package vo.alarm_site;

public class ReportFeedbackDay {

	private String name;
	private Integer haiG;
	private Integer baG;
	private Integer other;
	private Integer total;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getHaiG() {
		return haiG;
	}
	public void setHaiG(Integer haiG) {
		this.haiG = haiG;
	}
	public Integer getBaG() {
		return baG;
	}
	public void setBaG(Integer baG) {
		this.baG = baG;
	}
	public Integer getTotal() {
		return total;
	}
	public void setTotal(Integer total) {
		this.total = total;
	}
	public Integer getOther() {
		return other;
	}
	public void setOther(Integer other) {
		this.other = other;
	}
	private String chuaXuly;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS.ID
     *
     * @return the value of FB_PROCESS.ID
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    private String tlChuaXuly;
    private Integer trongHan;
	private Integer quaHan;
	private String tlQuaHan;
	private String tlTrongHan;
	
    public String getChuaXuly() {
		return chuaXuly;
	}

	public void setChuaXuly(String chuaXuly) {
		this.chuaXuly = chuaXuly;
	}

	public String getTlChuaXuly() {
		return tlChuaXuly;
	}

	public void setTlChuaXuly(String tlChuaXuly) {
		this.tlChuaXuly = tlChuaXuly;
	}

	public Integer getTrongHan() {
		return trongHan;
	}

	public void setTrongHan(Integer trongHan) {
		this.trongHan = trongHan;
	}

	public Integer getQuaHan() {
		return quaHan;
	}

	public void setQuaHan(Integer quaHan) {
		this.quaHan = quaHan;
	}

	public String getTlQuaHan() {
		return tlQuaHan;
	}

	public void setTlQuaHan(String tlQuaHan) {
		this.tlQuaHan = tlQuaHan;
	}

	public String getTlTrongHan() {
		return tlTrongHan;
	}

	public void setTlTrongHan(String tlTrongHan) {
		this.tlTrongHan = tlTrongHan;
	}
	
	private String province;
	private String provinceName;
	public String getProvince() {
		return province;
	}
	public void setProvince(String province) {
		this.province = province;
	}
	public String getProvinceName() {
		return provinceName;
	}
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}
	private String district;
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	
	private String team;
	public String getTeam() {
		return team;
	}
	public void setTeam(String team) {
		this.team = team;
	}
	
}
