package vo;

import java.io.Serializable;
import java.util.Date;

public class AlDyRpFinishRate implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.ID
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.DAY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.SYSTEM
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private String system;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.TO_DURATION
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private Integer toDuration;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.QTY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private Integer qty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AL_DY_RP_FINISH_RATE.ALARM_CLASS
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private String alarmClass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table AL_DY_RP_FINISH_RATE
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.ID
     *
     * @return the value of AL_DY_RP_FINISH_RATE.ID
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.ID
     *
     * @param id the value for AL_DY_RP_FINISH_RATE.ID
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.DAY
     *
     * @return the value of AL_DY_RP_FINISH_RATE.DAY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.DAY
     *
     * @param day the value for AL_DY_RP_FINISH_RATE.DAY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.SYSTEM
     *
     * @return the value of AL_DY_RP_FINISH_RATE.SYSTEM
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.SYSTEM
     *
     * @param system the value for AL_DY_RP_FINISH_RATE.SYSTEM
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setSystem(String system) {
        this.system = system;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.TO_DURATION
     *
     * @return the value of AL_DY_RP_FINISH_RATE.TO_DURATION
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public Integer getToDuration() {
        return toDuration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.TO_DURATION
     *
     * @param toDuration the value for AL_DY_RP_FINISH_RATE.TO_DURATION
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setToDuration(Integer toDuration) {
        this.toDuration = toDuration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.QTY
     *
     * @return the value of AL_DY_RP_FINISH_RATE.QTY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.QTY
     *
     * @param qty the value for AL_DY_RP_FINISH_RATE.QTY
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.CREATE_DATE
     *
     * @return the value of AL_DY_RP_FINISH_RATE.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.CREATE_DATE
     *
     * @param createDate the value for AL_DY_RP_FINISH_RATE.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AL_DY_RP_FINISH_RATE.ALARM_CLASS
     *
     * @return the value of AL_DY_RP_FINISH_RATE.ALARM_CLASS
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public String getAlarmClass() {
        return alarmClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AL_DY_RP_FINISH_RATE.ALARM_CLASS
     *
     * @param alarmClass the value for AL_DY_RP_FINISH_RATE.ALARM_CLASS
     *
     * @ibatorgenerated Mon Dec 17 14:53:02 ICT 2012
     */
    public void setAlarmClass(String alarmClass) {
        this.alarmClass = alarmClass;
    }
    
    private String rate;

	public String getRate() {
		return rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}
}