package vo;

import java.io.Serializable;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

public class CostWork implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.ID
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.EXPENSES_CODE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    @NotEmpty()
    private String expensesCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.WORK_NAME
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    @NotEmpty()
    private String workName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.WORK_SUPER
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    @NotNull()
    private Integer workSuper;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.ROOT_NO
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private Integer rootNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.WORK_CONTENT
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private String workContent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.ORDERING
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private Integer ordering;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COST_WORK.IS_ENABLE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private String isEnable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table COST_WORK
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.ID
     *
     * @return the value of COST_WORK.ID
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.ID
     *
     * @param id the value for COST_WORK.ID
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.EXPENSES_CODE
     *
     * @return the value of COST_WORK.EXPENSES_CODE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public String getExpensesCode() {
        return expensesCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.EXPENSES_CODE
     *
     * @param expensesCode the value for COST_WORK.EXPENSES_CODE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setExpensesCode(String expensesCode) {
        this.expensesCode = expensesCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.WORK_NAME
     *
     * @return the value of COST_WORK.WORK_NAME
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public String getWorkName() {
        return workName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.WORK_NAME
     *
     * @param workName the value for COST_WORK.WORK_NAME
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setWorkName(String workName) {
        this.workName = workName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.WORK_SUPER
     *
     * @return the value of COST_WORK.WORK_SUPER
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public Integer getWorkSuper() {
        return workSuper;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.WORK_SUPER
     *
     * @param workSuper the value for COST_WORK.WORK_SUPER
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setWorkSuper(Integer workSuper) {
        this.workSuper = workSuper;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.ROOT_NO
     *
     * @return the value of COST_WORK.ROOT_NO
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public Integer getRootNo() {
        return rootNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.ROOT_NO
     *
     * @param rootNo the value for COST_WORK.ROOT_NO
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setRootNo(Integer rootNo) {
        this.rootNo = rootNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.WORK_CONTENT
     *
     * @return the value of COST_WORK.WORK_CONTENT
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public String getWorkContent() {
        return workContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.WORK_CONTENT
     *
     * @param workContent the value for COST_WORK.WORK_CONTENT
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setWorkContent(String workContent) {
        this.workContent = workContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.ORDERING
     *
     * @return the value of COST_WORK.ORDERING
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.ORDERING
     *
     * @param ordering the value for COST_WORK.ORDERING
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COST_WORK.IS_ENABLE
     *
     * @return the value of COST_WORK.IS_ENABLE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COST_WORK.IS_ENABLE
     *
     * @param isEnable the value for COST_WORK.IS_ENABLE
     *
     * @ibatorgenerated Thu May 09 09:42:43 ICT 2013
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }
    
    public String getOrderingStr() {
		return orderingStr;
	}

	public void setOrderingStr(String orderingStr) {
		this.orderingStr = orderingStr;
	}

	public String getWorkSuperStr() {
		return workSuperStr;
	}

	public void setWorkSuperStr(String workSuperStr) {
		this.workSuperStr = workSuperStr;
	}

	public String getExpensesName() {
		return expensesName;
	}

	public void setExpensesName(String expensesName) {
		this.expensesName = expensesName;
	}

	private String orderingStr;
    private String workSuperStr;
    private String expensesName;
    
}