package vo;

import java.io.Serializable;

import org.hibernate.validator.constraints.NotEmpty;

public class CSeversTelnet implements Serializable {

    private Integer serverId;
    @NotEmpty()
    private String serverName;
    @NotEmpty()
    private String ipAddress;
    private Integer port;
    @NotEmpty()
    private String telnetUser;
    @NotEmpty()
    private String telnetPassword;
    @NotEmpty()
    private String loginTime;
    private String description;
    @NotEmpty()
    private String alarmName;
    @NotEmpty()
    private String type;
    private Integer ordering;
    private String function;
    private String deviceType;
    @NotEmpty()
    private String alarmType;
    private String command;
    @NotEmpty()
    private String node;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table C_SERVERS_TELNET
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.SERVER_ID
     *
     * @return the value of C_SERVERS_TELNET.SERVER_ID
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.SERVER_ID
     *
     * @param serverId the value for C_SERVERS_TELNET.SERVER_ID
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.SERVER_NAME
     *
     * @return the value of C_SERVERS_TELNET.SERVER_NAME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.SERVER_NAME
     *
     * @param serverName the value for C_SERVERS_TELNET.SERVER_NAME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.IP_ADDRESS
     *
     * @return the value of C_SERVERS_TELNET.IP_ADDRESS
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.IP_ADDRESS
     *
     * @param ipAddress the value for C_SERVERS_TELNET.IP_ADDRESS
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.PORT
     *
     * @return the value of C_SERVERS_TELNET.PORT
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.PORT
     *
     * @param port the value for C_SERVERS_TELNET.PORT
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.TELNET_USER
     *
     * @return the value of C_SERVERS_TELNET.TELNET_USER
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getTelnetUser() {
        return telnetUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.TELNET_USER
     *
     * @param telnetUser the value for C_SERVERS_TELNET.TELNET_USER
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setTelnetUser(String telnetUser) {
        this.telnetUser = telnetUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.TELNET_PASSWORD
     *
     * @return the value of C_SERVERS_TELNET.TELNET_PASSWORD
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getTelnetPassword() {
        return telnetPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.TELNET_PASSWORD
     *
     * @param telnetPassword the value for C_SERVERS_TELNET.TELNET_PASSWORD
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setTelnetPassword(String telnetPassword) {
        this.telnetPassword = telnetPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.LOGIN_TIME
     *
     * @return the value of C_SERVERS_TELNET.LOGIN_TIME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.LOGIN_TIME
     *
     * @param loginTime the value for C_SERVERS_TELNET.LOGIN_TIME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.DESCRIPTION
     *
     * @return the value of C_SERVERS_TELNET.DESCRIPTION
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.DESCRIPTION
     *
     * @param description the value for C_SERVERS_TELNET.DESCRIPTION
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.ALARM_NAME
     *
     * @return the value of C_SERVERS_TELNET.ALARM_NAME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.ALARM_NAME
     *
     * @param alarmName the value for C_SERVERS_TELNET.ALARM_NAME
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.TYPE
     *
     * @return the value of C_SERVERS_TELNET.TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.TYPE
     *
     * @param type the value for C_SERVERS_TELNET.TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.ORDERING
     *
     * @return the value of C_SERVERS_TELNET.ORDERING
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.ORDERING
     *
     * @param ordering the value for C_SERVERS_TELNET.ORDERING
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.FUNCTION
     *
     * @return the value of C_SERVERS_TELNET.FUNCTION
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.FUNCTION
     *
     * @param function the value for C_SERVERS_TELNET.FUNCTION
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setFunction(String function) {
        this.function = function;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.DEVICE_TYPE
     *
     * @return the value of C_SERVERS_TELNET.DEVICE_TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.DEVICE_TYPE
     *
     * @param deviceType the value for C_SERVERS_TELNET.DEVICE_TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column C_SERVERS_TELNET.ALARM_TYPE
     *
     * @return the value of C_SERVERS_TELNET.ALARM_TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column C_SERVERS_TELNET.ALARM_TYPE
     *
     * @param alarmType the value for C_SERVERS_TELNET.ALARM_TYPE
     *
     * @ibatorgenerated Tue Jan 08 17:04:35 ICT 2013
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType;
    }

	public String getCommand() {
		return command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public String getNode() {
		return node;
	}

	public void setNode(String node) {
		this.node = node;
	}

}