package vo;

import java.io.Serializable;
import java.util.Date;

public class FbProcessDetail implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.ID
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.FB_CODE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private String fbCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.PROCESS_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private Date processDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.PROCESS_CONTENT
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private String processContent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.CREATED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private String createdBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.CREATE_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.MODIFIED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private String modifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FB_PROCESS_DETAIL.MODIFY_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private Date modifyDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table FB_PROCESS_DETAIL
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.ID
     *
     * @return the value of FB_PROCESS_DETAIL.ID
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.ID
     *
     * @param id the value for FB_PROCESS_DETAIL.ID
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.FB_CODE
     *
     * @return the value of FB_PROCESS_DETAIL.FB_CODE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public String getFbCode() {
        return fbCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.FB_CODE
     *
     * @param fbCode the value for FB_PROCESS_DETAIL.FB_CODE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setFbCode(String fbCode) {
        this.fbCode = fbCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.PROCESS_DATE
     *
     * @return the value of FB_PROCESS_DETAIL.PROCESS_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.PROCESS_DATE
     *
     * @param processDate the value for FB_PROCESS_DETAIL.PROCESS_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.PROCESS_CONTENT
     *
     * @return the value of FB_PROCESS_DETAIL.PROCESS_CONTENT
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public String getProcessContent() {
        return processContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.PROCESS_CONTENT
     *
     * @param processContent the value for FB_PROCESS_DETAIL.PROCESS_CONTENT
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setProcessContent(String processContent) {
        this.processContent = processContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.CREATED_BY
     *
     * @return the value of FB_PROCESS_DETAIL.CREATED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.CREATED_BY
     *
     * @param createdBy the value for FB_PROCESS_DETAIL.CREATED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.CREATE_DATE
     *
     * @return the value of FB_PROCESS_DETAIL.CREATE_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.CREATE_DATE
     *
     * @param createDate the value for FB_PROCESS_DETAIL.CREATE_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.MODIFIED_BY
     *
     * @return the value of FB_PROCESS_DETAIL.MODIFIED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.MODIFIED_BY
     *
     * @param modifiedBy the value for FB_PROCESS_DETAIL.MODIFIED_BY
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FB_PROCESS_DETAIL.MODIFY_DATE
     *
     * @return the value of FB_PROCESS_DETAIL.MODIFY_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FB_PROCESS_DETAIL.MODIFY_DATE
     *
     * @param modifyDate the value for FB_PROCESS_DETAIL.MODIFY_DATE
     *
     * @ibatorgenerated Wed Nov 07 15:47:41 ICT 2012
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}