package vo;

import java.io.Serializable;

public class QldnDonGiaDien implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.ID_TRAM
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String idTram;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG_LOAI
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dgLoai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG1_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dg1Gia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG3_MUC1
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dg3Muc1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG3_MUC2
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dg3Muc2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG3_MUC3
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dg3Muc3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG_TL_KD
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dgTlKd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG_TL_KD_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dgTlKdGia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG_TL_SX
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dgTlSx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QLDN_DON_GIA_DIEN.DG_TL_SX_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private String dgTlSxGia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table QLDN_DON_GIA_DIEN
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.ID_TRAM
     *
     * @return the value of QLDN_DON_GIA_DIEN.ID_TRAM
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getIdTram() {
        return idTram;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.ID_TRAM
     *
     * @param idTram the value for QLDN_DON_GIA_DIEN.ID_TRAM
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setIdTram(String idTram) {
        this.idTram = idTram;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG_LOAI
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG_LOAI
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDgLoai() {
        return dgLoai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG_LOAI
     *
     * @param dgLoai the value for QLDN_DON_GIA_DIEN.DG_LOAI
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDgLoai(String dgLoai) {
        this.dgLoai = dgLoai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG1_GIA
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG1_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDg1Gia() {
        return dg1Gia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG1_GIA
     *
     * @param dg1Gia the value for QLDN_DON_GIA_DIEN.DG1_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDg1Gia(String dg1Gia) {
        this.dg1Gia = dg1Gia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC1
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG3_MUC1
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDg3Muc1() {
        return dg3Muc1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC1
     *
     * @param dg3Muc1 the value for QLDN_DON_GIA_DIEN.DG3_MUC1
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDg3Muc1(String dg3Muc1) {
        this.dg3Muc1 = dg3Muc1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC2
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG3_MUC2
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDg3Muc2() {
        return dg3Muc2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC2
     *
     * @param dg3Muc2 the value for QLDN_DON_GIA_DIEN.DG3_MUC2
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDg3Muc2(String dg3Muc2) {
        this.dg3Muc2 = dg3Muc2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC3
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG3_MUC3
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDg3Muc3() {
        return dg3Muc3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG3_MUC3
     *
     * @param dg3Muc3 the value for QLDN_DON_GIA_DIEN.DG3_MUC3
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDg3Muc3(String dg3Muc3) {
        this.dg3Muc3 = dg3Muc3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG_TL_KD
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG_TL_KD
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDgTlKd() {
        return dgTlKd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG_TL_KD
     *
     * @param dgTlKd the value for QLDN_DON_GIA_DIEN.DG_TL_KD
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDgTlKd(String dgTlKd) {
        this.dgTlKd = dgTlKd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG_TL_KD_GIA
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG_TL_KD_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDgTlKdGia() {
        return dgTlKdGia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG_TL_KD_GIA
     *
     * @param dgTlKdGia the value for QLDN_DON_GIA_DIEN.DG_TL_KD_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDgTlKdGia(String dgTlKdGia) {
        this.dgTlKdGia = dgTlKdGia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG_TL_SX
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG_TL_SX
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDgTlSx() {
        return dgTlSx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG_TL_SX
     *
     * @param dgTlSx the value for QLDN_DON_GIA_DIEN.DG_TL_SX
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDgTlSx(String dgTlSx) {
        this.dgTlSx = dgTlSx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QLDN_DON_GIA_DIEN.DG_TL_SX_GIA
     *
     * @return the value of QLDN_DON_GIA_DIEN.DG_TL_SX_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public String getDgTlSxGia() {
        return dgTlSxGia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QLDN_DON_GIA_DIEN.DG_TL_SX_GIA
     *
     * @param dgTlSxGia the value for QLDN_DON_GIA_DIEN.DG_TL_SX_GIA
     *
     * @ibatorgenerated Tue Jul 04 15:55:34 ICT 2017
     */
    public void setDgTlSxGia(String dgTlSxGia) {
        this.dgTlSxGia = dgTlSxGia;
    }
}