package vo;

import java.io.Serializable;
import java.util.Date;

public class SysDefineSmsEmail implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.ID
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.GROUP_TYPE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String groupType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.GROUP_NAME
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String groupName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.GROUP_USER
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String groupUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.IS_ENABLE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String isEnable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.ORDERING
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private Integer ordering;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.CREATED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String createdBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.MODIFIED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String modifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.MODIFY_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private Date modifyDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_DEFINE_SMS_EMAIL.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_DEFINE_SMS_EMAIL
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.ID
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.ID
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.ID
     *
     * @param id the value for SYS_DEFINE_SMS_EMAIL.ID
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_TYPE
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.GROUP_TYPE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_TYPE
     *
     * @param groupType the value for SYS_DEFINE_SMS_EMAIL.GROUP_TYPE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_NAME
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.GROUP_NAME
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_NAME
     *
     * @param groupName the value for SYS_DEFINE_SMS_EMAIL.GROUP_NAME
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_USER
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.GROUP_USER
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getGroupUser() {
        return groupUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.GROUP_USER
     *
     * @param groupUser the value for SYS_DEFINE_SMS_EMAIL.GROUP_USER
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setGroupUser(String groupUser) {
        this.groupUser = groupUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.IS_ENABLE
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.IS_ENABLE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.IS_ENABLE
     *
     * @param isEnable the value for SYS_DEFINE_SMS_EMAIL.IS_ENABLE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.ORDERING
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.ORDERING
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.ORDERING
     *
     * @param ordering the value for SYS_DEFINE_SMS_EMAIL.ORDERING
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.CREATED_BY
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.CREATED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.CREATED_BY
     *
     * @param createdBy the value for SYS_DEFINE_SMS_EMAIL.CREATED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.CREATE_DATE
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.CREATE_DATE
     *
     * @param createDate the value for SYS_DEFINE_SMS_EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.MODIFIED_BY
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.MODIFIED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.MODIFIED_BY
     *
     * @param modifiedBy the value for SYS_DEFINE_SMS_EMAIL.MODIFIED_BY
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.MODIFY_DATE
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.MODIFY_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.MODIFY_DATE
     *
     * @param modifyDate the value for SYS_DEFINE_SMS_EMAIL.MODIFY_DATE
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_DEFINE_SMS_EMAIL.DESCRIPTION
     *
     * @return the value of SYS_DEFINE_SMS_EMAIL.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_DEFINE_SMS_EMAIL.DESCRIPTION
     *
     * @param description the value for SYS_DEFINE_SMS_EMAIL.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 16 10:26:30 ICT 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }
}