package vo;

import java.io.Serializable;
import java.util.Date;

public class SysParameters implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.ID
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.CODE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.NAME
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.VALUE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String value;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.VALUE_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String valueEx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.VALUE_EX2
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String valueEx2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.VALUE_NUMBER
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Float valueNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.VALUE_NUMBER_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Float valueNumberEx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.ORDERING
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Integer ordering;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.CREATED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String createdBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.CREATE_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.MODIFIED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String modifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.MODIFY_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private Date modifyDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.TRANG_THAI
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String trangThai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_PARAMETERS.MA_TT
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private String maTt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.ID
     *
     * @return the value of SYS_PARAMETERS.ID
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.ID
     *
     * @param id the value for SYS_PARAMETERS.ID
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.CODE
     *
     * @return the value of SYS_PARAMETERS.CODE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.CODE
     *
     * @param code the value for SYS_PARAMETERS.CODE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.NAME
     *
     * @return the value of SYS_PARAMETERS.NAME
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.NAME
     *
     * @param name the value for SYS_PARAMETERS.NAME
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.VALUE
     *
     * @return the value of SYS_PARAMETERS.VALUE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.VALUE
     *
     * @param value the value for SYS_PARAMETERS.VALUE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.VALUE_EX
     *
     * @return the value of SYS_PARAMETERS.VALUE_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getValueEx() {
        return valueEx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.VALUE_EX
     *
     * @param valueEx the value for SYS_PARAMETERS.VALUE_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setValueEx(String valueEx) {
        this.valueEx = valueEx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.VALUE_EX2
     *
     * @return the value of SYS_PARAMETERS.VALUE_EX2
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getValueEx2() {
        return valueEx2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.VALUE_EX2
     *
     * @param valueEx2 the value for SYS_PARAMETERS.VALUE_EX2
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setValueEx2(String valueEx2) {
        this.valueEx2 = valueEx2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.VALUE_NUMBER
     *
     * @return the value of SYS_PARAMETERS.VALUE_NUMBER
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Float getValueNumber() {
        return valueNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.VALUE_NUMBER
     *
     * @param valueNumber the value for SYS_PARAMETERS.VALUE_NUMBER
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setValueNumber(Float valueNumber) {
        this.valueNumber = valueNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.VALUE_NUMBER_EX
     *
     * @return the value of SYS_PARAMETERS.VALUE_NUMBER_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Float getValueNumberEx() {
        return valueNumberEx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.VALUE_NUMBER_EX
     *
     * @param valueNumberEx the value for SYS_PARAMETERS.VALUE_NUMBER_EX
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setValueNumberEx(Float valueNumberEx) {
        this.valueNumberEx = valueNumberEx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.ORDERING
     *
     * @return the value of SYS_PARAMETERS.ORDERING
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.ORDERING
     *
     * @param ordering the value for SYS_PARAMETERS.ORDERING
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.CREATED_BY
     *
     * @return the value of SYS_PARAMETERS.CREATED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.CREATED_BY
     *
     * @param createdBy the value for SYS_PARAMETERS.CREATED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.CREATE_DATE
     *
     * @return the value of SYS_PARAMETERS.CREATE_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.CREATE_DATE
     *
     * @param createDate the value for SYS_PARAMETERS.CREATE_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.MODIFIED_BY
     *
     * @return the value of SYS_PARAMETERS.MODIFIED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.MODIFIED_BY
     *
     * @param modifiedBy the value for SYS_PARAMETERS.MODIFIED_BY
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.MODIFY_DATE
     *
     * @return the value of SYS_PARAMETERS.MODIFY_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.MODIFY_DATE
     *
     * @param modifyDate the value for SYS_PARAMETERS.MODIFY_DATE
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.TRANG_THAI
     *
     * @return the value of SYS_PARAMETERS.TRANG_THAI
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getTrangThai() {
        return trangThai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.TRANG_THAI
     *
     * @param trangThai the value for SYS_PARAMETERS.TRANG_THAI
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_PARAMETERS.MA_TT
     *
     * @return the value of SYS_PARAMETERS.MA_TT
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public String getMaTt() {
        return maTt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_PARAMETERS.MA_TT
     *
     * @param maTt the value for SYS_PARAMETERS.MA_TT
     *
     * @ibatorgenerated Thu Mar 10 16:41:57 ICT 2016
     */
    public void setMaTt(String maTt) {
        this.maTt = maTt;
    }
}