package vo;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class VRpDyTrx implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.DAY
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.BSCID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String bscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.CELLID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String cellid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.TRX
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String trx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.VENDOR
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String vendor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.SITE
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String site;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_TRX.STATUS
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table V_RP_DY_TRX
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.DAY
     *
     * @return the value of V_RP_DY_TRX.DAY
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.DAY
     *
     * @param day the value for V_RP_DY_TRX.DAY
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.BSCID
     *
     * @return the value of V_RP_DY_TRX.BSCID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getBscid() {
        return bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.BSCID
     *
     * @param bscid the value for V_RP_DY_TRX.BSCID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setBscid(String bscid) {
        this.bscid = bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.CELLID
     *
     * @return the value of V_RP_DY_TRX.CELLID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getCellid() {
        return cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.CELLID
     *
     * @param cellid the value for V_RP_DY_TRX.CELLID
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setCellid(String cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.TRX
     *
     * @return the value of V_RP_DY_TRX.TRX
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getTrx() {
        return trx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.TRX
     *
     * @param trx the value for V_RP_DY_TRX.TRX
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setTrx(String trx) {
        this.trx = trx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.VENDOR
     *
     * @return the value of V_RP_DY_TRX.VENDOR
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.VENDOR
     *
     * @param vendor the value for V_RP_DY_TRX.VENDOR
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.SITE
     *
     * @return the value of V_RP_DY_TRX.SITE
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.SITE
     *
     * @param site the value for V_RP_DY_TRX.SITE
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setSite(String site) {
        this.site = site;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_TRX.STATUS
     *
     * @return the value of V_RP_DY_TRX.STATUS
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_TRX.STATUS
     *
     * @param status the value for V_RP_DY_TRX.STATUS
     *
     * @ibatorgenerated Tue Nov 12 09:25:19 ICT 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getDayStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		if(day != null)
			return df.format(day);
		else
			return null;
	}
}