package dao;

import vo.AlCommandDangerous;

public interface AlCommandDangerousDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    void insert(AlCommandDangerous record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    void insertSelective(AlCommandDangerous record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    AlCommandDangerous selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    int updateByPrimaryKeySelective(AlCommandDangerous record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_COMMAND_DANGEROUS
     *
     * @ibatorgenerated Fri Aug 30 10:08:10 ICT 2013
     */
    int updateByPrimaryKey(AlCommandDangerous record);
}