package dao;

import java.util.List;

import vo.AlDyRpErrorPower;
import vo.SYS_PARAMETER;
import vo.WarningDipSame;

public interface AlDyRpErrorPowerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_DY_RP_ERROR_POWER
     *
     * @ibatorgenerated Thu May 30 10:31:11 ICT 2013
     */
    void insert(AlDyRpErrorPower record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AL_DY_RP_ERROR_POWER
     *
     * @ibatorgenerated Thu May 30 10:31:11 ICT 2013
     */
    void insertSelective(AlDyRpErrorPower record);
    

	int updateByPrimaryKeySelective(AlDyRpErrorPower record);
 
    int deleteByPrimaryKey(Integer id);

    
    AlDyRpErrorPower selectByPrimaryKey(int parseInt);

	int getStartJobErrorPower(String startTime);

	/*List<VAlDyRpErrorPower> getAlDyRpErrorPowerFilter(String sday,
			String eday, String bscid, String site, String teamProcess,
			int order, String column);*/

	List<AlDyRpErrorPower> getVAlDyRpErrorPowerFilter(String sday,
			String eday, String bscid, String site, String teamProcess,
			int order, String column);

	List<WarningDipSame> getAlarmSameSystem(String bscID, String device,
			String day);

	List<SYS_PARAMETER> titleErrorPower(String typeForm);

	int getStartJobErrorPower();
}