package dao;

import java.util.List;

import vo.CableTransmissionPartners;

public interface CableTransmissionPartnersDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    void insert(CableTransmissionPartners record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    void insertSelective(CableTransmissionPartners record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    CableTransmissionPartners selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    int updateByPrimaryKeySelective(CableTransmissionPartners record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CABLE_TRANSMISSION_PARTNERS
     *
     * @ibatorgenerated Thu Feb 27 10:28:30 ICT 2014
     */
    int updateByPrimaryKey(CableTransmissionPartners record);

	List<CableTransmissionPartners> getCableTransmissionPartner(String vendor,
			String odfName, String transmission, Integer startRecord,
			Integer endRecord, String sortfield, String sortorder,
			String strWhere);

	int countCableTransmissionPn(String vendor, String odfName,
			String transmission, String strWhere);

	List<CableTransmissionPartners> checkCableTransmissionPnUk(String vendor,
			String odfName, 
			String fiberCable,
			String odfPos,String transmission, String threadName, String odfDestination, String portDestination, 
			String site, String id);

	int updateByUniqueKey(CableTransmissionPartners record);

	List<CableTransmissionPartners> getVendorListPartners();
}