package dao;

import java.util.List;

import vo.CTableConfig;
import vo.SYS_PARAMETER;

public interface CTableConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    void insert(CTableConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    void insertSelective(CTableConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    CTableConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    int updateByPrimaryKeySelective(CTableConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_TABLE_CONFIG
     *
     * @ibatorgenerated Tue Oct 08 18:20:28 PDT 2013
     */
    int updateByPrimaryKey(CTableConfig record);

	List<CTableConfig> getTableConfigsForGrid(String tableName);

	List<CTableConfig> getColumnList(String tableName);

	List<CTableConfig> getTableConfigGet(String tableName, String columnName);

	List<String> getGroupList(String nameTable);

	//lay danh sach cac cot hien thi tren email
	List<CTableConfig> getColumnMailList(String tableName, String blockId);

	//lay tieu de trang web bao cao email. AnhCTV:06/11/2015
	List<SYS_PARAMETER> titleReportMail(String function, String mailid,
			String blockid);

	List<CTableConfig> getColumnReportBlock(String reportType, String blockId);

	List<SYS_PARAMETER> titleReportUCTT(String function, String region);
	
}