package dao;

import java.util.List;

import vo.FbProcess;
import vo.FbProcessFilter;
import vo.FbReport;
import vo.FbType;
import vo.MDepartment;
import vo.SYS_PARAMETER;
import vo.VRFbProcessDay;
import vo.alarm_site.ReportFeedbackDay;


public interface FbProcessDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    void insert(FbProcess record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    void insertSelective(FbProcess record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    FbProcess selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    int updateByPrimaryKeySelective(FbProcess record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table FB_PROCESS
     *
     * @ibatorgenerated Sat Nov 24 11:41:43 ICT 2012
     */
    int updateByPrimaryKey(FbProcess record);

	List<FbProcess> getFbProcessFilter(String startDate, String endDate,
			String column, String order);

	int countRowDaXuLy(String startDate, String endDate);

	List<FbProcess> getQLThongTinPA(String maPA, String loaiPA,
			String loaiMang, String thoiGianPAFrom, String thoiGianPATo,
			String soTB, String loaiTB, String thoiGianXLFrom,
			String thoiGianXLTo, String deptProcess, String team, String trangThai, String tinhThanh,
			String quanHuyen, String phuongXa, String vipCode, Integer fbIbc, String column, String order);
	List<FbProcess> getGeneralFeedback(String maPA, String loaiPA,
			String loaiMang, String thoiGianPAFrom, String thoiGianPATo,
			String soTB, String loaiTB, String thoiGianXLFrom,
			String thoiGianXLTo, String deptProcess, String team, String trangThai, String tinhThanh,
			String quanHuyen, String phuongXa, String vipCode, String fbIbc, String fbSendTelecom, 
			String site, String column, String order);
	 
	FbProcess selectById(String id);

	FbProcess selectJoinFBProById(String id);

	List<FbProcess> selectFBTheoLo(String P_WHERE);

	int countSoLuongPA(String startDate, String endDate, String dieuKien);

	int updateFeedbackForTheoLo(FbProcess record);

	String danhSoHieuLo();

	List<SYS_PARAMETER> getQLTTFBList();

	List<SYS_PARAMETER> getTenLoaiTB();

	List<SYS_PARAMETER> getTenLoaiMang();

	void insertFbProcess(String soThueBao, String phuongXa, String quanHuyen,
			String tinhThanh, String maLoaiPhanAnh, String loaiPhanAnh,
			String noiDungPA, String thoiGianPA, String donViXL,
			String loaiMang, String idCentral);
	
	

	List<FbProcess> getSlFbTheoToVT(String startDate, String endDate,
			String deptProcess, String team, String fbSendTelecom, String fbDistrict);

	List<FbProcess> getSlFbTheoNguyenNhan(String startDate, String endDate, String fbSendTelecom, String fbDistrict);

	List<SYS_PARAMETER> titleForm(String typeForm);

	List<FbType> getFBTypeList();

	List<SYS_PARAMETER> networkTypeList();

	List<FbProcessFilter> getProcessList(FbProcessFilter filter, String column,
			Integer order);
	
	void insertFbProcessFilter(FbProcessFilter record);

	int deleteFbProcessFilter(Integer id);

	int updateFbProcessFilter(FbProcessFilter record);

	FbProcessFilter selectFbProcessFilterByID(int parseInt);

	List<MDepartment> getDepartmentFbList();

	void updateCoreService(String status, String repeats, String hourData, String hourDefault);

	List<MDepartment> getDepartmentByDistrict(String province, String district);

	List<VRFbProcessDay> getVRFbProcessDay(String startDate, String endDate);
    // Bao cao tong hop/chi tiet theo loai phan anh
	List<ReportFeedbackDay> getReportByFbType(String startDate, String endDate, String fbSendTelecom, String fbDistrict);
	List<FbProcess> getSlFbTheoLoaiPA(String startDate, String endDate,
			String fbType, String fbSendTelecom, String fbDistrict);
	
	List<ReportFeedbackDay> getReportByDepartment(String dept, String team, String startDate,
			String endDate, String fbSendTelecom, String fbDistrict );

	List<ReportFeedbackDay> getReportByDistrict(String province, String district, String startDate, String endDate, String fbSendTelecom);

	List<ReportFeedbackDay> getReportByCausedby(String startDate, String endDate, String fbSendTelecom, String fbDistrict);

	List<FbProcess> getSlFbTheoQuanHuyen(String startDate, String endDate, String province,
			String district, String fbSendTelecom);

	List<FbProcess> getGridForFeedbackWeek(String startDate, String endDate,
			String fbType, String fbSendTelecom, String username);

	int updateFeedbackDeleted(FbProcess record);

	List<FbProcess> getFbDeletedList(String maPA, String loaiPA,
			String loaiMang, String thoiGianPAFrom, String thoiGianPATo,
			String soTB, String loaiTB, String thoiGianXLFrom,
			String thoiGianXLTo, String deptProcess, String team,
			String trangThai, String tinhThanh, String quanHuyen,
			String phuongXa, String vipCode, Integer fbIbc, String column,
			String order);
	/*Lay danh sach du lieu thoi gian xu ly, con lai cua FB de dem nguoc. AnhCTV 11/11/2015*/
	List<FbProcess> getTimeCountdownFB(FbProcess filter,String thoiGianPAFrom,String thoiGianPATo,String thoiGianXLFrom,String thoiGianXLTo,String function);

	//lay danh sach noi dung DVT phan hoi
	List<String> getDvtFeedbackContentList();

	// chuyen FB. AnhCTV: 14/11/2015
	void removeFbProcess(FbProcess record);
	
	// checkDiemDen . AnhCTV:10/06/2016
	void checkDiemDen(String checkedList, String status, String username);

	// LAY DANH SACH FB DIEM DEN. . AnhCTV:14/06/2016
	List<FbProcess> getFeedbackDiemDen(String loaiPA, String thoiGianPAFrom,
			String thoiGianPATo, String thoiGianXLFrom, String thoiGianXLTo,
			String deptProcess, String team, String status);
	
	// Lay tieu de cho cac form bieu do FB. AnhCTV:04/07/2016
	List<SYS_PARAMETER> titleFBChart(String function);

	// Lay du lieu do vao bieu do so luong FB. AnhCTV:04/07/2016
	List<String> getDataFeedbackChart(String sdateChar, String edateChar,
			String region, String province, String district, String dept,
			String team, String fb_type, String username, String function);
	
/*Bao co feedback theo ngay thang tuan quy nam. AnhCTV. 09/01.2018*/
	List<FbReport> getReportFBFBType(String sdate, String edate, Integer sweek, Integer smonth, Integer syear,
			String region, String province, String fbType, String status, String sqlWhere, String function,
			String reportType,String sqlReturn);

	List<FbReport> getReportFBDVTProcess(String sdate, String edate, Integer sweek, Integer smonth, Integer syear,
			String region, String province, String fbType, String status, String sqlWhere, String function,
			String reportType,String sqlReturn);

	List<FbReport> getReportFBRequest(String sdate, String edate, Integer sweek, Integer smonth, Integer syear,
			String region, String province, String fbType, String status, String sqlWhere, String function,
			String reportType,String sqlReturn);

	List<FbReport> getReportFBRise(String sdate, String edate, Integer sweek, Integer smonth, Integer syear, String region,
			String province, String fbType, String status, String sqlWhere, String function, String reportType,String sqlReturn);

	List<FbReport> getReportFBRegion(String sdate, String edate, String sweek, String smonth, String syear,
			String region, String province, String fbType, String status, String sqlWhere, String function,
			String reportType,String sqlReturn);
	
	/*// bao cao luy ke feedback . AnhCTV:15/06/2016
	List<FbProcess> getFeedbackLuyKe(String sdate, String edate, String region,
			String province, String fbType, String status);*/

}