package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.HQualityNetwork;
import vo.SYS_PARAMETER;

public class HQualityNetworkDAOImpl extends SqlMapClientDaoSupport implements HQualityNetworkDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public HQualityNetworkDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        HQualityNetwork key = new HQualityNetwork();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("H_QUALITY_NETWORK.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public void insert(HQualityNetwork record) {
        getSqlMapClientTemplate().insert("H_QUALITY_NETWORK.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public void insertSelective(HQualityNetwork record) {
        getSqlMapClientTemplate().insert("H_QUALITY_NETWORK.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public HQualityNetwork selectByPrimaryKey(Integer id) {
        HQualityNetwork key = new HQualityNetwork();
        key.setId(id);
        HQualityNetwork record = (HQualityNetwork) getSqlMapClientTemplate().queryForObject("H_QUALITY_NETWORK.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public int updateByPrimaryKeySelective(HQualityNetwork record) {
        int rows = getSqlMapClientTemplate().update("H_QUALITY_NETWORK.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_QUALITY_NETWORK
     *
     * @ibatorgenerated Tue Feb 05 10:48:31 ICT 2013
     */
    public int updateByPrimaryKey(HQualityNetwork record) {
        int rows = getSqlMapClientTemplate().update("H_QUALITY_NETWORK.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	@Override
	public List<String> getQualityName(String groupName) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_GROUP_NAME", groupName);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("H_QUALITY_NETWORK.getQualityName", map);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> titleQualityNetwork(String typeForm) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_TYPE_FORM", typeForm);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("H_QUALITY_NETWORK.titleQualityNetwork", map);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<HQualityNetwork> getQualityNetworkList(String groupName,String qualityName, String column, int order) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_GROUP_NAME", groupName);
		map.put("P_QUALITY_NAME", qualityName);
		map.put("P_COLUMN", column);
		map.put("P_ORDER", order);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("H_QUALITY_NETWORK.getQualityNetworkList", map);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getUnitList() {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("H_QUALITY_NETWORK.getUnitList", map);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getConditionList() {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("H_QUALITY_NETWORK.getConditionList", map);
	}

	@Override
	public int update(HQualityNetwork record) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_ID", record.getId());
		parms.put("P_GROUP_NAME", record.getGroupName());
		parms.put("P_QUALITY_NAME", record.getQualityName());
		parms.put("P_QUALITY_CONDITION", record.getQualityCondition());
		parms.put("P_QUALITY_VALUE", record.getQualityValue());
		parms.put("P_QUALITY_UNIT", record.getQualityUnit());
		parms.put("P_MODIFIED_BY", record.getModifiedBy());
		parms.put("P_MODIFY_DATE", record.getModifyDate());
		parms.put("P_QUALITY_CODE", record.getQualityCode());
		parms.put("P_ORDERING", record.getOrdering());
        int rows = getSqlMapClientTemplate().update("H_QUALITY_NETWORK.UPDATE", parms);
        return rows;
	}
}