package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.MnTaiThietBi;

public class MnTaiThietBiDAOImpl extends SqlMapClientDaoSupport implements MnTaiThietBiDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_TAI_THIET_BI
     *
     * @ibatorgenerated Tue Mar 15 14:55:06 ICT 2016
     */
    public MnTaiThietBiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_TAI_THIET_BI
     *
     * @ibatorgenerated Tue Mar 15 14:55:06 ICT 2016
     */
    public void insert(MnTaiThietBi record) {
        getSqlMapClientTemplate().insert("MN_TAI_THIET_BI.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_TAI_THIET_BI
     *
     * @ibatorgenerated Tue Mar 15 14:55:06 ICT 2016
     */
    public void insertSelective(MnTaiThietBi record) {
        getSqlMapClientTemplate().insert("MN_TAI_THIET_BI.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	@Override
	public List<MnTaiThietBi> filterByMonth(String filterColumn, Integer month, String year, String region, String min,
			String max) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("p_column", filterColumn);
		map.put("p_month", month);
		map.put("p_year", year);
		map.put("p_region", region);
		map.put("p_min", min);
		map.put("p_max", max);
		return getSqlMapClientTemplate().queryForList("MN_TAI_THIET_BI.filterByMonth", map);
	}
}