package dao;

import java.util.List;

import vo.SchedulerJobLog;

public interface SchedulerJobLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DBA_SCHEDULER_JOB_LOG
     *
     * @ibatorgenerated Tue Oct 02 15:24:26 ICT 2012
     */
    void insert(SchedulerJobLog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DBA_SCHEDULER_JOB_LOG
     *
     * @ibatorgenerated Tue Oct 02 15:24:26 ICT 2012
     */
    void insertSelective(SchedulerJobLog record);
   /* List<SchedulerJobLog> filter(String jobName);*/

	List<SchedulerJobLog> filter(String user, int startRecord, int endRecord,
			String column, int order);

	Integer countRow(String user);
}