package dao;

import java.util.List;

import vo.SysBlacklist;

public interface SysBlacklistDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    int deleteByPrimaryKey(String alarmId, String smsEmail, String username);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    void insert(SysBlacklist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    void insertSelective(SysBlacklist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    SysBlacklist selectByPrimaryKey(String alarmId, String smsEmail, String username);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    int updateByPrimaryKeySelective(SysBlacklist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_BLACKLIST
     *
     * @ibatorgenerated Sat Oct 19 00:03:33 ICT 2013
     */
    int updateByPrimaryKey(SysBlacklist record);

	List<SysBlacklist> getSysBlacklistByUsername(String username, String alarmType, String alarmId, String alarmName);

	int insertSysBlacklistByUser(String username, String checkedlist);

	int deleteSysBlacklist(String checkedlist);

	int updateSysBlackList(String id, String isEnable, String smsEmail);

	int insertBlacklistByParameter(String username, String checkedlist);
}