package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.AlShift;
import vo.SysMailParameter;

public class SysMailParameterDAOImpl extends SqlMapClientDaoSupport implements SysMailParameterDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_MAIL_PARAMETER
     *
     * @ibatorgenerated Thu Nov 21 17:25:42 ICT 2013
     */
    public SysMailParameterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_MAIL_PARAMETER
     *
     * @ibatorgenerated Thu Nov 21 17:25:42 ICT 2013
     */
    public void insert(SysMailParameter record) {
        getSqlMapClientTemplate().insert("SYS_MAIL_PARAMETER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_MAIL_PARAMETER
     *
     * @ibatorgenerated Thu Nov 21 17:25:42 ICT 2013
     */
    public void insertSelective(SysMailParameter record) {
        getSqlMapClientTemplate().insert("SYS_MAIL_PARAMETER.ibatorgenerated_insertSelective", record);
    }
    //lay danh sach cac block cua mails
	@SuppressWarnings("unchecked")
	@Override
	public List<SysMailParameter> getBlockListReport(String mailID, String blockID) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_MAILID", mailID);
		map.put("P_BLOCKID", blockID);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_MAIL_PARAMETER.getBlockListReport", map);
	}
}