package dao;

import vo.SysSend;

public interface SysSendDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    void insert(SysSend record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    void insertSelective(SysSend record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    SysSend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    int updateByPrimaryKeySelective(SysSend record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_SEND
     *
     * @ibatorgenerated Sat Dec 28 00:42:53 ICT 2013
     */
    int updateByPrimaryKey(SysSend record);
}