package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.VAlHRnc;

public class VAlHRncDAOImpl extends SqlMapClientDaoSupport implements VAlHRncDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_RNC
     *
     * @ibatorgenerated Tue Dec 18 14:47:17 ICT 2012
     */
    public VAlHRncDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_RNC
     *
     * @ibatorgenerated Tue Dec 18 14:47:17 ICT 2012
     */
    public void insert(VAlHRnc record) {
        getSqlMapClientTemplate().insert("V_AL_H_RNC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_RNC
     *
     * @ibatorgenerated Tue Dec 18 14:47:17 ICT 2012
     */
    public void insertSelective(VAlHRnc record) {
        getSqlMapClientTemplate().insert("V_AL_H_RNC.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getRNCList(String team) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TEAM", team);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_RNC.getRNCList", parms);
		
	}
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getRNCSearch(String team, String term) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TEAM", team);
		parms.put("P_RNC", term);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_RNC.getRNCSearch", parms);
	}

	@Override
	public String selectTeamByRNC(String operator) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_RNC", operator);	
		parms.put("P_DATA", null);
		getSqlMapClientTemplate().queryForObject("V_AL_H_RNC.selectTeamByRNC", parms);
		String record = (String) parms.get("P_DATA");
    	return record;
		
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getRncByVendor(String vendor) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_VENDOR", vendor);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_RNC.getRncByVendor", parms);
	}
}