package dao;

import java.util.List;

import vo.VAlHRnc;

public interface VAlHRncDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_RNC
     *
     * @ibatorgenerated Tue Dec 18 14:47:17 ICT 2012
     */
    void insert(VAlHRnc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_RNC
     *
     * @ibatorgenerated Tue Dec 18 14:47:17 ICT 2012
     */
    void insertSelective(VAlHRnc record);

	List<String> getRNCList(String team);

	List<String> getRNCSearch(String team, String term);

	String selectTeamByRNC(String operator);
	
	List<String> getRncByVendor(String vendor);
}