package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.VAlHBsc;

public class VAlHBscDAOImpl extends SqlMapClientDaoSupport implements VAlHBscDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_BSC
     *
     * @ibatorgenerated Thu Nov 22 10:25:58 ICT 2012
     */
    public VAlHBscDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_BSC
     *
     * @ibatorgenerated Thu Nov 22 10:25:58 ICT 2012
     */
    public void insert(VAlHBsc record) {
        getSqlMapClientTemplate().insert("V_AL_H_BSC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_H_BSC
     *
     * @ibatorgenerated Thu Nov 22 10:25:58 ICT 2012
     */
    public void insertSelective(VAlHBsc record) {
        getSqlMapClientTemplate().insert("V_AL_H_BSC.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
	public List<VAlHBsc> getAll() {
    	return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getAll");
    }
	@Override
	public String selectTeamByBSC(String netWorkType,String operator) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_NETWORK", netWorkType);
		parms.put("P_BSC", operator);
		parms.put("P_DATA", null);
		getSqlMapClientTemplate().queryForObject("V_AL_H_BSC.selectTeamByBSC", parms);
		String record = (String) parms.get("P_DATA");
    	return record;
	}
	

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getSystemByVendor(String vendor) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_VENDOR", vendor);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getSystemByVendor", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getBscByVendor(String vendor) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_VENDOR", vendor);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getBscByVendor", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getBSCIDByTeam(String netWorkType, String team, String term) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_NETWORK", netWorkType);
		parms.put("P_TEAM", team);
		parms.put("P_BSC", term);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getBSCIDByTeam", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getBSC23GByTeam(String team) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TEAM", team);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getBSC23GByTeam", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getBSCIDByTeam(String team) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TEAM", team);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_AL_H_BSC.getBSCIDByTeam", parms);
	}
}