package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.VAlShiftCalendar;
import vo.VAlShiftFilter;

public class VAlShiftCalendarDAOImpl extends SqlMapClientDaoSupport implements VAlShiftCalendarDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_SHIFT_CALENDAR
     *
     * @ibatorgenerated Wed Apr 10 14:05:55 ICT 2013
     */
    public VAlShiftCalendarDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_SHIFT_CALENDAR
     *
     * @ibatorgenerated Wed Apr 10 14:05:55 ICT 2013
     */
    public void insert(VAlShiftCalendar record) {
        getSqlMapClientTemplate().insert("V_AL_SHIFT_CALENDAR.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_AL_SHIFT_CALENDAR
     *
     * @ibatorgenerated Wed Apr 10 14:05:55 ICT 2013
     */
    public void insertSelective(VAlShiftCalendar record) {
        getSqlMapClientTemplate().insert("V_AL_SHIFT_CALENDAR.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
   	@Override
   	public List<VAlShiftCalendar> getList(VAlShiftFilter filter,String column, int order){
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("p_AREA", filter.getArea());
   		map.put("p_WEEK", filter.getWeek());
   		map.put("p_YEAR", filter.getYear());
   		map.put("p_TEAM", filter.getTeam());
   		map.put("p_COLUMN", column);
   		map.put("p_ORDER", order);
   		map.put("p_DATA", null);
   		return getSqlMapClientTemplate().queryForList("V_AL_SHIFT_CALENDAR.getList", map);

   	}
}