package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
 
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.VAssetsImportWarehouse;

public class VAssetsImportWarehouseDAOImpl extends SqlMapClientDaoSupport implements VAssetsImportWarehouseDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_ASSETS_IMPORT_WAREHOUSE
     *
     * @ibatorgenerated Wed May 22 16:21:26 ICT 2013
     */
    public VAssetsImportWarehouseDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_ASSETS_IMPORT_WAREHOUSE
     *
     * @ibatorgenerated Wed May 22 16:21:26 ICT 2013
     */
    public void insert(VAssetsImportWarehouse record) {
        getSqlMapClientTemplate().insert("V_ASSETS_IMPORT_WAREHOUSE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_ASSETS_IMPORT_WAREHOUSE
     *
     * @ibatorgenerated Wed May 22 16:21:26 ICT 2013
     */
    public void insertSelective(VAssetsImportWarehouse record) {
        getSqlMapClientTemplate().insert("V_ASSETS_IMPORT_WAREHOUSE.ibatorgenerated_insertSelective", record);
    }
    
    public void insert() {
        getSqlMapClientTemplate().queryForList("V_ASSETS_IMPORT_WAREHOUSE.insert");
    }
    
    @SuppressWarnings("unchecked")
	public List<VAssetsImportWarehouse> getList(String asTypesId,String productCode, String column, int order){
    	Map<String, Object> map = new HashMap<String, Object>();
    	
    	map.put("p_AS_TYPES_ID", asTypesId);
    	map.put("p_PRODUCT_CODE",productCode);
    	map.put("p_COLUMN", column);
		map.put("p_ORDER", order);
		map.put("p_DATA", null);
		
		return getSqlMapClientTemplate().queryForList("V_ASSETS_IMPORT_WAREHOUSE.getList", map);
    }
    
    @SuppressWarnings("unchecked")
	public List<VAssetsImportWarehouse> getDataById(String id){
    	Map<String, Object> map = new HashMap<String, Object>();
    	
    	map.put("p_id",id); 
		map.put("p_DATA", null);
		
		return getSqlMapClientTemplate().queryForList("V_ASSETS_IMPORT_WAREHOUSE.getDataById", map);
    }
}