package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.VHCell3G;

public class VHCell3GDAOImpl extends SqlMapClientDaoSupport implements VHCell3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_CELL_3G
     *
     * @ibatorgenerated Mon Jan 07 09:10:17 ICT 2013
     */
    public VHCell3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_CELL_3G
     *
     * @ibatorgenerated Mon Jan 07 09:10:17 ICT 2013
     */
    public void insert(VHCell3G record) {
        getSqlMapClientTemplate().insert("V_H_CELL_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_CELL_3G
     *
     * @ibatorgenerated Mon Jan 07 09:10:17 ICT 2013
     */
    public void insertSelective(VHCell3G record) {
        getSqlMapClientTemplate().insert("V_H_CELL_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getAllCellByRnc(String bscid) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_OPERATOR", bscid);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_H_CELL_3G.getAllCellByRnc", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getSite3GByBsc(String bscid) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_OPERATOR", bscid);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_H_CELL_3G.getSite3GByBsc", parms);
	}
}