package dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.HProvincesCode;
import vo.VHProvincesCode;

public class VHProvincesCodeDAOImpl extends SqlMapClientDaoSupport implements VHProvincesCodeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_PROVINCES_CODE
     *
     * @ibatorgenerated Wed Oct 31 16:17:06 ICT 2012
     */
    public VHProvincesCodeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_PROVINCES_CODE
     *
     * @ibatorgenerated Wed Oct 31 16:17:06 ICT 2012
     */
    public void insert(VHProvincesCode record) {
        getSqlMapClientTemplate().insert("V_H_PROVINCES_CODE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_H_PROVINCES_CODE
     *
     * @ibatorgenerated Wed Oct 31 16:17:06 ICT 2012
     */
    public void insertSelective(VHProvincesCode record) {
        getSqlMapClientTemplate().insert("V_H_PROVINCES_CODE.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
	public List<VHProvincesCode> getDepCodeList(){
		List<VHProvincesCode> Provinces = getSqlMapClientTemplate().queryForList("V_H_PROVINCES_CODE.getDepCodeList");
		return Provinces;
    }
	
}