package dao;

import java.util.List;

import vo.VRpDySgsnSummary;

public interface VRpDySgsnSummaryDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_SGSN_SUMMARY
     *
     * @ibatorgenerated Fri Feb 01 11:13:13 ICT 2013
     */
    void insert(VRpDySgsnSummary record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_SGSN_SUMMARY
     *
     * @ibatorgenerated Fri Feb 01 11:13:13 ICT 2013
     */
    void insertSelective(VRpDySgsnSummary record);
    List<VRpDySgsnSummary> filerOfHomePage(String tableName, String day, String region);
    List<VRpDySgsnSummary> filter(String startDate, String endDate, String sgsnid);

	
}