package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.VRpDyIsoUtility;

public class VRpDyIsoUtilityDAOImpl extends SqlMapClientDaoSupport implements VRpDyIsoUtilityDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISO_UTILITY
     *
     * @ibatorgenerated Thu Jun 19 11:54:21 ICT 2014
     */
    public VRpDyIsoUtilityDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISO_UTILITY
     *
     * @ibatorgenerated Thu Jun 19 11:54:21 ICT 2014
     */
    public void insert(VRpDyIsoUtility record) {
        getSqlMapClientTemplate().insert("V_RP_DY_ISO_UTILITY.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISO_UTILITY
     *
     * @ibatorgenerated Thu Jun 19 11:54:21 ICT 2014
     */
    public void insertSelective(VRpDyIsoUtility record) {
        getSqlMapClientTemplate().insert("V_RP_DY_ISO_UTILITY.ibatorgenerated_insertSelective", record);
    }
    @SuppressWarnings("unchecked")
   	@Override
   	public List<VRpDyIsoUtility> getInfo(String startDate, String endDate, String neType) {
   		Map<String, Object> map = new HashMap<String, Object>();
       	map.put("P_START_DATE", startDate);
       	map.put("P_END_DATE", endDate); 
       	map.put("P_NE_TYPE", neType); 
   		map.put("P_DATA", null);
   		
   		return getSqlMapClientTemplate().queryForList("V_RP_DY_ISO_UTILITY.getInfo", map);
   	}
}