package dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.VRpDyVt2G;

public class VRpDyVt2GDAOImpl extends SqlMapClientDaoSupport implements VRpDyVt2GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_VT_2G
     *
     * @ibatorgenerated Thu Feb 07 03:36:24 ICT 2013
     */
    public VRpDyVt2GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_VT_2G
     *
     * @ibatorgenerated Thu Feb 07 03:36:24 ICT 2013
     */
    public void insert(VRpDyVt2G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_VT_2G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_VT_2G
     *
     * @ibatorgenerated Thu Feb 07 03:36:24 ICT 2013
     */
    public void insertSelective(VRpDyVt2G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_VT_2G.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpDyVt2G> getAll(String day){
    	Map<String, Object> map = new HashMap<String, Object>();
    	map.put("day", day);
    return getSqlMapClientTemplate().queryForList("V_RP_DY_VT_2G.filter", map);
    }
    @SuppressWarnings("unchecked")
    public List<VRpDyVt2G> filerOfHomePage(String tableName, String day, String region) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TABLE_NAME", 		tableName);
    	parms.put("P_DAY", 		day);
    	parms.put("P_REGION", 		region);
    	parms.put("P_DATA", 				null);
    	
		
		List<VRpDyVt2G> record = getSqlMapClientTemplate().queryForList("V_RP_DY_VT_2G.filerOfHomePage", parms);
        return record;
	}
}