package dao;

import java.util.List;

import vo.VRpDyVt2G;

public interface VRpDyVt2GDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_VT_2G
     *
     * @ibatorgenerated Thu Feb 07 03:36:24 ICT 2013
     */
    void insert(VRpDyVt2G record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_VT_2G
     *
     * @ibatorgenerated Thu Feb 07 03:36:24 ICT 2013
     */
    void insertSelective(VRpDyVt2G record);
    
    List<VRpDyVt2G> getAll(String day);
    List<VRpDyVt2G> filerOfHomePage(String tableName, String day, String region);
}