package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.CoreLog;
import vn.com.vhc.vmsc2.statistics.web.filter.TimeLog;

public class CoreLogDAOImpl extends SqlMapClientDaoSupport implements CoreLogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_CORE_LOGS
     *
     * @ibatorgenerated Wed Aug 25 00:57:48 ICT 2010
     */
    public CoreLogDAOImpl() {
        super();
    }

	@SuppressWarnings("unchecked")
	public List<CoreLog> filter(TimeLog filter) {
		return getSqlMapClientTemplate().queryForList("C_CORE_LOGS.filter", filter);
	}
	
	public Integer countRow(TimeLog filter) {
		return (Integer) getSqlMapClientTemplate().queryForObject("C_CORE_LOGS.countRow", filter);
	}
}