package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.dbadatafiles;

public class dbadatafilesDAOImpl extends SqlMapClientDaoSupport implements dbadatafilesDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DBA_DATA_FILES
     *
     * @ibatorgenerated Tue Nov 06 15:35:53 ICT 2012
     */
    public dbadatafilesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DBA_DATA_FILES
     *
     * @ibatorgenerated Tue Nov 06 15:35:53 ICT 2012
     */
    public void insert(dbadatafiles record) {
        getSqlMapClientTemplate().insert("DBA_DATA_FILES.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DBA_DATA_FILES
     *
     * @ibatorgenerated Tue Nov 06 15:35:53 ICT 2012
     */
    public void insertSelective(dbadatafiles record) {
        getSqlMapClientTemplate().insert("DBA_DATA_FILES.ibatorgenerated_insertSelective", record);
    }
    @SuppressWarnings("unchecked")
  	public List<dbadatafiles> getAll() {
      	return getSqlMapClientTemplate().queryForList("DBA_DATA_FILES.getAll");
  	}
    
    @SuppressWarnings("unchecked")
   	public List<dbadatafiles> filter(String tablespaceName) {
   		Map<String,String> map = new HashMap<String, String>();
   		map.put("tablespaceName", tablespaceName);
   		return getSqlMapClientTemplate().queryForList("DBA_DATA_FILES.filter", map);
   	}
}