package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyBadCellRegion;

public class DyBadCellRegionDAOImpl extends SqlMapClientDaoSupport implements DyBadCellRegionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_BAD_CELL_REGION
     *
     * @ibatorgenerated Wed Mar 16 16:48:07 ICT 2011
     */
    public DyBadCellRegionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_BAD_CELL_REGION
     *
     * @ibatorgenerated Wed Mar 16 16:48:07 ICT 2011
     */
    public void insert(DyBadCellRegion record) {
        getSqlMapClientTemplate().insert("V_DY_BAD_CELL_REGION.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_BAD_CELL_REGION
     *
     * @ibatorgenerated Wed Mar 16 16:48:07 ICT 2011
     */
    public void insertSelective(DyBadCellRegion record) {
        getSqlMapClientTemplate().insert("V_DY_BAD_CELL_REGION.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<DyBadCellRegion> filter(String region, String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("region", region);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_DY_BAD_CELL_REGION.filter", map);
	}
}