package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyBscCploadQos;

public class DyBscCploadQosDAOImpl extends SqlMapClientDaoSupport implements DyBscCploadQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_CPLOAD_QOS
     *
     * @ibatorgenerated Wed Feb 23 17:14:23 ICT 2011
     */
    public DyBscCploadQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_CPLOAD_QOS
     *
     * @ibatorgenerated Wed Feb 23 17:14:23 ICT 2011
     */
    public void insert(DyBscCploadQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC_CPLOAD_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_CPLOAD_QOS
     *
     * @ibatorgenerated Wed Feb 23 17:14:23 ICT 2011
     */
    public void insertSelective(DyBscCploadQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC_CPLOAD_QOS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<DyBscCploadQos> filter(String startDate,String endDate, String bscid, String region){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("bscid", bscid);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
		map.put("region", region);
    return getSqlMapClientTemplate().queryForList("V_RP_DY_BSC_CPLOAD_QOS.filter2", map);
    }
}