package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyBscHsrQos;

public class DyBscHsrQosDAOImpl extends SqlMapClientDaoSupport implements DyBscHsrQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public DyBscHsrQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public int deleteByPrimaryKey(String bscid, Date day) {
        DyBscHsrQos key = new DyBscHsrQos();
        key.setBscid(bscid);
        key.setDay(day);
        int rows = getSqlMapClientTemplate().delete("DY_BSC_HSR_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public void insert(DyBscHsrQos record) {
        getSqlMapClientTemplate().insert("DY_BSC_HSR_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public void insertSelective(DyBscHsrQos record) {
        getSqlMapClientTemplate().insert("DY_BSC_HSR_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public DyBscHsrQos selectByPrimaryKey(String bscid, Date day) {
        DyBscHsrQos key = new DyBscHsrQos();
        key.setBscid(bscid);
        key.setDay(day);
        DyBscHsrQos record = (DyBscHsrQos) getSqlMapClientTemplate().queryForObject("DY_BSC_HSR_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public int updateByPrimaryKeySelective(DyBscHsrQos record) {
        int rows = getSqlMapClientTemplate().update("DY_BSC_HSR_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 09:18:59 ICT 2010
     */
    public int updateByPrimaryKey(DyBscHsrQos record) {
        int rows = getSqlMapClientTemplate().update("DY_BSC_HSR_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}