package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyHBscPchQos;

public class DyHBscPchQosDAOImpl extends SqlMapClientDaoSupport implements DyHBscPchQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public DyHBscPchQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public int deleteByPrimaryKey(String bscid, Date day) {
        DyHBscPchQos key = new DyHBscPchQos();
        key.setBscid(bscid);
        key.setDay(day);
        int rows = getSqlMapClientTemplate().delete("DY_H_BSC_PCH_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public void insert(DyHBscPchQos record) {
        getSqlMapClientTemplate().insert("DY_H_BSC_PCH_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public void insertSelective(DyHBscPchQos record) {
        getSqlMapClientTemplate().insert("DY_H_BSC_PCH_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public DyHBscPchQos selectByPrimaryKey(String bscid, Date day) {
        DyHBscPchQos key = new DyHBscPchQos();
        key.setBscid(bscid);
        key.setDay(day);
        DyHBscPchQos record = (DyHBscPchQos) getSqlMapClientTemplate().queryForObject("DY_H_BSC_PCH_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public int updateByPrimaryKeySelective(DyHBscPchQos record) {
        int rows = getSqlMapClientTemplate().update("DY_H_BSC_PCH_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_H_BSC_PCH_QOS
     *
     * @ibatorgenerated Wed Nov 10 10:02:41 ICT 2010
     */
    public int updateByPrimaryKey(DyHBscPchQos record) {
        int rows = getSqlMapClientTemplate().update("DY_H_BSC_PCH_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}