package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyHlrAuthenQos;

public class DyHlrAuthenQosDAOImpl extends SqlMapClientDaoSupport implements DyHlrAuthenQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public DyHlrAuthenQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public int deleteByPrimaryKey(Date day, String hlrid) {
        DyHlrAuthenQos key = new DyHlrAuthenQos();
        key.setDay(day);
        key.setHlrid(hlrid);
        int rows = getSqlMapClientTemplate().delete("DY_HLR_AUTHEN_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public void insert(DyHlrAuthenQos record) {
        getSqlMapClientTemplate().insert("DY_HLR_AUTHEN_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public void insertSelective(DyHlrAuthenQos record) {
        getSqlMapClientTemplate().insert("DY_HLR_AUTHEN_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public DyHlrAuthenQos selectByPrimaryKey(Date day, String hlrid) {
        DyHlrAuthenQos key = new DyHlrAuthenQos();
        key.setDay(day);
        key.setHlrid(hlrid);
        DyHlrAuthenQos record = (DyHlrAuthenQos) getSqlMapClientTemplate().queryForObject("DY_HLR_AUTHEN_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public int updateByPrimaryKeySelective(DyHlrAuthenQos record) {
        int rows = getSqlMapClientTemplate().update("DY_HLR_AUTHEN_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_HLR_AUTHEN_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:20:48 ICT 2010
     */
    public int updateByPrimaryKey(DyHlrAuthenQos record) {
        int rows = getSqlMapClientTemplate().update("DY_HLR_AUTHEN_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}