package vn.com.vhc.vmsc2.statistics.dao;

import java.sql.Date;
import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.DyMsccpload;

public interface DyMsccploadDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    int deleteByPrimaryKey(Date day, String mscid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    void insert(DyMsccpload record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    void insertSelective(DyMsccpload record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    DyMsccpload selectByPrimaryKey(Date day, String mscid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    int updateByPrimaryKeySelective(DyMsccpload record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_CP_LOAD
     *
     * @ibatorgenerated Mon Oct 08 11:19:42 ICT 2012
     */
    int updateByPrimaryKey(DyMsccpload record);
   
    List<DyMsccpload> filter( String mscid,String startDate, String endDate);
    
    List<DyMsccpload> filterDay(String startDate, String endDate);
}