package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyMscMgw;

public class DyMscMgwDAOImpl extends SqlMapClientDaoSupport implements DyMscMgwDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public DyMscMgwDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public int deleteByPrimaryKey(Date day, String mscid) {
        DyMscMgw key = new DyMscMgw();
        key.setDay(day);
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("DY_MSC_MGW.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public void insert(DyMscMgw record) {
        getSqlMapClientTemplate().insert("DY_MSC_MGW.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public void insertSelective(DyMscMgw record) {
        getSqlMapClientTemplate().insert("DY_MSC_MGW.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public DyMscMgw selectByPrimaryKey(Date day, String mscid) {
        DyMscMgw key = new DyMscMgw();
        key.setDay(day);
        key.setMscid(mscid);
        DyMscMgw record = (DyMscMgw) getSqlMapClientTemplate().queryForObject("DY_MSC_MGW.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public int updateByPrimaryKeySelective(DyMscMgw record) {
        int rows = getSqlMapClientTemplate().update("DY_MSC_MGW.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW
     *
     * @ibatorgenerated Mon Oct 15 17:19:09 ICT 2012
     */
    public int updateByPrimaryKey(DyMscMgw record) {
        int rows = getSqlMapClientTemplate().update("DY_MSC_MGW.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    @SuppressWarnings("unchecked")
    public List<DyMscMgw> filter(String mscid,String startDate,String endDate){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("mscid", mscid);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    return getSqlMapClientTemplate().queryForList("DY_MSC_MGW.filter", map);
    }
}