package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyMscMgwTendamfrOper;

public class DyMscMgwTendamfrOperDAOImpl extends SqlMapClientDaoSupport implements DyMscMgwTendamfrOperDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public DyMscMgwTendamfrOperDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public int deleteByPrimaryKey(Date day, String mscid) {
        DyMscMgwTendamfrOper key = new DyMscMgwTendamfrOper();
        key.setDay(day);
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public void insert(DyMscMgwTendamfrOper record) {
        getSqlMapClientTemplate().insert("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public void insertSelective(DyMscMgwTendamfrOper record) {
        getSqlMapClientTemplate().insert("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public DyMscMgwTendamfrOper selectByPrimaryKey(Date day, String mscid) {
        DyMscMgwTendamfrOper key = new DyMscMgwTendamfrOper();
        key.setDay(day);
        key.setMscid(mscid);
        DyMscMgwTendamfrOper record = (DyMscMgwTendamfrOper) getSqlMapClientTemplate().queryForObject("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public int updateByPrimaryKeySelective(DyMscMgwTendamfrOper record) {
        int rows = getSqlMapClientTemplate().update("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    public int updateByPrimaryKey(DyMscMgwTendamfrOper record) {
        int rows = getSqlMapClientTemplate().update("DY_MSC_MGW_TENDAM_FR_OPER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
    public List<DyMscMgwTendamfrOper> filter(String mscid,String startDate,String endDate){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("mscid", mscid);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    return getSqlMapClientTemplate().queryForList("DY_MSC_MGW_TENDAM_FR_OPER.filter", map);
    }
}