package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.DyMscMgwTendamfrOper;

public interface DyMscMgwTendamfrOperDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    int deleteByPrimaryKey(Date day, String mscid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    void insert(DyMscMgwTendamfrOper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    void insertSelective(DyMscMgwTendamfrOper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    DyMscMgwTendamfrOper selectByPrimaryKey(Date day, String mscid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    int updateByPrimaryKeySelective(DyMscMgwTendamfrOper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MSC_MGW_TENDAM_FR_OPER
     *
     * @ibatorgenerated Mon Nov 05 16:07:06 ICT 2012
     */
    int updateByPrimaryKey(DyMscMgwTendamfrOper record);
    
    List<DyMscMgwTendamfrOper> filter(String mscid,String startDate, String endDate);
}