package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.DyMtclBranch;

public class DyMtclBranchDAOImpl extends SqlMapClientDaoSupport implements DyMtclBranchDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public DyMtclBranchDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public int deleteByPrimaryKey(String branch, Date day) {
        DyMtclBranch key = new DyMtclBranch();
        key.setBranch(branch);
        key.setDay(day);
        int rows = getSqlMapClientTemplate().delete("DY_MTCL_BRANCH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public void insert(DyMtclBranch record) {
        getSqlMapClientTemplate().insert("DY_MTCL_BRANCH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public void insertSelective(DyMtclBranch record) {
        getSqlMapClientTemplate().insert("DY_MTCL_BRANCH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public DyMtclBranch selectByPrimaryKey(String branch, Date day) {
        DyMtclBranch key = new DyMtclBranch();
        key.setBranch(branch);
        key.setDay(day);
        DyMtclBranch record = (DyMtclBranch) getSqlMapClientTemplate().queryForObject("DY_MTCL_BRANCH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public int updateByPrimaryKeySelective(DyMtclBranch record) {
        int rows = getSqlMapClientTemplate().update("DY_MTCL_BRANCH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:53:01 ICT 2018
     */
    public int updateByPrimaryKey(DyMtclBranch record) {
        int rows = getSqlMapClientTemplate().update("DY_MTCL_BRANCH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}