package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyProvinceDcrtQos;

public class DyProvinceDcrtQosDAOImpl extends SqlMapClientDaoSupport implements DyProvinceDcrtQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:05:53 ICT 2011
     */
    public DyProvinceDcrtQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:05:53 ICT 2011
     */
    public void insert(DyProvinceDcrtQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_PROVINCE_DCRT_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:05:53 ICT 2011
     */
    public void insertSelective(DyProvinceDcrtQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_PROVINCE_DCRT_QOS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<DyProvinceDcrtQos> filter(String startDate,String endDate, String province, String region){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("province", province);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
		map.put("region", region);
    return getSqlMapClientTemplate().queryForList("V_RP_DY_PROVINCE_DCRT_QOS.filter2", map);
    }
}