package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyRouteCoreBhReport;

public class DyRouteCoreBhReportDAOImpl extends SqlMapClientDaoSupport implements DyRouteCoreBhReportDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public DyRouteCoreBhReportDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public int deleteByPrimaryKey(Date day, String fromNode, String toNode) {
        DyRouteCoreBhReport key = new DyRouteCoreBhReport();
        key.setDay(day);
        key.setFromNode(fromNode);
        key.setToNode(toNode);
        int rows = getSqlMapClientTemplate().delete("DY_ROUTE_CORE_BH_RP.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public void insert(DyRouteCoreBhReport record) {
        getSqlMapClientTemplate().insert("DY_ROUTE_CORE_BH_RP.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public void insertSelective(DyRouteCoreBhReport record) {
        getSqlMapClientTemplate().insert("DY_ROUTE_CORE_BH_RP.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public DyRouteCoreBhReport selectByPrimaryKey(Date day, String fromNode, String toNode) {
        DyRouteCoreBhReport key = new DyRouteCoreBhReport();
        key.setDay(day);
        key.setFromNode(fromNode);
        key.setToNode(toNode);
        DyRouteCoreBhReport record = (DyRouteCoreBhReport) getSqlMapClientTemplate().queryForObject("DY_ROUTE_CORE_BH_RP.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public int updateByPrimaryKeySelective(DyRouteCoreBhReport record) {
        int rows = getSqlMapClientTemplate().update("DY_ROUTE_CORE_BH_RP.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_ROUTE_CORE_BH_RP
     *
     * @ibatorgenerated Tue Nov 15 09:20:26 ICT 2011
     */
    public int updateByPrimaryKey(DyRouteCoreBhReport record) {
        int rows = getSqlMapClientTemplate().update("DY_ROUTE_CORE_BH_RP.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

	@SuppressWarnings("unchecked")
	public List<DyRouteCoreBhReport> filter(String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    	return getSqlMapClientTemplate().queryForList("DY_ROUTE_CORE_BH_RP.filter2", map);
	}

	@SuppressWarnings("unchecked")
	public List<DyRouteCoreBhReport> filter(String startDate, String endDate, String routeid) {
		Map<String, String> map = new HashMap<String, String>();
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    	map.put("routeid", routeid);
    	return getSqlMapClientTemplate().queryForList("DY_ROUTE_CORE_BH_RP.filter3", map);
	}

	@SuppressWarnings("unchecked")
	public List<DyRouteCoreBhReport> filterRoute(String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    	return getSqlMapClientTemplate().queryForList("DY_ROUTE_CORE_BH_RP.filter4", map);
	}
}