package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyRouteCoreReport;

public class DyRouteCoreReportDAOImpl extends SqlMapClientDaoSupport implements DyRouteCoreReportDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public DyRouteCoreReportDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public int deleteByPrimaryKey(Date day, String fromNode, String toNode) {
		DyRouteCoreReport key = new DyRouteCoreReport();
		key.setDay(day);
		key.setFromNode(fromNode);
		key.setToNode(toNode);
		int rows = getSqlMapClientTemplate().delete("DY_ROUTE_CORE_RP.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public void insert(DyRouteCoreReport record) {
		getSqlMapClientTemplate().insert("DY_ROUTE_CORE_RP.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public void insertSelective(DyRouteCoreReport record) {
		getSqlMapClientTemplate().insert("DY_ROUTE_CORE_RP.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public DyRouteCoreReport selectByPrimaryKey(Date day, String fromNode, String toNode) {
		DyRouteCoreReport key = new DyRouteCoreReport();
		key.setDay(day);
		key.setFromNode(fromNode);
		key.setToNode(toNode);
		DyRouteCoreReport record = (DyRouteCoreReport) getSqlMapClientTemplate().queryForObject("DY_ROUTE_CORE_RP.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public int updateByPrimaryKeySelective(DyRouteCoreReport record) {
		int rows = getSqlMapClientTemplate().update("DY_ROUTE_CORE_RP.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DY_ROUTE_CORE_RP
	 * 
	 * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
	 */
	public int updateByPrimaryKey(DyRouteCoreReport record) {
		int rows = getSqlMapClientTemplate().update("DY_ROUTE_CORE_RP.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
	public List<DyRouteCoreReport> filter(String fromNode, String toNode, String day) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("fromNode", fromNode);
		map.put("toNode", toNode);
		map.put("day", day);

		return getSqlMapClientTemplate().queryForList("DY_ROUTE_CORE_RP.filter", map);
	}
}