package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.DyStpM3dataQos;

public class DyStpM3dataQosDAOImpl extends SqlMapClientDaoSupport implements DyStpM3dataQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public DyStpM3dataQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public int deleteByPrimaryKey(Date day, String stpid) {
        DyStpM3dataQos key = new DyStpM3dataQos();
        key.setDay(day);
        key.setStpid(stpid);
        int rows = getSqlMapClientTemplate().delete("DY_STP_M3DATA_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public void insert(DyStpM3dataQos record) {
        getSqlMapClientTemplate().insert("DY_STP_M3DATA_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public void insertSelective(DyStpM3dataQos record) {
        getSqlMapClientTemplate().insert("DY_STP_M3DATA_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public DyStpM3dataQos selectByPrimaryKey(Date day, String stpid) {
        DyStpM3dataQos key = new DyStpM3dataQos();
        key.setDay(day);
        key.setStpid(stpid);
        DyStpM3dataQos record = (DyStpM3dataQos) getSqlMapClientTemplate().queryForObject("DY_STP_M3DATA_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public int updateByPrimaryKeySelective(DyStpM3dataQos record) {
        int rows = getSqlMapClientTemplate().update("DY_STP_M3DATA_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DY_STP_M3DATA_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:46:17 ICT 2010
     */
    public int updateByPrimaryKey(DyStpM3dataQos record) {
        int rows = getSqlMapClientTemplate().update("DY_STP_M3DATA_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}