package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.FilePattern;

public class FilePatternDAOImpl extends SqlMapClientDaoSupport implements FilePatternDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public FilePatternDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public int deleteByPrimaryKey(Integer patternId) {
        FilePattern key = new FilePattern();
        key.setPatternId(patternId);
        int rows = getSqlMapClientTemplate().delete("C_FILE_PATTERNS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public void insert(FilePattern record) {
        getSqlMapClientTemplate().insert("C_FILE_PATTERNS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public void insertSelective(FilePattern record) {
        getSqlMapClientTemplate().insert("C_FILE_PATTERNS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public FilePattern selectByPrimaryKey(Integer patternId) {
        FilePattern key = new FilePattern();
        key.setPatternId(patternId);
        FilePattern record = (FilePattern) getSqlMapClientTemplate().queryForObject("C_FILE_PATTERNS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public int updateByPrimaryKeySelective(FilePattern record) {
        int rows = getSqlMapClientTemplate().update("C_FILE_PATTERNS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table C_FILE_PATTERNS
     *
     * @ibatorgenerated Wed Aug 25 00:33:14 ICT 2010
     */
    public int updateByPrimaryKey(FilePattern record) {
        int rows = getSqlMapClientTemplate().update("C_FILE_PATTERNS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<FilePattern> getAll() {
    	return getSqlMapClientTemplate().queryForList("C_FILE_PATTERNS.getAll");
    }
    
    
    @SuppressWarnings("unchecked")
	public List<FilePattern> filter(String filePattern, String nodeType, String convertClass, String rawTable, String status) {
    	Map<String, Object> map = new HashMap<String, Object>();
    	map.put("P_FILE_PATTERN", filePattern);
    	map.put("P_NODE_TYPE", nodeType);
    	map.put("P_CONVERT_CLASS", convertClass);
    	map.put("P_RAW_TABLE", rawTable);
    	map.put("P_STATUS", status);
		map.put("P_DATA", null);
		
		return getSqlMapClientTemplate().queryForList("C_FILE_PATTERNS.filter", map);
    }

	public FilePattern selectByFilePattern(String filePattern) {
        return (FilePattern) getSqlMapClientTemplate().queryForObject("C_FILE_PATTERNS.ibatorgenerated_selectByFilePattern", filePattern);
	}
}