package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HIpbbBwlist;
import vn.com.vhc.vmsc2.statistics.domain.HIpbbGraphTemplateGraph;

public class HIpbbGraphTemplateGraphDAOImpl extends SqlMapClientDaoSupport implements HIpbbGraphTemplateGraphDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public HIpbbGraphTemplateGraphDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public int deleteByPrimaryKey(Integer id) {
        HIpbbGraphTemplateGraph key = new HIpbbGraphTemplateGraph();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public void insert(HIpbbGraphTemplateGraph record) {
        getSqlMapClientTemplate().insert("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public void insertSelective(HIpbbGraphTemplateGraph record) {
        getSqlMapClientTemplate().insert("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public HIpbbGraphTemplateGraph selectByPrimaryKey(Integer id) {
        HIpbbGraphTemplateGraph key = new HIpbbGraphTemplateGraph();
        key.setId(id);
        HIpbbGraphTemplateGraph record = (HIpbbGraphTemplateGraph) getSqlMapClientTemplate().queryForObject("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public int updateByPrimaryKeySelective(HIpbbGraphTemplateGraph record) {
        int rows = getSqlMapClientTemplate().update("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_GRAPH_TEMPLATE_GRAPH
     *
     * @ibatorgenerated Wed Jan 08 15:27:30 ICT 2014
     */
    public int updateByPrimaryKey(HIpbbGraphTemplateGraph record) {
        int rows = getSqlMapClientTemplate().update("H_IPBB_GRAPH_TEMPLATE_GRAPH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<HIpbbGraphTemplateGraph> getData(String title, String link, String column, int order){
    	Map<String, Object> map = new HashMap<String, Object>();
    	map.put("p_title", title);
    	map.put("p_link", link);
    	map.put("p_column", column);
    	map.put("p_order", order);
    	
		map.put("P_DATA", null); 
		return getSqlMapClientTemplate().queryForList("H_IPBB_GRAPH_TEMPLATE_GRAPH.getData", map);
    }
    
    @SuppressWarnings("unchecked")
	public List<HIpbbBwlist> getLinkId(String link){
    	Map<String, Object> map = new HashMap<String, Object>();
    	map.put("p_link", link); 
    	
		map.put("P_DATA", null); 
		return getSqlMapClientTemplate().queryForList("H_IPBB_GRAPH_TEMPLATE_GRAPH.getLink", map);
    }
}