package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HIpbbBwlist;
import vn.com.vhc.vmsc2.statistics.web.filter.HIpbbBwlistFilter;

public class HIpbbBwlistDAOImpl extends SqlMapClientDaoSupport implements HIpbbBwlistDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public HIpbbBwlistDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        HIpbbBwlist key = new HIpbbBwlist();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("H_IPBB_BWLIST.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public void insert(HIpbbBwlist record) {
        getSqlMapClientTemplate().insert("H_IPBB_BWLIST.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public void insertSelective(HIpbbBwlist record) {
        getSqlMapClientTemplate().insert("H_IPBB_BWLIST.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public HIpbbBwlist selectByPrimaryKey(Integer id) {
        HIpbbBwlist key = new HIpbbBwlist();
        key.setId(id);
        HIpbbBwlist record = (HIpbbBwlist) getSqlMapClientTemplate().queryForObject("H_IPBB_BWLIST.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public int updateByPrimaryKeySelective(HIpbbBwlist record) {
        int rows = getSqlMapClientTemplate().update("H_IPBB_BWLIST.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_IPBB_BWLIST
     *
     * @ibatorgenerated Thu Dec 27 20:57:14 ICT 2012
     */
    public int updateByPrimaryKey(HIpbbBwlist record) {
        int rows = getSqlMapClientTemplate().update("H_IPBB_BWLIST.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
   	public List<HIpbbBwlist> getAll() {
   		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getAll");
   	}
    
    @SuppressWarnings("unchecked")
	public List<HIpbbBwlist> filter(HIpbbBwlistFilter filter) {
		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.filter", filter);
	}
    
    public HIpbbBwlist filterBykey(HIpbbBwlistFilter filter) {
        return (HIpbbBwlist) getSqlMapClientTemplate().queryForObject("H_IPBB_BWLIST.filterBykey", filter);
	}
    
    @SuppressWarnings("unchecked")
	public List<HIpbbBwlist> getAllDirection() {
		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getAllDirection");
	}
    
    @SuppressWarnings("unchecked")
	public List<HIpbbBwlist> getAllLink() {
		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getAllLink");
	}
    @SuppressWarnings("unchecked")
  	public List<HIpbbBwlist> getDirectInternet() {
  		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getDirectInternet");
  	}
      
      @SuppressWarnings("unchecked")
  	public List<HIpbbBwlist> getLinkInternet() {
  		return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getLinkInternet");
  	}
	  @SuppressWarnings("unchecked")
	  public List<HIpbbBwlist> getDirectInternet(String direction, String link){
	  	Map<String, Object> map = new HashMap<String, Object>();
	  	map.put("direction", direction); 
	  	map.put("link", link); 
	  return getSqlMapClientTemplate().queryForList("H_IPBB_BWLIST.getDirectionByLink", map);
	  }  
}