package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HrHlrRegisterQos;

public class HrHlrRegisterQosDAOImpl extends SqlMapClientDaoSupport implements HrHlrRegisterQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public HrHlrRegisterQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public int deleteByPrimaryKey(Date day, String hlrid, Integer hour) {
        HrHlrRegisterQos key = new HrHlrRegisterQos();
        key.setDay(day);
        key.setHlrid(hlrid);
        key.setHour(hour);
        int rows = getSqlMapClientTemplate().delete("HR_HLR_REGISTER_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public void insert(HrHlrRegisterQos record) {
        getSqlMapClientTemplate().insert("HR_HLR_REGISTER_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public void insertSelective(HrHlrRegisterQos record) {
        getSqlMapClientTemplate().insert("HR_HLR_REGISTER_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public HrHlrRegisterQos selectByPrimaryKey(Date day, String hlrid, Integer hour) {
        HrHlrRegisterQos key = new HrHlrRegisterQos();
        key.setDay(day);
        key.setHlrid(hlrid);
        key.setHour(hour);
        HrHlrRegisterQos record = (HrHlrRegisterQos) getSqlMapClientTemplate().queryForObject("HR_HLR_REGISTER_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public int updateByPrimaryKeySelective(HrHlrRegisterQos record) {
        int rows = getSqlMapClientTemplate().update("HR_HLR_REGISTER_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_REGISTER_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:21:32 ICT 2010
     */
    public int updateByPrimaryKey(HrHlrRegisterQos record) {
        int rows = getSqlMapClientTemplate().update("HR_HLR_REGISTER_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}