package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;

import vn.com.vhc.vmsc2.statistics.domain.HrHlrMapQos;

public interface HrHlrMapQosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    int deleteByPrimaryKey(Date day, String hlrid, Integer hour);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    void insert(HrHlrMapQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    void insertSelective(HrHlrMapQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    HrHlrMapQos selectByPrimaryKey(Date day, String hlrid, Integer hour);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    int updateByPrimaryKeySelective(HrHlrMapQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_HLR_MAP_QOS
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    int updateByPrimaryKey(HrHlrMapQos record);
}