package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.HrMscPaging;

public class HrMscPagingDAOImpl extends SqlMapClientDaoSupport implements HrMscPagingDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:19 ICT 2012
     */
    public HrMscPagingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public int deleteByPrimaryKey(Date day, Integer hour, String mscid) {
        HrMscPaging key = new HrMscPaging();
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("HR_MSC_PAGING.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public void insert(HrMscPaging record) {
        getSqlMapClientTemplate().insert("HR_MSC_PAGING.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public void insertSelective(HrMscPaging record) {
        getSqlMapClientTemplate().insert("HR_MSC_PAGING.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public HrMscPaging selectByPrimaryKey(Date day, Integer hour, String mscid) {
        HrMscPaging key = new HrMscPaging();
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        HrMscPaging record = (HrMscPaging) getSqlMapClientTemplate().queryForObject("HR_MSC_PAGING.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public int updateByPrimaryKeySelective(HrMscPaging record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_PAGING.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING
     *
     * @ibatorgenerated Sat Oct 13 10:29:20 ICT 2012
     */
    public int updateByPrimaryKey(HrMscPaging record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_PAGING.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
   	public List<HrMscPaging> filter(String startHour, Date startDate, String endHour,Date endDate, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate",startDate);
   		map.put("endDate",endDate);
   		map.put("mscid", mscid);
       	return getSqlMapClientTemplate().queryForList("HR_MSC_PAGING.filter", map);
   	}
       @SuppressWarnings("unchecked")
       public List<HrMscPaging> filter2(String startHour, Date startDate, String endHour, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate", startDate);
   		map.put("mscid", mscid);
   		return getSqlMapClientTemplate().queryForList("HR_MSC_PAGING.filter2", map);
      	}
}