package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HrMscPagingbc;

public class HrMscPagingbcDAOImpl extends SqlMapClientDaoSupport implements HrMscPagingbcDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public HrMscPagingbcDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public int deleteByPrimaryKey(String bc, Date day, Integer hour, String mscid) {
        HrMscPagingbc key = new HrMscPagingbc();
        key.setBc(bc);
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("HR_MSC_PAGING_BC.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public void insert(HrMscPagingbc record) {
        getSqlMapClientTemplate().insert("HR_MSC_PAGING_BC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public void insertSelective(HrMscPagingbc record) {
        getSqlMapClientTemplate().insert("HR_MSC_PAGING_BC.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public HrMscPagingbc selectByPrimaryKey(String bc, Date day, Integer hour, String mscid) {
        HrMscPagingbc key = new HrMscPagingbc();
        key.setBc(bc);
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        HrMscPagingbc record = (HrMscPagingbc) getSqlMapClientTemplate().queryForObject("HR_MSC_PAGING_BC.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public int updateByPrimaryKeySelective(HrMscPagingbc record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_PAGING_BC.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_PAGING_BC
     *
     * @ibatorgenerated Sat Oct 13 10:29:35 ICT 2012
     */
    public int updateByPrimaryKey(HrMscPagingbc record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_PAGING_BC.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
   	public List<HrMscPagingbc> filter(String startHour, Date startDate, String endHour,Date endDate, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate",startDate);
   		map.put("endDate",endDate);
   		map.put("mscid", mscid);
       	return getSqlMapClientTemplate().queryForList("HR_MSC_PAGING_BC.filter", map);
   	}
       @SuppressWarnings("unchecked")
       public List<HrMscPagingbc> filter2(String startHour, Date startDate, String endHour, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate", startDate);
   		map.put("mscid", mscid);
   		return getSqlMapClientTemplate().queryForList("HR_MSC_PAGING_BC.filter2", map);
      	}
}