package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.HrMscLoss;

public class HrMscLossDAOImpl extends SqlMapClientDaoSupport implements HrMscLossDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public HrMscLossDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public int deleteByPrimaryKey(Date day, Integer hour, String mscid) {
        HrMscLoss key = new HrMscLoss();
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("HR_MSC_LOSS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public void insert(HrMscLoss record) {
        getSqlMapClientTemplate().insert("HR_MSC_LOSS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public void insertSelective(HrMscLoss record) {
        getSqlMapClientTemplate().insert("HR_MSC_LOSS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public HrMscLoss selectByPrimaryKey(Date day, Integer hour, String mscid) {
        HrMscLoss key = new HrMscLoss();
        key.setDay(day);
        key.setHour(hour);
        key.setMscid(mscid);
        HrMscLoss record = (HrMscLoss) getSqlMapClientTemplate().queryForObject("HR_MSC_LOSS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public int updateByPrimaryKeySelective(HrMscLoss record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_LOSS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MSC_LOSS
     *
     * @ibatorgenerated Wed Oct 10 10:46:40 ICT 2012
     */
    public int updateByPrimaryKey(HrMscLoss record) {
        int rows = getSqlMapClientTemplate().update("HR_MSC_LOSS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
   	public List<HrMscLoss> filter(String startHour, Date startDate, String endHour,Date endDate, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate",startDate);
   		map.put("endDate",endDate);
   		map.put("mscid", mscid);
       	return getSqlMapClientTemplate().queryForList("HR_MSC_LOSS.filter", map);
   	}
       @SuppressWarnings("unchecked")
       public List<HrMscLoss> filter2(String startHour, Date startDate, String endHour, String mscid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate", startDate);
   		map.put("mscid", mscid);
   		return getSqlMapClientTemplate().queryForList("HR_MSC_LOSS.filter2", map);
      	}
}