package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.HrMtclBranch;

public class HrMtclBranchDAOImpl extends SqlMapClientDaoSupport implements HrMtclBranchDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public HrMtclBranchDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public int deleteByPrimaryKey(String branch, Date day, Integer hour) {
        HrMtclBranch key = new HrMtclBranch();
        key.setBranch(branch);
        key.setDay(day);
        key.setHour(hour);
        int rows = getSqlMapClientTemplate().delete("HR_MTCL_BRANCH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public void insert(HrMtclBranch record) {
        getSqlMapClientTemplate().insert("HR_MTCL_BRANCH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public void insertSelective(HrMtclBranch record) {
        getSqlMapClientTemplate().insert("HR_MTCL_BRANCH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public HrMtclBranch selectByPrimaryKey(String branch, Date day, Integer hour) {
        HrMtclBranch key = new HrMtclBranch();
        key.setBranch(branch);
        key.setDay(day);
        key.setHour(hour);
        HrMtclBranch record = (HrMtclBranch) getSqlMapClientTemplate().queryForObject("HR_MTCL_BRANCH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public int updateByPrimaryKeySelective(HrMtclBranch record) {
        int rows = getSqlMapClientTemplate().update("HR_MTCL_BRANCH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_BRANCH
     *
     * @ibatorgenerated Sat Jul 07 16:52:52 ICT 2018
     */
    public int updateByPrimaryKey(HrMtclBranch record) {
        int rows = getSqlMapClientTemplate().update("HR_MTCL_BRANCH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}