package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import vn.com.vhc.vmsc2.statistics.domain.HrMtclCtkd;

public interface HrMtclCtkdDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    int deleteByPrimaryKey(String ctkd, Date day, Integer hour);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    void insert(HrMtclCtkd record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    void insertSelective(HrMtclCtkd record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    HrMtclCtkd selectByPrimaryKey(String ctkd, Date day, Integer hour);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    int updateByPrimaryKeySelective(HrMtclCtkd record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_MTCL_CTKD
     *
     * @ibatorgenerated Sat Jul 07 16:52:36 ICT 2018
     */
    int updateByPrimaryKey(HrMtclCtkd record);
}