package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HrRegionQos;

public class HrRegionQosDAOImpl extends SqlMapClientDaoSupport implements HrRegionQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public HrRegionQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public int deleteByPrimaryKey(Date day, Integer hour, String region) {
        HrRegionQos key = new HrRegionQos();
        key.setDay(day);
        key.setHour(hour);
        key.setRegion(region);
        int rows = getSqlMapClientTemplate().delete("HR_REGION_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public void insert(HrRegionQos record) {
        getSqlMapClientTemplate().insert("HR_REGION_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public void insertSelective(HrRegionQos record) {
        getSqlMapClientTemplate().insert("HR_REGION_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public HrRegionQos selectByPrimaryKey(Date day, Integer hour, String region) {
        HrRegionQos key = new HrRegionQos();
        key.setDay(day);
        key.setHour(hour);
        key.setRegion(region);
        HrRegionQos record = (HrRegionQos) getSqlMapClientTemplate().queryForObject("HR_REGION_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public int updateByPrimaryKeySelective(HrRegionQos record) {
        int rows = getSqlMapClientTemplate().update("HR_REGION_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_REGION_QOS
     *
     * @ibatorgenerated Fri Nov 16 16:35:55 ICT 2012
     */
    public int updateByPrimaryKey(HrRegionQos record) {
        int rows = getSqlMapClientTemplate().update("HR_REGION_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
   	public List<HrRegionQos> filter(String startHour, Date startDate, String endHour,Date endDate, String region) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("startDate",startDate);
   		map.put("endHour", endHour);
   		map.put("endDate",endDate);
   		map.put("region", region);
       	return getSqlMapClientTemplate().queryForList("HR_REGION_QOS.filter", map);
   	}
       @SuppressWarnings("unchecked")
       public List<HrRegionQos> filter2(String startHour, Date startDate, String endHour, String region) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("startDate", startDate);
   		map.put("endHour", endHour);
   		map.put("region", region);
   		return getSqlMapClientTemplate().queryForList("HR_REGION_QOS.filter2", map);
      	}
}