package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.HrRouteCoreReport;

public class HrRouteCoreReportDAOImpl extends SqlMapClientDaoSupport implements HrRouteCoreReportDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public HrRouteCoreReportDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public int deleteByPrimaryKey(Date day, String fromNode, Integer hour, String toNode) {
        HrRouteCoreReport key = new HrRouteCoreReport();
        key.setDay(day);
        key.setFromNode(fromNode);
        key.setHour(hour);
        key.setToNode(toNode);
        int rows = getSqlMapClientTemplate().delete("HR_ROUTE_CORE_RP.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public void insert(HrRouteCoreReport record) {
        getSqlMapClientTemplate().insert("HR_ROUTE_CORE_RP.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public void insertSelective(HrRouteCoreReport record) {
        getSqlMapClientTemplate().insert("HR_ROUTE_CORE_RP.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public HrRouteCoreReport selectByPrimaryKey(Date day, String fromNode, Integer hour, String toNode) {
        HrRouteCoreReport key = new HrRouteCoreReport();
        key.setDay(day);
        key.setFromNode(fromNode);
        key.setHour(hour);
        key.setToNode(toNode);
        HrRouteCoreReport record = (HrRouteCoreReport) getSqlMapClientTemplate().queryForObject("HR_ROUTE_CORE_RP.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public int updateByPrimaryKeySelective(HrRouteCoreReport record) {
        int rows = getSqlMapClientTemplate().update("HR_ROUTE_CORE_RP.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_ROUTE_CORE_RP
     *
     * @ibatorgenerated Fri Oct 22 14:10:12 ICT 2010
     */
    public int updateByPrimaryKey(HrRouteCoreReport record) {
        int rows = getSqlMapClientTemplate().update("HR_ROUTE_CORE_RP.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    @SuppressWarnings("unchecked")
	public List<HrRouteCoreReport> filter(String fromNode, String toNode, String day, String hour) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("fromNode", fromNode);
		map.put("toNode", toNode);
		map.put("day", day);
		map.put("hour", hour);
		return getSqlMapClientTemplate().queryForList("HR_ROUTE_CORE_RP.filter", map);
	}
}