package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;

import vn.com.vhc.vmsc2.statistics.domain.HrStpAssonciationQos;

public interface HrStpAssonciationQosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    int deleteByPrimaryKey(Date day, Integer hour, String stpid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    void insert(HrStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    void insertSelective(HrStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    HrStpAssonciationQos selectByPrimaryKey(Date day, Integer hour, String stpid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    int updateByPrimaryKeySelective(HrStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:47:00 ICT 2010
     */
    int updateByPrimaryKey(HrStpAssonciationQos record);
}