package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.MDepartment;

public class MDepartmentDAOImpl extends SqlMapClientDaoSupport implements MDepartmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public MDepartmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public int deleteByPrimaryKey(String deptCode) {
        MDepartment key = new MDepartment();
        key.setDeptCode(deptCode);
        int rows = getSqlMapClientTemplate().delete("M_DEPARTMENT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public void insert(MDepartment record) {
        getSqlMapClientTemplate().insert("M_DEPARTMENT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public void insertSelective(MDepartment record) {
        getSqlMapClientTemplate().insert("M_DEPARTMENT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public MDepartment selectByPrimaryKey(String deptCode) {
        MDepartment key = new MDepartment();
        key.setDeptCode(deptCode);
        MDepartment record = (MDepartment) getSqlMapClientTemplate().queryForObject("M_DEPARTMENT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public int updateByPrimaryKeySelective(MDepartment record) {
        int rows = getSqlMapClientTemplate().update("M_DEPARTMENT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 24 09:14:16 PDT 2013
     */
    public int updateByPrimaryKey(MDepartment record) {
        int rows = getSqlMapClientTemplate().update("M_DEPARTMENT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
    public List<MDepartment> getMDepartmentForProvince(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("M_DEPARTMENT.getMDepartmentForProvince", parms);
    }
}