package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.MnBadCellDistrict;


public interface MnBadCellDistrictDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int deleteByPrimaryKey(String district, Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insert(MnBadCellDistrict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insertSelective(MnBadCellDistrict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    MnBadCellDistrict selectByPrimaryKey(String district, Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKeySelective(MnBadCellDistrict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_DISTRICT
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKey(MnBadCellDistrict record);

	List<MnBadCellDistrict> filter(String province, String district, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear);
}