package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.MnBadCellRegion3g;


public interface MnBadCellRegion3gDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int deleteByPrimaryKey(Integer month, String region, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insert(MnBadCellRegion3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insertSelective(MnBadCellRegion3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    MnBadCellRegion3g selectByPrimaryKey(Integer month, String region, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKeySelective(MnBadCellRegion3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BAD_CELL_REGION_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKey(MnBadCellRegion3g record);

	List<MnBadCellRegion3g> filter(String region, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear);
}