package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.MnBranch;

public class MnBranchDAOImpl extends SqlMapClientDaoSupport implements MnBranchDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public MnBranchDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public int deleteByPrimaryKey(String branch, Integer month, String region, Integer year) {
        MnBranch key = new MnBranch();
        key.setBranch(branch);
        key.setMonth(month);
        key.setRegion(region);
        key.setYear(year);
        int rows = getSqlMapClientTemplate().delete("MN_BRANCH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public void insert(MnBranch record) {
        getSqlMapClientTemplate().insert("MN_BRANCH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public void insertSelective(MnBranch record) {
        getSqlMapClientTemplate().insert("MN_BRANCH.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public MnBranch selectByPrimaryKey(String branch, Integer month, String region, Integer year) {
        MnBranch key = new MnBranch();
        key.setBranch(branch);
        key.setMonth(month);
        key.setRegion(region);
        key.setYear(year);
        MnBranch record = (MnBranch) getSqlMapClientTemplate().queryForObject("MN_BRANCH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public int updateByPrimaryKeySelective(MnBranch record) {
        int rows = getSqlMapClientTemplate().update("MN_BRANCH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BRANCH
     *
     * @ibatorgenerated Mon Feb 21 15:55:04 ICT 2011
     */
    public int updateByPrimaryKey(MnBranch record) {
        int rows = getSqlMapClientTemplate().update("MN_BRANCH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
    public List<MnBranch> filter(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String branch, String region){
		Map<String, String> map = new HashMap<String, String>();
		map.put("branch", branch);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("MN_BRANCH.filter2", map);
    }
}