package vn.com.vhc.vmsc2.statistics.dao;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.MnBscHsrQos;

public class MnBscHsrQosDAOImpl extends SqlMapClientDaoSupport implements MnBscHsrQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public MnBscHsrQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public int deleteByPrimaryKey(String bscid, Integer month, Integer year) {
        MnBscHsrQos key = new MnBscHsrQos();
        key.setBscid(bscid);
        key.setMonth(month);
        key.setYear(year);
        int rows = getSqlMapClientTemplate().delete("MN_BSC_HSR_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public void insert(MnBscHsrQos record) {
        getSqlMapClientTemplate().insert("MN_BSC_HSR_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public void insertSelective(MnBscHsrQos record) {
        getSqlMapClientTemplate().insert("MN_BSC_HSR_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public MnBscHsrQos selectByPrimaryKey(String bscid, Integer month, Integer year) {
        MnBscHsrQos key = new MnBscHsrQos();
        key.setBscid(bscid);
        key.setMonth(month);
        key.setYear(year);
        MnBscHsrQos record = (MnBscHsrQos) getSqlMapClientTemplate().queryForObject("MN_BSC_HSR_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public int updateByPrimaryKeySelective(MnBscHsrQos record) {
        int rows = getSqlMapClientTemplate().update("MN_BSC_HSR_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_BSC_HSR_QOS
     *
     * @ibatorgenerated Tue Oct 19 14:13:04 ICT 2010
     */
    public int updateByPrimaryKey(MnBscHsrQos record) {
        int rows = getSqlMapClientTemplate().update("MN_BSC_HSR_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}