package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.MnCellTrafficProvince;


public interface MnCellTrafficProvinceDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int deleteByPrimaryKey(Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insert(MnCellTrafficProvince record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insertSelective(MnCellTrafficProvince record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    MnCellTrafficProvince selectByPrimaryKey(Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKeySelective(MnCellTrafficProvince record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_PROVINCE
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKey(MnCellTrafficProvince record);

	List<MnCellTrafficProvince> filter(String province, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear);
}