package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.MnCellTrafficDistrict3g;


public interface MnCellTrafficDistrict3gDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int deleteByPrimaryKey(String district, Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insert(MnCellTrafficDistrict3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    void insertSelective(MnCellTrafficDistrict3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    MnCellTrafficDistrict3g selectByPrimaryKey(String district, Integer month, String province, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKeySelective(MnCellTrafficDistrict3g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TRAFFIC_DISTRICT_3G
     *
     * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
     */
    int updateByPrimaryKey(MnCellTrafficDistrict3g record);

	List<MnCellTrafficDistrict3g> filter(String province, String district, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear);
}