package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.MnCellToCellQos;

public class MnCellToCellQosDAOImpl extends SqlMapClientDaoSupport implements MnCellToCellQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public MnCellToCellQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public int deleteByPrimaryKey(String bscid, String fromCell, Integer month, String toCell, Integer year) {
        MnCellToCellQos key = new MnCellToCellQos();
        key.setBscid(bscid);
        key.setFromCell(fromCell);
        key.setMonth(month);
        key.setToCell(toCell);
        key.setYear(year);
        int rows = getSqlMapClientTemplate().delete("MN_CELL_TO_CELL_QOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public void insert(MnCellToCellQos record) {
        getSqlMapClientTemplate().insert("MN_CELL_TO_CELL_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public void insertSelective(MnCellToCellQos record) {
        getSqlMapClientTemplate().insert("MN_CELL_TO_CELL_QOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public MnCellToCellQos selectByPrimaryKey(String bscid, String fromCell, Integer month, String toCell, Integer year) {
        MnCellToCellQos key = new MnCellToCellQos();
        key.setBscid(bscid);
        key.setFromCell(fromCell);
        key.setMonth(month);
        key.setToCell(toCell);
        key.setYear(year);
        MnCellToCellQos record = (MnCellToCellQos) getSqlMapClientTemplate().queryForObject("MN_CELL_TO_CELL_QOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public int updateByPrimaryKeySelective(MnCellToCellQos record) {
        int rows = getSqlMapClientTemplate().update("MN_CELL_TO_CELL_QOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_CELL_TO_CELL_QOS
     *
     * @ibatorgenerated Tue Dec 07 13:58:45 ICT 2010
     */
    public int updateByPrimaryKey(MnCellToCellQos record) {
        int rows = getSqlMapClientTemplate().update("MN_CELL_TO_CELL_QOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

	@SuppressWarnings("unchecked")
	public List<MnCellToCellQos> filterCellToCells(String bscid, String fromCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, int startRecord, int endRecord, String column, String order) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", fromCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		map.put("startRecord", startRecord);
		map.put("endRecord", endRecord);
		map.put("column", column);
		map.put("order", order);
		
		return getSqlMapClientTemplate().queryForList("MN_CELL_TO_CELL_QOS.filterCellToCells", map);
	}
	
	@SuppressWarnings("unchecked")
	public List<MnCellToCellQos> filterCellToCells(String bscid, String fromCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", fromCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		
		return getSqlMapClientTemplate().queryForList("MN_CELL_TO_CELL_QOS.filterCellToCells3", map);
	}

	@SuppressWarnings("unchecked")
	public List<MnCellToCellQos> filterCellsToCell(String bscid, String toCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, int startRecord, int endRecord, String column, String order) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", toCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		map.put("startRecord", startRecord);
		map.put("endRecord", endRecord);
		map.put("column", column);
		map.put("order", order);
		
		return getSqlMapClientTemplate().queryForList("MN_CELL_TO_CELL_QOS.filterCellsToCell", map);
	}
	
	@SuppressWarnings("unchecked")
	public List<MnCellToCellQos> filterCellsToCell(String bscid, String toCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", toCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		
		return getSqlMapClientTemplate().queryForList("MN_CELL_TO_CELL_QOS.filterCellsToCell3", map);
	}

	public Integer countFromCell(String bscid, String fromCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", fromCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		
		return (Integer) getSqlMapClientTemplate().queryForObject("MN_CELL_TO_CELL_QOS.countFromCell", map);
	}

	public Integer countToCell(String bscid, String toCell, Integer startMonth, Integer startYear, Integer endMonth, Integer endYear) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", toCell);
		map.put("startMonth", startMonth.toString());
		map.put("startYear", startYear.toString());
		map.put("endMonth", endMonth.toString());
		map.put("endYear",  endYear.toString());
		
		return (Integer) getSqlMapClientTemplate().queryForObject("MN_CELL_TO_CELL_QOS.countToCell", map);
	}
}