package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.MnLinkset;

public class MnLinksetDAOImpl extends SqlMapClientDaoSupport implements MnLinksetDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public MnLinksetDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public int deleteByPrimaryKey(String fromNode, String linksetid, Integer month, String toNode, Integer year) {
        MnLinkset key = new MnLinkset();
        key.setFromNode(fromNode);
        key.setLinksetid(linksetid);
        key.setMonth(month);
        key.setToNode(toNode);
        key.setYear(year);
        int rows = getSqlMapClientTemplate().delete("MN_S7LINKSET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public void insert(MnLinkset record) {
        getSqlMapClientTemplate().insert("MN_S7LINKSET.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public void insertSelective(MnLinkset record) {
        getSqlMapClientTemplate().insert("MN_S7LINKSET.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public MnLinkset selectByPrimaryKey(String fromNode, String linksetid, Integer month, String toNode, Integer year) {
        MnLinkset key = new MnLinkset();
        key.setFromNode(fromNode);
        key.setLinksetid(linksetid);
        key.setMonth(month);
        key.setToNode(toNode);
        key.setYear(year);
        MnLinkset record = (MnLinkset) getSqlMapClientTemplate().queryForObject("MN_S7LINKSET.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public int updateByPrimaryKeySelective(MnLinkset record) {
        int rows = getSqlMapClientTemplate().update("MN_S7LINKSET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_S7LINKSET
     *
     * @ibatorgenerated Fri Oct 22 10:29:11 ICT 2010
     */
    public int updateByPrimaryKey(MnLinkset record) {
        int rows = getSqlMapClientTemplate().update("MN_S7LINKSET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<MnLinkset> filter(Integer month,Integer year, String fromNode, String toNode){
    	 MnLinkset key = new MnLinkset();
    	 key.setMonth(month);
         key.setYear(year);
         key.setFromNode(fromNode);
         key.setToNode(toNode);
    	return getSqlMapClientTemplate().queryForList("MN_S7LINKSET.filter", key);
    }
}