package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.MnRegionQos;

public interface MnRegionQosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    int deleteByPrimaryKey(Integer month, String region, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    void insert(MnRegionQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    void insertSelective(MnRegionQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    MnRegionQos selectByPrimaryKey(Integer month, String region, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    int updateByPrimaryKeySelective(MnRegionQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MN_REGION_QOS
     *
     * @ibatorgenerated Mon Nov 19 09:42:28 ICT 2012
     */
    int updateByPrimaryKey(MnRegionQos record);
    
    List<MnRegionQos> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, String region);
}