package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.MonitorKpi3gMail;

public class MonitorKpi3gMailDAOImpl extends SqlMapClientDaoSupport implements MonitorKpi3gMailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MONITOR_KPI_3G_MAIL
     *
     * @ibatorgenerated Fri May 11 15:57:06 ICT 2018
     */
    public MonitorKpi3gMailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MONITOR_KPI_3G_MAIL
     *
     * @ibatorgenerated Fri May 11 15:57:06 ICT 2018
     */
    public void insert(MonitorKpi3gMail record) {
        getSqlMapClientTemplate().insert("MONITOR_KPI_3G_MAIL.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MONITOR_KPI_3G_MAIL
     *
     * @ibatorgenerated Fri May 11 15:57:06 ICT 2018
     */
    public void insertSelective(MonitorKpi3gMail record) {
        getSqlMapClientTemplate().insert("MONITOR_KPI_3G_MAIL.ibatorgenerated_insertSelective", record);
    }

    @SuppressWarnings("unchecked")
	public List<MonitorKpi3gMail> getDataList(String startDate, String endDate) {
		// TODO Auto-generated method stub
    	Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_START_DATE", startDate);
		map.put("P_END_DATE", endDate);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("MONITOR_KPI_3G_MAIL.getGiamSat3gKpiMail", map);
	}
}