package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vn.com.vhc.vmsc2.statistics.domain.Msc;
import vn.com.vhc.vmsc2.statistics.web.filter.MscFilter;

public class MscDAOImpl extends SqlMapClientDaoSupport implements MscDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public MscDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public int deleteByPrimaryKey(String mscid) {
        Msc key = new Msc();
        key.setMscid(mscid);
        int rows = getSqlMapClientTemplate().delete("H_MSC.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public void insert(Msc record) {
        getSqlMapClientTemplate().insert("H_MSC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public void insertSelective(Msc record) {
        getSqlMapClientTemplate().insert("H_MSC.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public Msc selectByPrimaryKey(String mscid) {
        Msc key = new Msc();
        key.setMscid(mscid);
        Msc record = (Msc) getSqlMapClientTemplate().queryForObject("H_MSC.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public int updateByPrimaryKeySelective(Msc record) {
        int rows = getSqlMapClientTemplate().update("H_MSC.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_MSC
     *
     * @ibatorgenerated Thu Jan 23 16:25:06 ICT 2014
     */
    public int updateByPrimaryKey(Msc record) {
        int rows = getSqlMapClientTemplate().update("H_MSC.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<Msc> filter(MscFilter filter) {
		return getSqlMapClientTemplate().queryForList("H_MSC.filter", filter);
	}

	@SuppressWarnings("unchecked")
	public List<Msc> getAll() {
		return getSqlMapClientTemplate().queryForList("H_MSC.getAll");
	}

	@SuppressWarnings("unchecked")
	public List<String> getMscids(String term) {
		return getSqlMapClientTemplate().queryForList("H_MSC.getMsc", term);
	}
	
	public int deleteById(Integer id) {
        Msc key = new Msc();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("H_MSC.ibatorgenerated_deleteById", key);
        return rows;
    }
	
	public Msc selectById(Integer id) {
        Msc key = new Msc();
        key.setId(id);
        Msc record = (Msc) getSqlMapClientTemplate().queryForObject("H_MSC.ibatorgenerated_selectById", key);
        return record;
    }
	
    @SuppressWarnings("unchecked")
	public List<Msc> checkUniqueMsc(String mscid, String id) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MSCID", mscid);
		parms.put("P_ID", id);
		parms.put("P_DATA", null);
		
		return getSqlMapClientTemplate().queryForList("H_MSC.checkUniqueMsc", parms);
	}
    
    public int updateById(Msc record) {
        int rows = getSqlMapClientTemplate().update("H_MSC.ibatorgenerated_updateById", record);
        return rows;
    }
}