package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.ReIpbbBwlist;

public interface ReIpbbBwlistDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    int deleteByPrimaryKey(String direction, String link);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    void insert(ReIpbbBwlist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    void insertSelective(ReIpbbBwlist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    ReIpbbBwlist selectByPrimaryKey(String direction, String link);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    int updateByPrimaryKeySelective(ReIpbbBwlist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_E_IPBB_BWLIST
     *
     * @ibatorgenerated Sat Nov 24 09:35:40 ICT 2012
     */
    int updateByPrimaryKey(ReIpbbBwlist record);
    
    List<ReIpbbBwlist> getAllDirection();
    List<ReIpbbBwlist> getAllLink();
    List<ReIpbbBwlist> getDirectInternet();
    List<ReIpbbBwlist> getLinkInternet();
    
}