package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.Stp;
import vn.com.vhc.vmsc2.statistics.web.filter.StpFilter;

public interface StpDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    int deleteByPrimaryKey(String stpid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    void insert(Stp record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    void insertSelective(Stp record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    Stp selectByPrimaryKey(String stpid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    int updateByPrimaryKeySelective(Stp record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table H_STP
     *
     * @ibatorgenerated Wed Oct 13 14:24:12 ICT 2010
     */
    int updateByPrimaryKey(Stp record);

	List<Stp> filter(StpFilter filter);

	List<String> getStpids(String term);
	
	List<Stp> getStpList();
	List<Stp> getSliList();
}