package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.SummaryLog3g;
import vn.com.vhc.vmsc2.statistics.web.filter.SummaryLogFilter;

public class SummaryLog3gDAOImpl extends SqlMapClientDaoSupport implements SummaryLog3gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table S_SUMMARY_LOGS_3G
     *
     * @ibatorgenerated Thu Sep 13 09:59:29 ICT 2012
     */
    public SummaryLog3gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table S_SUMMARY_LOGS_3G
     *
     * @ibatorgenerated Thu Sep 13 09:59:29 ICT 2012
     */
    public void insert(SummaryLog3g record) {
        getSqlMapClientTemplate().insert("S_SUMMARY_LOGS_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table S_SUMMARY_LOGS_3G
     *
     * @ibatorgenerated Thu Sep 13 09:59:29 ICT 2012
     */
    public void insertSelective(SummaryLog3g record) {
        getSqlMapClientTemplate().insert("S_SUMMARY_LOGS_3G.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
	public List<SummaryLog3g> filter(SummaryLogFilter filter) {
		return getSqlMapClientTemplate().queryForList("S_SUMMARY_LOGS_3G.filter", filter);
	}

	public Integer countRow(SummaryLogFilter filter) {
		return (Integer) getSqlMapClientTemplate().queryForObject("S_SUMMARY_LOGS_3G.countRow", filter);
	}
}