package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.SummaryConfig;
import vn.com.vhc.vmsc2.statistics.web.filter.SummaryConfigFilter;

public class SummaryConfigDAOImpl extends SqlMapClientDaoSupport implements SummaryConfigDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public SummaryConfigDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public int deleteByPrimaryKey(Integer configId) {
		SummaryConfig key = new SummaryConfig();
		key.setConfigId(configId);
		int rows = getSqlMapClientTemplate().delete("S_SUMMARY_CONFIGS.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public void insert(SummaryConfig record) {
		getSqlMapClientTemplate().insert("S_SUMMARY_CONFIGS.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public void insertSelective(SummaryConfig record) {
		getSqlMapClientTemplate().insert("S_SUMMARY_CONFIGS.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public SummaryConfig selectByPrimaryKey(Integer configId) {
		SummaryConfig key = new SummaryConfig();
		key.setConfigId(configId);
		SummaryConfig record = (SummaryConfig) getSqlMapClientTemplate().queryForObject("S_SUMMARY_CONFIGS.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public int updateByPrimaryKeySelective(SummaryConfig record) {
		int rows = getSqlMapClientTemplate().update("S_SUMMARY_CONFIGS.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table S_SUMMARY_CONFIGS
	 * 
	 * @ibatorgenerated Tue Sep 07 10:32:18 ICT 2010
	 */
	public int updateByPrimaryKey(SummaryConfig record) {
		int rows = getSqlMapClientTemplate().update("S_SUMMARY_CONFIGS.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
	public List<SummaryConfig> getAll() {
		return getSqlMapClientTemplate().queryForList("S_SUMMARY_CONFIGS.getAll");
	}

	@SuppressWarnings("unchecked")
	public List<SummaryConfig> filter(SummaryConfigFilter filter) {
		return getSqlMapClientTemplate().queryForList("S_SUMMARY_CONFIGS.filter", filter);
	}

	public SummaryConfig exitSummaryConfig(String tableName, String columnName) 
	{
		SummaryConfig key = new SummaryConfig();
		key.setTableName(tableName);
		key.setColumnName(columnName);
		SummaryConfig record = (SummaryConfig) getSqlMapClientTemplate().queryForObject("S_SUMMARY_CONFIGS.exitSummaryConfig", key);
		
			return record;
	}
}