package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.SYS_PARAMETER;

public class SYS_PARAMETERDAOImpl extends SqlMapClientDaoSupport implements SYS_PARAMETERDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public SYS_PARAMETERDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        SYS_PARAMETER key = new SYS_PARAMETER();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SYS_PARAMETER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public void insert(SYS_PARAMETER record) {
        getSqlMapClientTemplate().insert("SYS_PARAMETER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public void insertSelective(SYS_PARAMETER record) {
        getSqlMapClientTemplate().insert("SYS_PARAMETER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public SYS_PARAMETER selectByPrimaryKey(Integer id) {
        SYS_PARAMETER key = new SYS_PARAMETER();
        key.setId(id);
        SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate().queryForObject("SYS_PARAMETER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public int updateByPrimaryKeySelective(SYS_PARAMETER record) {
        int rows = getSqlMapClientTemplate().update("SYS_PARAMETER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    public int updateByPrimaryKey(SYS_PARAMETER record) {
        int rows = getSqlMapClientTemplate().update("SYS_PARAMETER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getSysParameterByCode(String code){
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSysParameterByCode", code);
    }
    
    @SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getSystemNotInSysMenu(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSystemNotInSysMenu", parms);
    }

	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> checkWarningTypeExits(String code, String name) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("name", name);
		parms.put("code", code);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.checkWarningTypeExits", parms);
	}
	
	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getListTTPACount(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getListTTPACount", parms);
    }
    
	
    public SYS_PARAMETER getSPByValue(String value){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
    	parms.put("P_VALUE", value);
		parms.put("P_DATA", null);
		SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate().queryForObject("SYS_PARAMETER.getSPByValue", parms);
    	return record;
    }

	@SuppressWarnings("unchecked")
	
    public List<SYS_PARAMETER> getSPByCodeAndName(String code, String name){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
    	parms.put("P_CODE", code);
    	parms.put("P_NAME", name);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSPByCodeAndName", parms);
    }
	@SuppressWarnings("unchecked")
	
	public SYS_PARAMETER getValueByCodeName(String pName, String pValue) {
		SYS_PARAMETER key = new SYS_PARAMETER();
        key.setCode(pName);
        key.setName(pValue);
        List<SYS_PARAMETER> record = getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getValueByCodeName", key);
    	if (record!=null)
    		return record.get(0);
    	else
    		return null;
	}

	
	public int updateByCodeName(SYS_PARAMETER record) {
		 int rows = getSqlMapClientTemplate().update("SYS_PARAMETER.updateByCodeName", record);
	     return rows;
	}
	
	@SuppressWarnings("unchecked")
	
    public List<SYS_PARAMETER> getSysParametersFilter(String code, String name, String column, String order){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
    	parms.put("P_CODE", code);
    	parms.put("P_NAME", name);
    	parms.put("P_COLUMN", column);
		parms.put("P_ORDER", order);
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSysParametersFilter", parms);
    }
    
    @SuppressWarnings("unchecked")
	
    public List<SYS_PARAMETER> distinctMaThamSo(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.distinctMaThamSo", parms);
    }
    
    @SuppressWarnings("unchecked")
	
    public List<SYS_PARAMETER> titleSysParameter(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.titleSysParameter", parms);
    }
    
    @SuppressWarnings("unchecked")
	
    public List<SYS_PARAMETER> getListHourOnDay(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getListHourOnDay", parms);
    }

    @SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getAlarmType() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);	
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getAlarmType", parms);
	}

	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getStatusFinish() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);	
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getStatusFinish", parms);
	}

	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getCausebySystem() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);	
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getCausebySystem", parms);
	}
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getStatusDVTUCTT() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getStatusDVTUCTT", parms);
	}
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getStatusNode() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getStatusNode", parms);
	}
	
	
	public SYS_PARAMETER getTimerLossDip() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate().queryForObject("SYS_PARAMETER.getTimerLossDip", parms);
    	return record;
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getCondition() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getCondition", parms);
	}
	//@author Thang
	
	/*
    public List<SYS_PARAMETER> getSPByName(String name, String value){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
    	parms.put("P_NAME", name);
    	parms.put("P_VALUE", value);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSPByName", parms);
    }*/
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getSPByName(String alarmType, String netWork,
			String typeForm) {
		Map<String, Object> parms = new HashMap<String, Object>();
    	parms.put("P_NAME", alarmType);
    	parms.put("P_REMARK", netWork);
    	parms.put("P_TYPE_FORM", typeForm);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSPByName", parms);
	}
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getVendorList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getVendorList", parms);
	}

	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getGroupQualityList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getGroupQualityList", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getProcessFeedbackJob() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getProcessFeedbackJob", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getStatusOfCentralFb() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getStatusOfCentralFb", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getIsEnableCableOdfList(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getIsEnableCableOdfList", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getLoaiBaoCaoList(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getLoaiBaoCaoList", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getColorOdfLienTang(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getColorOdfLienTang", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getAsImportWarehouseUnit(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getAsImportWarehouseUnit", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getSameUnitAssets(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSameUnitAssets", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> asImportWarehouseByUnit(String unit){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_UNIT", unit);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.asImportWarehouseByUnit", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getListFbIbc(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getListFbIbc", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getHomePage(String module){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MODULE", module);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getHomePage", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getUserAdmin(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getUserAdmin", parms);
	}
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> titleSysParameterByCode(String typeCode,
			String typeForm) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_CODE", typeCode);  
		map.put("P_TYPE_FORM", typeForm); 
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.titleSysParameterByCode", map);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getModuleWhenLogin(String moduleValue){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MODULE_VALUE", moduleValue);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getModuleWhenLogin", parms);
	}
	
	@SuppressWarnings("unchecked")
	
	public List<SYS_PARAMETER> getEquipmentType(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getEquipmentType", parms);
	}
	
	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getStatusEquipmentType(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getStatusEquipmentType", parms);
	}
	
	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getYesNoList(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getYesNoList", parms);
	}
	 @SuppressWarnings("unchecked") 
	public List<SYS_PARAMETER> getVendorForResourceList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getVendorForResourceList", parms);
	}
	
}