package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.SYS_PARAMETER;

public interface SYS_PARAMETERDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    void insert(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    void insertSelective(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    SYS_PARAMETER selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int updateByPrimaryKeySelective(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int updateByPrimaryKey(SYS_PARAMETER record);

	List<SYS_PARAMETER> getSysParameterByCode(String code);

	List<SYS_PARAMETER> getSystemNotInSysMenu();

	List<SYS_PARAMETER> checkWarningTypeExits(String code, String name);

	List<SYS_PARAMETER> getListTTPACount();

	SYS_PARAMETER getSPByValue(String value);
	
	List<SYS_PARAMETER> getSPByCodeAndName(String code, String name);

	SYS_PARAMETER getValueByCodeName(String pName, String pValue);

	int updateByCodeName(SYS_PARAMETER record);

	List<SYS_PARAMETER> getSysParametersFilter(String code, String name,
			String column, String order);

	List<SYS_PARAMETER> distinctMaThamSo();

	List<SYS_PARAMETER> titleSysParameter();

	List<SYS_PARAMETER> getListHourOnDay();

	List<SYS_PARAMETER> getAlarmType();

	List<SYS_PARAMETER> getStatusFinish();

	List<SYS_PARAMETER> getCausebySystem();

	List<SYS_PARAMETER> getStatusDVTUCTT();

	List<SYS_PARAMETER> getStatusNode();
	
	List<SYS_PARAMETER> getCondition();

	SYS_PARAMETER getTimerLossDip();
	
	// @author Thangpx
	/*List<SYS_PARAMETER> getSPByName(String pName, String pValue);
*/
	List<SYS_PARAMETER> getSPByName(String alarmType, String netWork,
			String typeForm);

	List<SYS_PARAMETER> getVendorList();

	List<SYS_PARAMETER> getGroupQualityList();

	List<SYS_PARAMETER> getProcessFeedbackJob();

	List<SYS_PARAMETER> getStatusOfCentralFb();

	List<SYS_PARAMETER> getIsEnableCableOdfList();

	List<SYS_PARAMETER> getLoaiBaoCaoList();

	List<SYS_PARAMETER> getColorOdfLienTang();

	List<SYS_PARAMETER> getAsImportWarehouseUnit();

	List<SYS_PARAMETER> asImportWarehouseByUnit(String unit);

	List<SYS_PARAMETER> getSameUnitAssets();

	List<SYS_PARAMETER> getListFbIbc();

	List<SYS_PARAMETER> getHomePage(String module); 
	
	List<SYS_PARAMETER> getUserAdmin();

	List<SYS_PARAMETER> titleSysParameterByCode(String typeCode, String string);

	List<SYS_PARAMETER> getModuleWhenLogin(String moduleValue);

	List<SYS_PARAMETER> getEquipmentType();

	List<SYS_PARAMETER> getStatusEquipmentType();
	List<SYS_PARAMETER> getYesNoList();
	List<SYS_PARAMETER> getVendorForResourceList();
}