package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.SysParameter;

public class SysParameterDAOImpl extends SqlMapClientDaoSupport implements SysParameterDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public SysParameterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        SysParameter key = new SysParameter();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SYS_PARAMETERS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public void insert(SysParameter record) {
        getSqlMapClientTemplate().insert("SYS_PARAMETERS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public void insertSelective(SysParameter record) {
        getSqlMapClientTemplate().insert("SYS_PARAMETERS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public SysParameter selectByPrimaryKey(Integer id) {
        SysParameter key = new SysParameter();
        key.setId(id);
        SysParameter record = (SysParameter) getSqlMapClientTemplate().queryForObject("SYS_PARAMETERS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public int updateByPrimaryKeySelective(SysParameter record) {
        int rows = getSqlMapClientTemplate().update("SYS_PARAMETERS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETERS
     *
     * @ibatorgenerated Wed Sep 26 17:46:03 ICT 2012
     */
    public int updateByPrimaryKey(SysParameter record) {
        int rows = getSqlMapClientTemplate().update("SYS_PARAMETERS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
    public List<SysParameter> filter(String code){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("code", code);
    return getSqlMapClientTemplate().queryForList("SYS_PARAMETERS.filter", map);
    }
    @SuppressWarnings("unchecked")
    public List<SysParameter> filter(String code, String name){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("code", code);
    	map.put("name", name);
    return getSqlMapClientTemplate().queryForList("SYS_PARAMETERS.filterbyName", map);
    }
   
}