package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VDyCellData2G;

public class VDyCellData2GDAOImpl extends SqlMapClientDaoSupport implements VDyCellData2GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_CELL_DATA_2G
     *
     * @ibatorgenerated Wed Dec 19 15:56:48 ICT 2012
     */
    public VDyCellData2GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_CELL_DATA_2G
     *
     * @ibatorgenerated Wed Dec 19 15:56:48 ICT 2012
     */
    public void insert(VDyCellData2G record) {
        getSqlMapClientTemplate().insert("V_DY_CELL_DATA_2G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_DY_CELL_DATA_2G
     *
     * @ibatorgenerated Wed Dec 19 15:56:48 ICT 2012
     */
    public void insertSelective(VDyCellData2G record) {
        getSqlMapClientTemplate().insert("V_DY_CELL_DATA_2G.ibatorgenerated_insertSelective", record);
    }
    
    
    @SuppressWarnings("unchecked")
	public List<VDyCellData2G> filter(String startDate, String endDate, String bscid, String cellid){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
    	map.put("bscid", bscid);
    	map.put("cellid", cellid);
    	return getSqlMapClientTemplate().queryForList("V_DY_CELL_DATA_2G.filter", map);
    }
    
    @SuppressWarnings("unchecked")
    public List<VDyCellData2G> filter2(String startDate, String endDate, String bscid, String cellid) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("bscid", bscid);
		return getSqlMapClientTemplate().queryForList("V_DY_CELL_DATA_2G.filter2", map);
	}
}