package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VHrIpbbLink;
import vn.com.vhc.vmsc2.statistics.web.filter.IPBBFilter;


public interface VHrIpbbLinkDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_HR_IPBB_LINK
     *
     * @ibatorgenerated Fri Nov 23 09:58:36 ICT 2012
     */
    void insert(VHrIpbbLink record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_HR_IPBB_LINK
     *
     * @ibatorgenerated Fri Nov 23 09:58:36 ICT 2012
     */
    void insertSelective(VHrIpbbLink record);
    
    List<VHrIpbbLink> filter(IPBBFilter filter);
}