package vn.com.vhc.vmsc2.statistics.dao;

import vn.com.vhc.vmsc2.statistics.domain.VRDyBranchGprs;

public interface VRDyBranchGprsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_R_DY_BRANCH_GPRSEDGE
     *
     * @ibatorgenerated Tue Aug 14 11:43:53 ICT 2012
     */
    void insert(VRDyBranchGprs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_R_DY_BRANCH_GPRSEDGE
     *
     * @ibatorgenerated Tue Aug 14 11:43:53 ICT 2012
     */
    void insertSelective(VRDyBranchGprs record);
}