package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellHoBhIbc;

public class VRpDyCellHoBhIbcDAOImpl extends SqlMapClientDaoSupport implements VRpDyCellHoBhIbcDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:40 ICT 2010
     */
    public VRpDyCellHoBhIbcDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:40 ICT 2010
     */
    public void insert(VRpDyCellHoBhIbc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_HO_BH_IBC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:40 ICT 2010
     */
    public void insertSelective(VRpDyCellHoBhIbc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_HO_BH_IBC.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyCellHoBhIbc> filterDetails(String startDate, String endDate, String bscid, String cellid) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("startDate", startDate);
		map.put("endDate",  endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_HO_BH_IBC.filterDetails", map);
	}
}