package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyNBscUtilTrau2g;

public class VRpDyNBscUtilTrau2gDAOImpl extends SqlMapClientDaoSupport implements VRpDyNBscUtilTrau2gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_N_BSC_UTIL_TRAU_2G
     *
     * @ibatorgenerated Fri Nov 29 10:32:24 ICT 2013
     */
    public VRpDyNBscUtilTrau2gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_N_BSC_UTIL_TRAU_2G
     *
     * @ibatorgenerated Fri Nov 29 10:32:24 ICT 2013
     */
    public void insert(VRpDyNBscUtilTrau2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_N_BSC_UTIL_TRAU_2G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_N_BSC_UTIL_TRAU_2G
     *
     * @ibatorgenerated Fri Nov 29 10:32:24 ICT 2013
     */
    public void insertSelective(VRpDyNBscUtilTrau2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_N_BSC_UTIL_TRAU_2G.ibatorgenerated_insertSelective", record);
    }
    public List<VRpDyNBscUtilTrau2g> filterHourly(String tableName, String bscid, String objName,String startDate, String startHour, String endHour)
    {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TABLE_NAME", 		tableName);
    	parms.put("P_BSCID", 		bscid);
    	parms.put("P_OBJNAME", 		objName);
    	parms.put("P_START_DATE", 		startDate);
    	parms.put("P_START_HOUR", 		startHour);
    	parms.put("P_END_HOUR", 		endHour);
    	parms.put("P_DATA", 				null);
    	
		@SuppressWarnings("unchecked")
		List<VRpDyNBscUtilTrau2g> record = getSqlMapClientTemplate().queryForList("V_RP_DY_N_BSC_UTIL_TRAU_2G.filterHourly", parms);
        return record;
	}
    public List<VRpDyNBscUtilTrau2g> filterDaily(String tableName,String bscid, String objName,String startDate, String endDate) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TABLE_NAME", 		tableName);
		parms.put("P_BSCID", 		bscid);
    	parms.put("P_OBJNAME", 		objName);
    	parms.put("P_START_DATE", 		startDate);
    	parms.put("P_END_DATE", 		endDate);
    	parms.put("P_DATA", 				null);
    	
		@SuppressWarnings("unchecked")
		List<VRpDyNBscUtilTrau2g> record = getSqlMapClientTemplate().queryForList("V_RP_DY_N_BSC_UTIL_TRAU_2G.filterDaily", parms);
        return record;
	}
}