package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyIrsrAlarmDistrict3g;

public class VRpDyIrsrAlarmDistrict3gDAOImpl extends SqlMapClientDaoSupport implements VRpDyIrsrAlarmDistrict3gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:40:03 GMT+07:00 2011
     */
    public VRpDyIrsrAlarmDistrict3gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:40:03 GMT+07:00 2011
     */
    public void insert(VRpDyIrsrAlarmDistrict3g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_IRSR_ALARM_DISTRICT_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:40:03 GMT+07:00 2011
     */
    public void insertSelective(VRpDyIrsrAlarmDistrict3g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_IRSR_ALARM_DISTRICT_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyIrsrAlarmDistrict3g> filter(String region, String province, String district, String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("district", district);
		map.put("province", province);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_IRSR_ALARM_DISTRICT_3G.filter", map);
	}
}