package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;


import vn.com.vhc.vmsc2.statistics.domain.VRpDyMscMgwCPLoad;

public class VRpDyMscMgwCPLoadDAOImpl extends SqlMapClientDaoSupport implements VRpDyMscMgwCPLoadDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:36 ICT 2013
     */
    public VRpDyMscMgwCPLoadDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:36 ICT 2013
     */
    public void insert(VRpDyMscMgwCPLoad record) {
        getSqlMapClientTemplate().insert("V_RP_DY_MSC_MGW_CPLOAD.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:36 ICT 2013
     */
    public void insertSelective(VRpDyMscMgwCPLoad record) {
        getSqlMapClientTemplate().insert("V_RP_DY_MSC_MGW_CPLOAD.ibatorgenerated_insertSelective", record);
    }
    @SuppressWarnings("unchecked")
    public List<VRpDyMscMgwCPLoad> filter(String startDate, String endDate, String mscid) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("mscid", mscid);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_MSC_MGW_CPLOAD.filter", map);
	}
    @SuppressWarnings("unchecked")
    public List<VRpDyMscMgwCPLoad> filterDay(String startDate, String endDate) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_MSC_MGW_CPLOAD.filterDay", map);
	}
}