package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyBranch3G;

public class VRpDyBranch3GDAOImpl extends SqlMapClientDaoSupport implements VRpDyBranch3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public VRpDyBranch3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public void insert(VRpDyBranch3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BRANCH_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public void insertSelective(VRpDyBranch3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BRANCH_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyBranch3G> filter(String startDate, String endDate, String branch, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("branch", branch);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_BRANCH_3G.filter", map);
	}
}