package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyRegionData2g;

public class VRpDyRegionData2gDAOImpl extends SqlMapClientDaoSupport implements VRpDyRegionData2gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_DATA_2G
     *
     * @ibatorgenerated Mon Sep 12 09:10:12 GMT+07:00 2011
     */
    public VRpDyRegionData2gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_DATA_2G
     *
     * @ibatorgenerated Mon Sep 12 09:10:12 GMT+07:00 2011
     */
    public void insert(VRpDyRegionData2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_DATA_2G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_DATA_2G
     *
     * @ibatorgenerated Mon Sep 12 09:10:12 GMT+07:00 2011
     */
    public void insertSelective(VRpDyRegionData2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_DATA_2G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyRegionData2g> filter(String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("startDate", startDate);
		map.put("endDate",  endDate);
		map.put("region",  region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_REGION_DATA_2G.filter", map);
	}
}