package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyDistrictIbc;


public interface VRpDyDistrictIbcDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DISTRICT_IBC
     *
     * @ibatorgenerated Mon Dec 20 15:10:46 ICT 2010
     */
    void insert(VRpDyDistrictIbc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DISTRICT_IBC
     *
     * @ibatorgenerated Mon Dec 20 15:10:46 ICT 2010
     */
    void insertSelective(VRpDyDistrictIbc record);

	List<VRpDyDistrictIbc> filter(String startDate, String endDate, String province, String district, String region);
}