package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.OptionBsc;
import vn.com.vhc.vmsc2.statistics.domain.VRpDyBsc;

public class VRpDyBscDAOImpl extends SqlMapClientDaoSupport implements VRpDyBscDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC
     *
     * @ibatorgenerated Thu Dec 16 13:50:16 ICT 2010
     */
    public VRpDyBscDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC
     *
     * @ibatorgenerated Thu Dec 16 13:50:16 ICT 2010
     */
    public void insert(VRpDyBsc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC
     *
     * @ibatorgenerated Thu Dec 16 13:50:16 ICT 2010
     */
    public void insertSelective(VRpDyBsc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC.ibatorgenerated_insertSelective", record);
    }

    @SuppressWarnings("unchecked")
    public List<VRpDyBsc> filter(String startDate,String endDate, String bscid, String region){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("bscid", bscid);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
		map.put("region", region);
    return getSqlMapClientTemplate().queryForList("V_RP_DY_BSC.filter2", map);
    }

	@SuppressWarnings("unchecked")
	public List<OptionBsc> BscOption(String startDate, String endDate, int startHour, int endHour, String bscid, String region) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("p_start_date", startDate);
		map.put("p_end_date", endDate);
		map.put("p_start_hour", startHour);
		map.put("p_end_hour", endHour);
		map.put("p_bscid", bscid);
		map.put("p_region", region);	
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_BSC.bscOption", map);
	}

	public OptionBsc countBscOption(String startDate, String endDate, int startHour, int endHour, String bscid, String region) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("p_start_date", startDate);
		map.put("p_end_date", endDate);
		map.put("p_start_hour", startHour);
		map.put("p_end_hour", endHour);
		map.put("p_bscid", bscid);
		map.put("p_region", region);
		map.put("P_DATA", null);
		return (OptionBsc) getSqlMapClientTemplate().queryForObject("V_RP_DY_BSC.countBscOption", map);
	}
}