package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellTrafficBsc3G;

public class VRpDyCellTrafficBsc3GDAOImpl extends SqlMapClientDaoSupport implements VRpDyCellTrafficBsc3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public VRpDyCellTrafficBsc3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insert(VRpDyCellTrafficBsc3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_BSC_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insertSelective(VRpDyCellTrafficBsc3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_BSC_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyCellTrafficBsc3G> filter(String bscid, String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("region", region);
		map.put("bscid", bscid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_TRAFFIC_BSC_3G.filter", map);
	}
}