package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyMscHo3G;

public interface VRpDyMscHo3GDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_HO_3G
     *
     * @ibatorgenerated Fri Nov 08 14:56:49 ICT 2013
     */
    void insert(VRpDyMscHo3G record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_HO_3G
     *
     * @ibatorgenerated Fri Nov 08 14:56:49 ICT 2013
     */
    void insertSelective(VRpDyMscHo3G record);
    List<VRpDyMscHo3G> filterHourly(String tableName, String mscid,String startDate, String startHour, String endHour);
    List<VRpDyMscHo3G> filterDaily(String tableName, String mscid,String startDate, String endDate);
    List<VRpDyMscHo3G> filterMonthly(String tableName,String mscid,String startMonth,String endMonth,String startYear,String endYear);
    List<VRpDyMscHo3G> filterWeekly(String tableName,String mscid,String startWeek,String endWeek,String startYear,String endYear);

}