package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellTrafficBsc;

public class VRpDyCellTrafficBscDAOImpl extends SqlMapClientDaoSupport implements VRpDyCellTrafficBscDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC
     *
     * @ibatorgenerated Tue Apr 05 15:49:04 ICT 2011
     */
    public VRpDyCellTrafficBscDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC
     *
     * @ibatorgenerated Tue Apr 05 15:49:04 ICT 2011
     */
    public void insert(VRpDyCellTrafficBsc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_BSC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_BSC
     *
     * @ibatorgenerated Tue Apr 05 15:49:04 ICT 2011
     */
    public void insertSelective(VRpDyCellTrafficBsc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_BSC.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyCellTrafficBsc> filter(String bscid, String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_TRAFFIC_BSC.filter", map);
	}
}