package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCsiCmdLicence;

public interface VRpDyCsiCmdLicenceDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CSI_CMD_LICENCE
     *
     * @ibatorgenerated Tue Aug 05 15:23:03 ICT 2014
     */
    void insert(VRpDyCsiCmdLicence record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CSI_CMD_LICENCE
     *
     * @ibatorgenerated Tue Aug 05 15:23:03 ICT 2014
     */
    void insertSelective(VRpDyCsiCmdLicence record);
    List<VRpDyCsiCmdLicence> getCsiCmdLicence(String mscid, String type, String startDate, String endDate);
}