package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyMscHo2G;  
public interface VRpDyMscHo2GDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_HO_2G
     *
     * @ibatorgenerated Fri Nov 08 11:54:31 ICT 2013
     */
    void insert(VRpDyMscHo2G record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_MSC_HO_2G
     *
     * @ibatorgenerated Fri Nov 08 11:54:31 ICT 2013
     */
    void insertSelective(VRpDyMscHo2G record);
    
    List<VRpDyMscHo2G> filterHourly(String tableName, String mscid,String startDate, String startHour, String endHour);
    List<VRpDyMscHo2G> filterDaily(String tableName, String mscid,String startDate, String endDate);
    List<VRpDyMscHo2G> filterMonthly(String tableName,String mscid,String startMonth,String endMonth,String startYear,String endYear);
    List<VRpDyMscHo2G> filterWeekly(String tableName,String mscid,String startWeek,String endWeek,String startYear,String endYear);

}