package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellToCellQos3G;

public class VRpDyCellToCellQos3GDAOImpl extends SqlMapClientDaoSupport implements VRpDyCellToCellQos3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TO_CELL_QOS_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public VRpDyCellToCellQos3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TO_CELL_QOS_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insert(VRpDyCellToCellQos3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TO_CELL_QOS_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TO_CELL_QOS_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insertSelective(VRpDyCellToCellQos3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TO_CELL_QOS_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyCellToCellQos3G> filterCellToCells(String startDate, String endDate, String bscid, String cellid) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_TO_CELL_QOS_3G.filterCellToCells", map);
	}

	@SuppressWarnings("unchecked")
	public List<VRpDyCellToCellQos3G> filterCellsToCell(String startDate, String endDate, String bscid, String cellid) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_TO_CELL_QOS_3G.filterCellsToCell", map);
	}
}