package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCsiCmdLicence;

public class VRpDyCsiCmdLicenceDAOImpl extends SqlMapClientDaoSupport implements VRpDyCsiCmdLicenceDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CSI_CMD_LICENCE
     *
     * @ibatorgenerated Tue Aug 05 15:23:03 ICT 2014
     */
    public VRpDyCsiCmdLicenceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CSI_CMD_LICENCE
     *
     * @ibatorgenerated Tue Aug 05 15:23:03 ICT 2014
     */
    public void insert(VRpDyCsiCmdLicence record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CSI_CMD_LICENCE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CSI_CMD_LICENCE
     *
     * @ibatorgenerated Tue Aug 05 15:23:03 ICT 2014
     */
    public void insertSelective(VRpDyCsiCmdLicence record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CSI_CMD_LICENCE.ibatorgenerated_insertSelective", record);
    }
    public List<VRpDyCsiCmdLicence> getCsiCmdLicence( String nodeid, String type, String startDate, String endDate) {
		Map<String, Object> parms = new HashMap<String, Object>(); 
    	parms.put("P_NODEID", 		nodeid);
    	parms.put("P_TYPE", 		type);
    	parms.put("P_START_DATE", 		startDate);
    	parms.put("P_END_DATE", 		endDate);
    	parms.put("P_DATA", 				null);
    	
		@SuppressWarnings("unchecked")
		List<VRpDyCsiCmdLicence> record = getSqlMapClientTemplate().queryForList("V_RP_DY_CSI_CMD_LICENCE.getCsiCmdLicence", parms);
        return record;
	}
 
}