package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyRegionIbc;

public class VRpDyRegionIbcDAOImpl extends SqlMapClientDaoSupport implements VRpDyRegionIbcDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_IBC
     *
     * @ibatorgenerated Mon Sep 05 16:06:32 GMT+07:00 2011
     */
    public VRpDyRegionIbcDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_IBC
     *
     * @ibatorgenerated Mon Sep 05 16:06:32 GMT+07:00 2011
     */
    public void insert(VRpDyRegionIbc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_IBC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_IBC
     *
     * @ibatorgenerated Mon Sep 05 16:06:32 GMT+07:00 2011
     */
    public void insertSelective(VRpDyRegionIbc record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_IBC.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyRegionIbc> filter(String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("startDate", startDate);
		map.put("endDate",  endDate);
		map.put("region",  region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_REGION_IBC.filter", map);
	}
}