package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyIrsrAlarmSite2g;

public class VRpDyIrsrAlarmSite2gDAOImpl extends SqlMapClientDaoSupport implements VRpDyIrsrAlarmSite2gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISRS_ARLARM_SITE_2G
     *
     * @ibatorgenerated Thu Sep 15 14:46:56 GMT+07:00 2011
     */
    public VRpDyIrsrAlarmSite2gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISRS_ARLARM_SITE_2G
     *
     * @ibatorgenerated Thu Sep 15 14:46:56 GMT+07:00 2011
     */
    public void insert(VRpDyIrsrAlarmSite2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_ISRS_ARLARM_SITE_2G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_ISRS_ARLARM_SITE_2G
     *
     * @ibatorgenerated Thu Sep 15 14:46:56 GMT+07:00 2011
     */
    public void insertSelective(VRpDyIrsrAlarmSite2g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_ISRS_ARLARM_SITE_2G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyIrsrAlarmSite2g> filter(String bscid, String siteid, String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("region", region);
		map.put("bscid", bscid);
		map.put("siteid", siteid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_ISRS_ARLARM_SITE_2G.filter", map);
	}
}