package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyIrsrAlarmBsc3g;

public class VRpDyIrsrAlarmBsc3gDAOImpl extends SqlMapClientDaoSupport implements VRpDyIrsrAlarmBsc3gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_BSC_3G
     *
     * @ibatorgenerated Thu Aug 04 08:59:53 ICT 2011
     */
    public VRpDyIrsrAlarmBsc3gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_BSC_3G
     *
     * @ibatorgenerated Thu Aug 04 08:59:53 ICT 2011
     */
    public void insert(VRpDyIrsrAlarmBsc3g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_IRSR_ALARM_BSC_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_IRSR_ALARM_BSC_3G
     *
     * @ibatorgenerated Thu Aug 04 08:59:53 ICT 2011
     */
    public void insertSelective(VRpDyIrsrAlarmBsc3g record) {
        getSqlMapClientTemplate().insert("V_RP_DY_IRSR_ALARM_BSC_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyIrsrAlarmBsc3g> filter(String bscid, String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_IRSR_ALARM_BSC_3G.filter", map);
	}
}