package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyRegion3G;

public class VRpDyRegion3GDAOImpl extends SqlMapClientDaoSupport implements VRpDyRegion3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_3G
     *
     * @ibatorgenerated Mon Apr 25 11:01:01 ICT 2011
     */
    public VRpDyRegion3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_3G
     *
     * @ibatorgenerated Mon Apr 25 11:01:01 ICT 2011
     */
    public void insert(VRpDyRegion3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_REGION_3G
     *
     * @ibatorgenerated Mon Apr 25 11:01:01 ICT 2011
     */
    public void insertSelective(VRpDyRegion3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_REGION_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyRegion3G> filter(String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("startDate", "'" + startDate + "'");
		map.put("endDate",  "'" + endDate + "'");
		return getSqlMapClientTemplate().queryForList("V_RP_DY_REGION_3G.filter", map);
	}

	@SuppressWarnings("unchecked")
	public List<VRpDyRegion3G> filter(String startDate, String endDate, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("startDate", startDate);
		map.put("endDate",  endDate);
		map.put("region",  region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_REGION_3G.filter", map);
	}
}