package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyBscDcrtQos;

public class VRpDyBscDcrtQosDAOImpl extends SqlMapClientDaoSupport implements VRpDyBscDcrtQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:08:48 ICT 2011
     */
    public VRpDyBscDcrtQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:08:48 ICT 2011
     */
    public void insert(VRpDyBscDcrtQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC_DCRT_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_BSC_DCRT_QOS
     *
     * @ibatorgenerated Wed Feb 23 10:08:48 ICT 2011
     */
    public void insertSelective(VRpDyBscDcrtQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_BSC_DCRT_QOS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpDyBscDcrtQos> filter(String startDate,String endDate, String bscid, String region){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("bscid", bscid);
    	map.put("startDate", startDate);
    	map.put("endDate", endDate);
		map.put("region", region);
    return getSqlMapClientTemplate().queryForList("V_RP_DY_BSC_DCRT_QOS.filter2", map);
    }
}