package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VrpDyGgsnSummary;

public class VrpDyGgsnSummaryDAOImpl extends SqlMapClientDaoSupport implements VrpDyGgsnSummaryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_GGSN_SUMMARY
     *
     * @ibatorgenerated Fri Feb 01 14:11:07 ICT 2013
     */
    public VrpDyGgsnSummaryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_GGSN_SUMMARY
     *
     * @ibatorgenerated Fri Feb 01 14:11:07 ICT 2013
     */
    public void insert(VrpDyGgsnSummary record) {
        getSqlMapClientTemplate().insert("V_RP_DY_GGSN_SUMMARY.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_GGSN_SUMMARY
     *
     * @ibatorgenerated Fri Feb 01 14:11:07 ICT 2013
     */
    public void insertSelective(VrpDyGgsnSummary record) {
        getSqlMapClientTemplate().insert("V_RP_DY_GGSN_SUMMARY.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
   	public List<VrpDyGgsnSummary> filter(String startDate, String endDate, String ggsnid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startDate", startDate);
   		map.put("endDate", endDate);
   		map.put("ggsnid", ggsnid);
   		return getSqlMapClientTemplate().queryForList("V_RP_DY_GGSN_SUMMARY.filter", map);
   	}
    
    @SuppressWarnings("unchecked")
    public List<VrpDyGgsnSummary> filter1(String startDate, String endDate){
    	Map<String, String> map = new HashMap<String, String>();
    	map.put("startDate",startDate);
    	map.put("endDate",endDate);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_GGSN_SUMMARY.filter1", map);
    }
}