package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyDns2;

public class VRpDyDns2DAOImpl extends SqlMapClientDaoSupport implements VRpDyDns2DAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DNS_2
     *
     * @ibatorgenerated Wed Aug 06 17:14:05 ICT 2014
     */
    public VRpDyDns2DAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DNS_2
     *
     * @ibatorgenerated Wed Aug 06 17:14:05 ICT 2014
     */
    public void insert(VRpDyDns2 record) {
        getSqlMapClientTemplate().insert("V_RP_DY_DNS_2.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DNS_2
     *
     * @ibatorgenerated Wed Aug 06 17:14:05 ICT 2014
     */
    public void insertSelective(VRpDyDns2 record) {
        getSqlMapClientTemplate().insert("V_RP_DY_DNS_2.ibatorgenerated_insertSelective", record);
    }
    public List<VRpDyDns2> filterDaily(String tableName,String nodeid,String startDate, String endDate) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_TABLE_NAME", 		tableName);
    	parms.put("P_NODEID", 		nodeid);
    	parms.put("P_START_DATE", 		startDate);
    	parms.put("P_END_DATE", 		endDate);
    	parms.put("P_DATA", 				null);
    	
		@SuppressWarnings("unchecked")
		List<VRpDyDns2> record = getSqlMapClientTemplate().queryForList("V_RP_DY_DNS_2.filterDaily", parms);
        return record;
	}
}