package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.OptionDistrict;
import vn.com.vhc.vmsc2.statistics.domain.VRpDyDistrict;

public class VRpDyDistrictDAOImpl extends SqlMapClientDaoSupport implements VRpDyDistrictDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DISTRICT
     *
     * @ibatorgenerated Mon Dec 20 15:10:46 ICT 2010
     */
    public VRpDyDistrictDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DISTRICT
     *
     * @ibatorgenerated Mon Dec 20 15:10:46 ICT 2010
     */
    public void insert(VRpDyDistrict record) {
        getSqlMapClientTemplate().insert("V_RP_DY_DISTRICT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_DISTRICT
     *
     * @ibatorgenerated Mon Dec 20 15:10:46 ICT 2010
     */
    public void insertSelective(VRpDyDistrict record) {
        getSqlMapClientTemplate().insert("V_RP_DY_DISTRICT.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyDistrict> filter(String startDate, String endDate, String province, String district, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("district", district);
		map.put("province", province);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_DY_DISTRICT.filter", map);
	}

	@SuppressWarnings("unchecked")
	public List<OptionDistrict> DistrictOption(String startDate, String endDate, int startHour, int endHour, String region, String province, String district,
			int startRecord, int endRecord, String column, int order) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("p_start_date", startDate);
		map.put("p_end_date", endDate);
		map.put("p_start_hour", startHour);
		map.put("p_end_hour", endHour);
		map.put("p_region", region);
		map.put("p_province", province);
		map.put("p_district", district);
		map.put("p_start_record", startRecord);
		map.put("p_end_record", endRecord);
		map.put("p_column", column);
		map.put("p_order", order);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_DISTRICT.DistrictOption", map);
	}

	public OptionDistrict countDistrictOption(String startDate, String endDate, int startHour, int endHour, String region, String province, String district) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("p_start_date", startDate);
		map.put("p_end_date", endDate);
		map.put("p_start_hour", startHour);
		map.put("p_end_hour", endHour);
		map.put("p_region", region);
		map.put("p_province", province);
		map.put("p_district", district);
		map.put("P_DATA", null);
		return (OptionDistrict) getSqlMapClientTemplate().queryForObject("V_RP_DY_DISTRICT.countDistrictOption", map);

	}
}