package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellTrafficDistrict3g;


public interface VRpDyCellTrafficDistrict3gDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table V_RP_DY_CELL_TRAFF_DISTRICT_3G
	 * 
	 * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
	 */
	void insert(VRpDyCellTrafficDistrict3g record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table V_RP_DY_CELL_TRAFF_DISTRICT_3G
	 * 
	 * @ibatorgenerated Tue Jul 05 14:51:42 ICT 2011
	 */
	void insertSelective(VRpDyCellTrafficDistrict3g record);

	List<VRpDyCellTrafficDistrict3g> filter(String province, String district, String startDate, String endDate);
}