package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyCellTrafficRegion3G;

public class VRpDyCellTrafficRegion3GDAOImpl extends SqlMapClientDaoSupport implements VRpDyCellTrafficRegion3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_REGION_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public VRpDyCellTrafficRegion3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_REGION_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insert(VRpDyCellTrafficRegion3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_REGION_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_CELL_TRAFFIC_REGION_3G
     *
     * @ibatorgenerated Mon Jun 13 15:33:08 ICT 2011
     */
    public void insertSelective(VRpDyCellTrafficRegion3G record) {
        getSqlMapClientTemplate().insert("V_RP_DY_CELL_TRAFFIC_REGION_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyCellTrafficRegion3G> filter(String region, String startDate, String endDate) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("region", region);
		map.put("startDate", startDate);
		map.put("endDate", endDate);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_CELL_TRAFFIC_REGION_3G.filter", map);
	}
}