package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpDyProvinceGprsQos;

public class VRpDyProvinceGprsQosDAOImpl extends SqlMapClientDaoSupport implements VRpDyProvinceGprsQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:13 ICT 2010
     */
    public VRpDyProvinceGprsQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:13 ICT 2010
     */
    public void insert(VRpDyProvinceGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_PROVINCE_GPRS_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:13 ICT 2010
     */
    public void insertSelective(VRpDyProvinceGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_DY_PROVINCE_GPRS_QOS.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpDyProvinceGprsQos> filter(String province, Date d, String region) {
		VRpDyProvinceGprsQos key = new VRpDyProvinceGprsQos();
		key.setProvince(province);
		key.setDay(d);
		key.setRegion(region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_PROVINCE_GPRS_QOS.filter", key);
	}

	@SuppressWarnings("unchecked")
	public List<VRpDyProvinceGprsQos> filterDetails(String startDate, String endDate, String province, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("province", province);
		map.put("startDate", startDate);
		map.put("endDate",  endDate);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_DY_PROVINCE_GPRS_QOS.filterDetails", map);
	}
}