package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.OptionProvinceGprsCs;
import vn.com.vhc.vmsc2.statistics.domain.VRpDyProvinceGprsCs;


public interface VRpDyProvinceGprsCsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_GPRS_CS
     *
     * @ibatorgenerated Thu Nov 18 16:57:30 ICT 2010
     */
    void insert(VRpDyProvinceGprsCs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_DY_PROVINCE_GPRS_CS
     *
     * @ibatorgenerated Thu Nov 18 16:57:30 ICT 2010
     */
    void insertSelective(VRpDyProvinceGprsCs record);

	List<VRpDyProvinceGprsCs> filter(String province, Date d, String region);

	List<VRpDyProvinceGprsCs> filterDetails(String startDate, String endDate, String province, String region);

	/**
	 * @author TrungNQ
	 * @createDate 6/11/2015
	 * @decription Tim kiem du lieu muc tuy chon
	 * 
	 * */
	List<OptionProvinceGprsCs> provinceGprsCsOption(
			String startDate, String endDate, int startHour, int endHour,
			String region, String province, int startRecord, int endRecord, String column, int order);
	
	OptionProvinceGprsCs countProvinceGprsCsOption(
			String startDate, String endDate, int startHour, int endHour,
			String region, String province);
}