package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpHrSgsnQos;

public class VRpHrSgsnQosDAOImpl extends SqlMapClientDaoSupport implements VRpHrSgsnQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_SGSN_QOS
     *
     * @ibatorgenerated Wed Jun 22 15:29:43 ICT 2011
     */
    public VRpHrSgsnQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_SGSN_QOS
     *
     * @ibatorgenerated Wed Jun 22 15:29:43 ICT 2011
     */
    public void insert(VRpHrSgsnQos record) {
        getSqlMapClientTemplate().insert("V_RP_HR_SGSN_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_SGSN_QOS
     *
     * @ibatorgenerated Wed Jun 22 15:29:43 ICT 2011
     */
    public void insertSelective(VRpHrSgsnQos record) {
        getSqlMapClientTemplate().insert("V_RP_HR_SGSN_QOS.ibatorgenerated_insertSelective", record);
    }

    @SuppressWarnings("unchecked")
   	public List<VRpHrSgsnQos> filter(String startHour, Date startDate, String endHour,Date endDate, String region, String sgsnid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate",startDate);
   		map.put("endDate",endDate);
   		map.put("region", region);
   		map.put("sgsnid", sgsnid);
       	return getSqlMapClientTemplate().queryForList("V_RP_HR_SGSN_QOS.filter", map);
   	}
       @SuppressWarnings("unchecked")
       public List<VRpHrSgsnQos> filter2(String startHour, Date startDate, String endHour, String region, String sgsnid) {
   		Map<String, Object> map = new HashMap<String, Object>();
   		map.put("startHour", startHour);
   		map.put("endHour", endHour);
   		map.put("startDate", startDate);
   		map.put("region", region);
   		map.put("sgsnid", sgsnid);
   		return getSqlMapClientTemplate().queryForList("V_RP_HR_SGSN_QOS.filter2", map);
      	}
}