package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpHrBscGprsQos;

public class VRpHrBscGprsQosDAOImpl extends SqlMapClientDaoSupport implements VRpHrBscGprsQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BSC_GPRS_QOS
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public VRpHrBscGprsQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BSC_GPRS_QOS
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void insert(VRpHrBscGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_HR_BSC_GPRS_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BSC_GPRS_QOS
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void insertSelective(VRpHrBscGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_HR_BSC_GPRS_QOS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpHrBscGprsQos> filter(Date day,Integer hour,  String bscid, String region){
    	VRpHrBscGprsQos key = new VRpHrBscGprsQos();
    	key.setBscid(bscid);
    	key.setDay(day);
    	key.setHour(hour);
    	key.setRegion(region);
    	return getSqlMapClientTemplate().queryForList("V_RP_HR_BSC_GPRS_QOS.filter", key);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpHrBscGprsQos> filter(String startHour,String endHour,String day,String bscid, String region){
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("startHour", startHour);
		map.put("endHour", endHour);
		map.put("day", day);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_HR_BSC_GPRS_QOS.filter2", map);
    }
}