package vn.com.vhc.vmsc2.statistics.dao;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpHrMscMgwCPLoad;

public class VRpHrMscMgwCPLoadDAOImpl extends SqlMapClientDaoSupport implements VRpHrMscMgwCPLoadDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:49 ICT 2013
     */
    public VRpHrMscMgwCPLoadDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:49 ICT 2013
     */
    public void insert(VRpHrMscMgwCPLoad record) {
        getSqlMapClientTemplate().insert("V_RP_HR_MSC_MGW_CPLOAD.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_MSC_MGW_CPLOAD
     *
     * @ibatorgenerated Mon Jan 07 17:35:49 ICT 2013
     */
    public void insertSelective(VRpHrMscMgwCPLoad record) {
        getSqlMapClientTemplate().insert("V_RP_HR_MSC_MGW_CPLOAD.ibatorgenerated_insertSelective", record);
    }
    @SuppressWarnings("unchecked")
   	public List<VRpHrMscMgwCPLoad> filter(String startHour, Date startDate, String endHour,  Date endDate, String mscid) {
    		Map<String, Object> map = new HashMap<String, Object>();
    		map.put("startHour", startHour);
    		map.put("endHour", endHour);
    		map.put("startDate", startDate);
    		map.put("endDate", endDate);
    		map.put("mscid", mscid);

    		return getSqlMapClientTemplate().queryForList("V_RP_HR_MSC_MGW_CPLOAD.filter", map);
   	}
    @SuppressWarnings("unchecked")
    public List<VRpHrMscMgwCPLoad> filter2(String startHour, Date startDate, String endHour, String mscid) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("startHour", startHour);
		map.put("endHour", endHour);
		map.put("startDate", startDate);
		map.put("mscid", mscid);
		return getSqlMapClientTemplate().queryForList("V_RP_HR_MSC_MGW_CPLOAD.filter2", map);
   	}
}