package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpHrBranch3G;

public class VRpHrBranch3GDAOImpl extends SqlMapClientDaoSupport implements VRpHrBranch3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public VRpHrBranch3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public void insert(VRpHrBranch3G record) {
        getSqlMapClientTemplate().insert("V_RP_HR_BRANCH_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_HR_BRANCH_3G
     *
     * @ibatorgenerated Tue May 10 14:23:21 ICT 2011
     */
    public void insertSelective(VRpHrBranch3G record) {
        getSqlMapClientTemplate().insert("V_RP_HR_BRANCH_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpHrBranch3G> filter(String startHour, String endHour, String day, String branch, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("branch", branch);
		map.put("startHour", startHour);
		map.put("endHour", endHour);
		map.put("day", day);
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_HR_BRANCH_3G.filter", map);
	}
}