package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnCellHo;

public class VRpMnCellHoDAOImpl extends SqlMapClientDaoSupport implements VRpMnCellHoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_HO
     *
     * @ibatorgenerated Tue Nov 16 11:27:00 ICT 2010
     */
    public VRpMnCellHoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_HO
     *
     * @ibatorgenerated Tue Nov 16 11:27:00 ICT 2010
     */
    public void insert(VRpMnCellHo record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_HO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_HO
     *
     * @ibatorgenerated Tue Nov 16 11:27:00 ICT 2010
     */
    public void insertSelective(VRpMnCellHo record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_HO.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpMnCellHo> filter(String bscid, String cellid, Integer month, Integer year) {
		VRpMnCellHo key = new VRpMnCellHo();
		key.setBscid(bscid);
		key.setCellid(cellid);
		key.setMonth(month);
		key.setYear(year);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_HO.filter", key);
	}

	@SuppressWarnings("unchecked")
	public List<VRpMnCellHo> filterDetails(String startMonth, String startYear, String endMonth, String endYear, String bscid, String cellid) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("startMonth", startMonth);
		map.put("startYear",  startYear);
		map.put("endMonth", endMonth);
		map.put("endYear",  endYear);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_HO.filterDetails", map);
	}

	@SuppressWarnings("unchecked")
	public List<VRpMnCellHo> filter(String bscid, String cellid, Integer month, Integer year, int startRecord, int endRecord, String column, String order) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("month", month);
		map.put("year",  year);
		map.put("startRecord", startRecord);
        map.put("endRecord", endRecord);
        map.put("column", column);
        map.put("order", order);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_HO.filter", map);
	}

	public Integer countRow(String bscid, String cellid, Integer month, Integer year) {
		VRpMnCellHo key = new VRpMnCellHo();
		key.setBscid(bscid);
		key.setCellid(cellid);
		key.setMonth(month);
		key.setYear(year);
		return (Integer) getSqlMapClientTemplate().queryForObject("V_RP_MN_CELL_HO.countRow", key);
	}
}