package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnProvince3G;

public class VRpMnProvince3GDAOImpl extends SqlMapClientDaoSupport implements VRpMnProvince3GDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_3G
     *
     * @ibatorgenerated Mon Apr 25 10:16:58 ICT 2011
     */
    public VRpMnProvince3GDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_3G
     *
     * @ibatorgenerated Mon Apr 25 10:16:58 ICT 2011
     */
    public void insert(VRpMnProvince3G record) {
        getSqlMapClientTemplate().insert("V_RP_MN_PROVINCE_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_3G
     *
     * @ibatorgenerated Mon Apr 25 10:16:58 ICT 2011
     */
    public void insertSelective(VRpMnProvince3G record) {
        getSqlMapClientTemplate().insert("V_RP_MN_PROVINCE_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpMnProvince3G> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, String province, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("province", province);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_PROVINCE_3G.filter", map);
	}
}