package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnCellQos;

public interface VRpMnCellQosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_QOS
     *
     * @ibatorgenerated Tue Jul 24 11:19:16 ICT 2012
     */
    void insert(VRpMnCellQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_QOS
     *
     * @ibatorgenerated Tue Jul 24 11:19:16 ICT 2012
     */
    void insertSelective(VRpMnCellQos record);
    List<VRpMnCellQos> filterno(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid);
    List<VRpMnCellQos> filterhigh(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid);
    List<VRpMnCellQos> filterlow(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid);
}