package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnCellHoIbc;


public interface VRpMnCellHoIbcDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_HO
     *
     * @ibatorgenerated Tue Nov 16 11:27:00 ICT 2010
     */
    void insert(VRpMnCellHoIbc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_HO
     *
     * @ibatorgenerated Tue Nov 16 11:27:00 ICT 2010
     */
    void insertSelective(VRpMnCellHoIbc record);

    List<VRpMnCellHoIbc> filter(String bscid, String cellid, Integer month, Integer year);

	List<VRpMnCellHoIbc> filterDetails(String startMonth, String startYear, String endMonth, String endYear, String bscid, String cellid);
}