package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnProvinceGprsQos;

public class VRpMnProvinceGprsQosDAOImpl extends SqlMapClientDaoSupport implements VRpMnProvinceGprsQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:02 ICT 2010
     */
    public VRpMnProvinceGprsQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:02 ICT 2010
     */
    public void insert(VRpMnProvinceGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_MN_PROVINCE_GPRS_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_PROVINCE_GPRS_QOS
     *
     * @ibatorgenerated Thu Nov 18 17:01:02 ICT 2010
     */
    public void insertSelective(VRpMnProvinceGprsQos record) {
        getSqlMapClientTemplate().insert("V_RP_MN_PROVINCE_GPRS_QOS.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpMnProvinceGprsQos> filter(String province, Integer month, Integer year, String region) {
		VRpMnProvinceGprsQos key = new VRpMnProvinceGprsQos();
		key.setProvince(province);
		key.setMonth(month);
		key.setYear(year);
		key.setRegion(region);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_PROVINCE_GPRS_QOS.filter", key);
	}

	@SuppressWarnings("unchecked")
	public List<VRpMnProvinceGprsQos> filterDetails(String startMonth, String startYear, String endMonth, String endYear, String province, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("province", province);
		map.put("startMonth", startMonth);
		map.put("startYear",  startYear);
		map.put("endMonth", endMonth);
		map.put("endYear",  endYear);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_PROVINCE_GPRS_QOS.filterDetails", map);
	}
}