package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnBscHo;

public class VRpMnBscHoDAOImpl extends SqlMapClientDaoSupport implements VRpMnBscHoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_BSC_HO
     *
     * @ibatorgenerated Thu Nov 18 15:00:51 ICT 2010
     */
    public VRpMnBscHoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_BSC_HO
     *
     * @ibatorgenerated Thu Nov 18 15:00:51 ICT 2010
     */
    public void insert(VRpMnBscHo record) {
        getSqlMapClientTemplate().insert("V_RP_MN_BSC_HO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_BSC_HO
     *
     * @ibatorgenerated Thu Nov 18 15:00:51 ICT 2010
     */
    public void insertSelective(VRpMnBscHo record) {
        getSqlMapClientTemplate().insert("V_RP_MN_BSC_HO.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpMnBscHo> filterDetails(String startMonth, String startYear, String endMonth, String endYear, String bscid, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("startMonth", startMonth);
		map.put("startYear",  startYear);
		map.put("endMonth", endMonth);
		map.put("endYear",  endYear);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_BSC_HO.filterDetails", map);
	}

	@SuppressWarnings("unchecked")
	public List<VRpMnBscHo> filter(String bscid, Integer month, Integer year, String region) {
		VRpMnBscHo key = new VRpMnBscHo();
		key.setBscid(bscid);
		key.setMonth(month);
		key.setYear(year);
		key.setRegion(region);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_BSC_HO.filter", key);
	}
	
	@SuppressWarnings("unchecked")
	public List<VRpMnBscHo> filterLS(String startMonth, String endMonth, String startYear, String endYear, String bscid){
		Map<String, String> map = new HashMap<String, String>();
		map.put("startMonth", startMonth);
		map.put("endMonth", endMonth);
		map.put("startYear", startYear);
		map.put("endYear", endYear);
		map.put("bscid", bscid);
		return getSqlMapClientTemplate().queryForList("V_RP_MN_BSC_HO.filterLS",map);
		}
}