package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnCellQos;

public class VRpMnCellQosDAOImpl extends SqlMapClientDaoSupport implements VRpMnCellQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_QOS
     *
     * @ibatorgenerated Tue Jul 24 11:19:16 ICT 2012
     */
    public VRpMnCellQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_QOS
     *
     * @ibatorgenerated Tue Jul 24 11:19:16 ICT 2012
     */
    public void insert(VRpMnCellQos record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_QOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_QOS
     *
     * @ibatorgenerated Tue Jul 24 11:19:16 ICT 2012
     */
    public void insertSelective(VRpMnCellQos record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_QOS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellQos> filterhigh(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid){
		Map<String, String> map = new HashMap<String, String>();
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("bscid", bscid);
		map.put("cellid", cellid);
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_QOS.filterhigh", map);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellQos> filterlow(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid){
		Map<String, String> map = new HashMap<String, String>();
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("bscid", bscid);
		map.put("cellid", cellid);
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_QOS.filterlow", map);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellQos> filterno(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid){
		Map<String, String> map = new HashMap<String, String>();
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("bscid", bscid);
		map.put("cellid", cellid);
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_QOS.filterno", map);
    }
}