package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnRegion2G3G;


public interface VRpMnRegion2G3GDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_REGION_2G_3G
     *
     * @ibatorgenerated Fri Jun 03 10:11:24 ICT 2011
     */
    void insert(VRpMnRegion2G3G record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_REGION_2G_3G
     *
     * @ibatorgenerated Fri Jun 03 10:11:24 ICT 2011
     */
    void insertSelective(VRpMnRegion2G3G record);

	List<VRpMnRegion2G3G> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, String region);
}