package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VrpMnIpbbLink1;

public class VrpMnIpbbLink1DAOImpl extends SqlMapClientDaoSupport implements VrpMnIpbbLink1DAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_IPBB_LINK1
     *
     * @ibatorgenerated Mon Feb 04 11:51:20 ICT 2013
     */
    public VrpMnIpbbLink1DAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_IPBB_LINK1
     *
     * @ibatorgenerated Mon Feb 04 11:51:20 ICT 2013
     */
    public void insert(VrpMnIpbbLink1 record) {
        getSqlMapClientTemplate().insert("V_RP_MN_IPBB_LINK1.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_IPBB_LINK1
     *
     * @ibatorgenerated Mon Feb 04 11:51:20 ICT 2013
     */
    public void insertSelective(VrpMnIpbbLink1 record) {
        getSqlMapClientTemplate().insert("V_RP_MN_IPBB_LINK1.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
	public List<VrpMnIpbbLink1> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("startMonth", Integer.toString(startMonth));
		map.put("startYear",  Integer.toString(startYear));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("endYear",  Integer.toString(endYear));
		return getSqlMapClientTemplate().queryForList("V_RP_MN_IPBB_LINK1.filter", map);
	}
}