package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpMnCellGprsCs;

public class VRpMnCellGprsCsDAOImpl extends SqlMapClientDaoSupport implements VRpMnCellGprsCsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_GPRS_CS
     *
     * @ibatorgenerated Mon Nov 15 14:09:02 ICT 2010
     */
    public VRpMnCellGprsCsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_GPRS_CS
     *
     * @ibatorgenerated Mon Nov 15 14:09:02 ICT 2010
     */
    public void insert(VRpMnCellGprsCs record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_GPRS_CS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_MN_CELL_GPRS_CS
     *
     * @ibatorgenerated Mon Nov 15 14:09:02 ICT 2010
     */
    public void insertSelective(VRpMnCellGprsCs record) {
        getSqlMapClientTemplate().insert("V_RP_MN_CELL_GPRS_CS.ibatorgenerated_insertSelective", record);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellGprsCs> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, String cellid, String province,String bscid, String region, int startRecord, int endRecord, String column, String order){
    	Map<String, Object> map = new HashMap<String, Object>();
		map.put("cellid", cellid);
		map.put("bscid", bscid);
		map.put("province", province);
		map.put("region", region);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("startRecord", startRecord);
		map.put("endRecord", endRecord);
		map.put("column", column);
		map.put("order", order);
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_GPRS_CS.filter", map);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellGprsCs> filter(Integer startMonth, Integer startYear, Integer endMonth, Integer endYear, String cellid, String province,String bscid, String region){
    	Map<String, Object> map = new HashMap<String, Object>();
		map.put("cellid", cellid);
		map.put("bscid", bscid);
		map.put("province", province);
		map.put("region", region);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_GPRS_CS.filter3", map);
    }
    
    @SuppressWarnings("unchecked")
    public List<VRpMnCellGprsCs> filter(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear,String bscid, String cellid){
		Map<String, String> map = new HashMap<String, String>();
		map.put("cellid", cellid);
		map.put("bscid", bscid);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
    	return getSqlMapClientTemplate().queryForList("V_RP_MN_CELL_GPRS_CS.filter2", map);
    }

	public Integer countRow(Integer startMonth,Integer startYear, Integer endMonth,Integer endYear, String cellid, String bscid, String province, String region) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("cellid", cellid);
		map.put("bscid", bscid);
		map.put("province", province);
		map.put("startMonth", Integer.toString(startMonth));
		map.put("endMonth", Integer.toString(endMonth));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("region", region);
    	return (Integer) getSqlMapClientTemplate().queryForObject("V_RP_MN_CELL_GPRS_CS.countRow", map);
	}
}