package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpQrCellData2g;

public interface VRpQrCellData2gDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_QR_CELL_DATA_2G
     *
     * @ibatorgenerated Wed Sep 23 15:08:49 ICT 2015
     */
    void insert(VRpQrCellData2g record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_QR_CELL_DATA_2G
     *
     * @ibatorgenerated Wed Sep 23 15:08:49 ICT 2015
     */
    void insertSelective(VRpQrCellData2g record);
    List<VRpQrCellData2g> filter(String startQuarter, String startYear, String endQuarter, String endYear, String cellid, String province, String bscid,
			String region,int order, String column);
}