package vn.com.vhc.vmsc2.statistics.dao;

import java.util.List;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkProvinceBh;


public interface VRpWkProvinceBhDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_PROVINCE_BH
     *
     * @ibatorgenerated Mon Dec 13 10:11:24 ICT 2010
     */
    void insert(VRpWkProvinceBh record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_PROVINCE_BH
     *
     * @ibatorgenerated Mon Dec 13 10:11:24 ICT 2010
     */
    void insertSelective(VRpWkProvinceBh record);

	List<VRpWkProvinceBh> filter(Integer startWeek, Integer startYear, Integer endWeek, Integer endYear, String province, String region);
}