package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkSiteQos;

public class VRpWkSiteQosDAOImpl extends SqlMapClientDaoSupport implements VRpWkSiteQosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE
     *
     * @ibatorgenerated Thu Dec 16 17:13:02 ICT 2010
     */
    public VRpWkSiteQosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE
     *
     * @ibatorgenerated Thu Dec 16 17:13:02 ICT 2010
     */
    public void insert(VRpWkSiteQos record) {
        getSqlMapClientTemplate().insert("V_RP_WK_SITE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE
     *
     * @ibatorgenerated Thu Dec 16 17:13:02 ICT 2010
     */
    public void insertSelective(VRpWkSiteQos record) {
        getSqlMapClientTemplate().insert("V_RP_WK_SITE.ibatorgenerated_insertSelective", record);
    }
    @SuppressWarnings("unchecked")
	public List<VRpWkSiteQos> filter(String province,String bscid, String siteid, Integer week, Integer year, String region) {
		VRpWkSiteQos key = new VRpWkSiteQos();
		key.setProvince(province);
		key.setBscid(bscid);
		key.setSiteid(siteid);
		key.setWeek(week);
		key.setYear(year);
		key.setRegion(region);
		return getSqlMapClientTemplate().queryForList("V_RP_WK_SITE.filter", key);
	}

	@SuppressWarnings("unchecked")
	public List<VRpWkSiteQos> filterDetails(String startWeek, String startYear, String endWeek, String endYear, String bscid, String siteid, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("siteid", siteid);
		map.put("startWeek", startWeek);
		map.put("startYear",  startYear);
		map.put("endWeek", endWeek);
		map.put("endYear",  endYear);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_WK_SITE.filterDetails", map);
	}
}