package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkSiteHoBh;

public class VRpWkSiteHoBhDAOImpl extends SqlMapClientDaoSupport implements VRpWkSiteHoBhDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE_HO_BH
     *
     * @ibatorgenerated Wed Nov 17 11:40:49 ICT 2010
     */
    public VRpWkSiteHoBhDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE_HO_BH
     *
     * @ibatorgenerated Wed Nov 17 11:40:49 ICT 2010
     */
    public void insert(VRpWkSiteHoBh record) {
        getSqlMapClientTemplate().insert("V_RP_WK_SITE_HO_BH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_SITE_HO_BH
     *
     * @ibatorgenerated Wed Nov 17 11:40:49 ICT 2010
     */
    public void insertSelective(VRpWkSiteHoBh record) {
        getSqlMapClientTemplate().insert("V_RP_WK_SITE_HO_BH.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpWkSiteHoBh> filterDetails(String startWeek, String startYear, String endWeek, String endYear, String bscid, String siteid, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("siteid", siteid);
		map.put("startWeek", startWeek);
		map.put("startYear",  startYear);
		map.put("endWeek", endWeek);
		map.put("endYear",  endYear);
		map.put("region", region);
		return getSqlMapClientTemplate().queryForList("V_RP_WK_SITE_HO_BH.filterDetails", map);
	}
}