package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkCellHoBh;

public class VRpWkCellHoBhDAOImpl extends SqlMapClientDaoSupport implements VRpWkCellHoBhDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:47 ICT 2010
     */
    public VRpWkCellHoBhDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:47 ICT 2010
     */
    public void insert(VRpWkCellHoBh record) {
        getSqlMapClientTemplate().insert("V_RP_WK_CELL_HO_BH.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_HO_BH
     *
     * @ibatorgenerated Tue Nov 16 11:26:47 ICT 2010
     */
    public void insertSelective(VRpWkCellHoBh record) {
        getSqlMapClientTemplate().insert("V_RP_WK_CELL_HO_BH.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpWkCellHoBh> filterDetails(String startWeek, String startYear, String endWeek, String endYear, String bscid, String cellid) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("bscid", bscid);
		map.put("cellid", cellid);
		map.put("startWeek", startWeek);
		map.put("startYear",  startYear);
		map.put("endWeek", endWeek);
		map.put("endYear",  endYear);
		return getSqlMapClientTemplate().queryForList("V_RP_WK_CELL_HO_BH.filterDetails", map);
	}
}