package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkCellCapacity;

public class VRpWkCellCapacityDAOImpl extends SqlMapClientDaoSupport implements VRpWkCellCapacityDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_CAPACITY
     *
     * @ibatorgenerated Mon Nov 15 14:24:28 ICT 2010
     */
    public VRpWkCellCapacityDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_CAPACITY
     *
     * @ibatorgenerated Mon Nov 15 14:24:28 ICT 2010
     */
    public void insert(VRpWkCellCapacity record) {
        getSqlMapClientTemplate().insert("V_RP_WK_CELL_CAPACITY.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_CELL_CAPACITY
     *
     * @ibatorgenerated Mon Nov 15 14:24:28 ICT 2010
     */
    public void insertSelective(VRpWkCellCapacity record) {
        getSqlMapClientTemplate().insert("V_RP_WK_CELL_CAPACITY.ibatorgenerated_insertSelective", record);
    }

	
	@SuppressWarnings("unchecked")
    public List<VRpWkCellCapacity> filter(Integer startWeek,Integer startYear,Integer endWeek,Integer endYear, String cellid, String province,String bscid, String region){
    	Map<String, Object> map = new HashMap<String, Object>();
		map.put("cellid", cellid);
		map.put("bscid", bscid);
		map.put("province", province);
		map.put("region", region);
		map.put("startWeek", Integer.toString(startWeek));
		map.put("endWeek", Integer.toString(endWeek));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
    	return getSqlMapClientTemplate().queryForList("V_RP_WK_CELL_CAPACITY.filter3", map);
    }
}