package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpWkDistrictIbc;

public class VRpWkDistrictIbcDAOImpl extends SqlMapClientDaoSupport implements VRpWkDistrictIbcDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_DISTRICT_IBC
     *
     * @ibatorgenerated Mon Dec 20 16:09:19 ICT 2010
     */
    public VRpWkDistrictIbcDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_DISTRICT_IBC
     *
     * @ibatorgenerated Mon Dec 20 16:09:19 ICT 2010
     */
    public void insert(VRpWkDistrictIbc record) {
        getSqlMapClientTemplate().insert("V_RP_WK_DISTRICT_IBC.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_WK_DISTRICT_IBC
     *
     * @ibatorgenerated Mon Dec 20 16:09:19 ICT 2010
     */
    public void insertSelective(VRpWkDistrictIbc record) {
        getSqlMapClientTemplate().insert("V_RP_WK_DISTRICT_IBC.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpWkDistrictIbc> filter(Integer startWeek, Integer startYear, Integer endWeek, Integer endYear, String province, String district, String region) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("district", district);
		map.put("province", province);
		map.put("startWeek", Integer.toString(startWeek));
		map.put("endWeek", Integer.toString(endWeek));
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_WK_DISTRICT_IBC.filter", map);
	}
}