package vn.com.vhc.vmsc2.statistics.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vn.com.vhc.vmsc2.statistics.domain.VRpYrIrsrAlarmDistrict3g;

public class VRpYrIrsrAlarmDistrict3gDAOImpl extends SqlMapClientDaoSupport implements VRpYrIrsrAlarmDistrict3gDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_YR_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:45:04 GMT+07:00 2011
     */
    public VRpYrIrsrAlarmDistrict3gDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_YR_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:45:04 GMT+07:00 2011
     */
    public void insert(VRpYrIrsrAlarmDistrict3g record) {
        getSqlMapClientTemplate().insert("V_RP_YR_IRSR_ALARM_DISTRICT_3G.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table V_RP_YR_IRSR_ALARM_DISTRICT_3G
     *
     * @ibatorgenerated Thu Sep 15 11:45:04 GMT+07:00 2011
     */
    public void insertSelective(VRpYrIrsrAlarmDistrict3g record) {
        getSqlMapClientTemplate().insert("V_RP_YR_IRSR_ALARM_DISTRICT_3G.ibatorgenerated_insertSelective", record);
    }

	@SuppressWarnings("unchecked")
	public List<VRpYrIrsrAlarmDistrict3g> filter(String region, String province, String district, Integer startYear, Integer endYear) {
		Map<String, String> map = new HashMap<String, String>();
		map.put("district", district);
		map.put("province", province);
		map.put("startYear", Integer.toString(startYear));
		map.put("endYear", Integer.toString(endYear));
		map.put("region", region);
    	return getSqlMapClientTemplate().queryForList("V_RP_YR_IRSR_ALARM_DISTRICT_3G.filter", map);
	}
}