package vn.com.vhc.vmsc2.statistics.dao;

import vn.com.vhc.vmsc2.statistics.domain.WkStpAssonciationQos;

public interface WkStpAssonciationQosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    int deleteByPrimaryKey(String stpid, Integer week, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    void insert(WkStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    void insertSelective(WkStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    WkStpAssonciationQos selectByPrimaryKey(String stpid, Integer week, Integer year);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    int updateByPrimaryKeySelective(WkStpAssonciationQos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WK_STP_ASSOCIATION_QOS
     *
     * @ibatorgenerated Wed Oct 27 15:45:27 ICT 2010
     */
    int updateByPrimaryKey(WkStpAssonciationQos record);
}