package vn.com.vhc.vmsc2.statistics.domain;

import java.util.Date;

public class DyProvinceDcrtQos {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.PROVINCE
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.DAY
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F1
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F2
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F3
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F4
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F5
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F6
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F7
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F8
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F9
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F10
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F11
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F12
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F13
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F14
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F15
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F16
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F17
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F18
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F19
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.F20
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private Float f20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_DY_PROVINCE_DCRT_QOS.REGION
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    private String region;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.PROVINCE
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.PROVINCE
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.PROVINCE
     *
     * @param province the value for V_RP_DY_PROVINCE_DCRT_QOS.PROVINCE
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.DAY
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.DAY
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.DAY
     *
     * @param day the value for V_RP_DY_PROVINCE_DCRT_QOS.DAY
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F1
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F1
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF1() {
        return f1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F1
     *
     * @param f1 the value for V_RP_DY_PROVINCE_DCRT_QOS.F1
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF1(Float f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F2
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F2
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF2() {
        return f2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F2
     *
     * @param f2 the value for V_RP_DY_PROVINCE_DCRT_QOS.F2
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF2(Float f2) {
        this.f2 = f2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F3
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F3
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF3() {
        return f3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F3
     *
     * @param f3 the value for V_RP_DY_PROVINCE_DCRT_QOS.F3
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF3(Float f3) {
        this.f3 = f3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F4
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F4
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF4() {
        return f4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F4
     *
     * @param f4 the value for V_RP_DY_PROVINCE_DCRT_QOS.F4
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF4(Float f4) {
        this.f4 = f4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F5
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F5
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF5() {
        return f5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F5
     *
     * @param f5 the value for V_RP_DY_PROVINCE_DCRT_QOS.F5
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF5(Float f5) {
        this.f5 = f5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F6
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F6
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF6() {
        return f6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F6
     *
     * @param f6 the value for V_RP_DY_PROVINCE_DCRT_QOS.F6
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF6(Float f6) {
        this.f6 = f6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F7
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F7
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF7() {
        return f7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F7
     *
     * @param f7 the value for V_RP_DY_PROVINCE_DCRT_QOS.F7
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF7(Float f7) {
        this.f7 = f7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F8
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F8
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF8() {
        return f8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F8
     *
     * @param f8 the value for V_RP_DY_PROVINCE_DCRT_QOS.F8
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF8(Float f8) {
        this.f8 = f8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F9
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F9
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF9() {
        return f9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F9
     *
     * @param f9 the value for V_RP_DY_PROVINCE_DCRT_QOS.F9
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF9(Float f9) {
        this.f9 = f9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F10
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F10
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF10() {
        return f10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F10
     *
     * @param f10 the value for V_RP_DY_PROVINCE_DCRT_QOS.F10
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF10(Float f10) {
        this.f10 = f10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F11
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F11
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF11() {
        return f11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F11
     *
     * @param f11 the value for V_RP_DY_PROVINCE_DCRT_QOS.F11
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF11(Float f11) {
        this.f11 = f11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F12
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F12
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF12() {
        return f12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F12
     *
     * @param f12 the value for V_RP_DY_PROVINCE_DCRT_QOS.F12
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF12(Float f12) {
        this.f12 = f12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F13
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F13
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF13() {
        return f13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F13
     *
     * @param f13 the value for V_RP_DY_PROVINCE_DCRT_QOS.F13
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF13(Float f13) {
        this.f13 = f13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F14
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F14
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF14() {
        return f14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F14
     *
     * @param f14 the value for V_RP_DY_PROVINCE_DCRT_QOS.F14
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF14(Float f14) {
        this.f14 = f14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F15
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F15
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF15() {
        return f15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F15
     *
     * @param f15 the value for V_RP_DY_PROVINCE_DCRT_QOS.F15
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF15(Float f15) {
        this.f15 = f15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F16
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F16
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF16() {
        return f16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F16
     *
     * @param f16 the value for V_RP_DY_PROVINCE_DCRT_QOS.F16
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF16(Float f16) {
        this.f16 = f16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F17
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F17
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF17() {
        return f17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F17
     *
     * @param f17 the value for V_RP_DY_PROVINCE_DCRT_QOS.F17
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF17(Float f17) {
        this.f17 = f17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F18
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F18
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF18() {
        return f18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F18
     *
     * @param f18 the value for V_RP_DY_PROVINCE_DCRT_QOS.F18
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF18(Float f18) {
        this.f18 = f18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F19
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F19
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF19() {
        return f19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F19
     *
     * @param f19 the value for V_RP_DY_PROVINCE_DCRT_QOS.F19
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF19(Float f19) {
        this.f19 = f19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F20
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.F20
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public Float getF20() {
        return f20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.F20
     *
     * @param f20 the value for V_RP_DY_PROVINCE_DCRT_QOS.F20
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setF20(Float f20) {
        this.f20 = f20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.REGION
     *
     * @return the value of V_RP_DY_PROVINCE_DCRT_QOS.REGION
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_DY_PROVINCE_DCRT_QOS.REGION
     *
     * @param region the value for V_RP_DY_PROVINCE_DCRT_QOS.REGION
     *
     * @ibatorgenerated Mon May 23 17:40:04 ICT 2011
     */
    public void setRegion(String region) {
        this.region = region;
    }
}