package vn.com.vhc.vmsc2.statistics.domain;

import java.util.Date;

public class HrBscSignalUtil {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.BSCID
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private String bscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.DAY
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.HOUR
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Integer hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Float utilRxHsl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Float utilRxNb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Float utilTxHsl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    private Float utilTxNb;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.BSCID
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.BSCID
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public String getBscid() {
        return bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.BSCID
     *
     * @param bscid the value for HR_BSC_SIGNAL_UTIL.BSCID
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setBscid(String bscid) {
        this.bscid = bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.DAY
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.DAY
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.DAY
     *
     * @param day the value for HR_BSC_SIGNAL_UTIL.DAY
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.HOUR
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.HOUR
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.HOUR
     *
     * @param hour the value for HR_BSC_SIGNAL_UTIL.HOUR
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_HSL
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.UTIL_RX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Float getUtilRxHsl() {
        return utilRxHsl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_HSL
     *
     * @param utilRxHsl the value for HR_BSC_SIGNAL_UTIL.UTIL_RX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setUtilRxHsl(Float utilRxHsl) {
        this.utilRxHsl = utilRxHsl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_NB
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.UTIL_RX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Float getUtilRxNb() {
        return utilRxNb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_RX_NB
     *
     * @param utilRxNb the value for HR_BSC_SIGNAL_UTIL.UTIL_RX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setUtilRxNb(Float utilRxNb) {
        this.utilRxNb = utilRxNb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_HSL
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.UTIL_TX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Float getUtilTxHsl() {
        return utilTxHsl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_HSL
     *
     * @param utilTxHsl the value for HR_BSC_SIGNAL_UTIL.UTIL_TX_HSL
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setUtilTxHsl(Float utilTxHsl) {
        this.utilTxHsl = utilTxHsl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_NB
     *
     * @return the value of HR_BSC_SIGNAL_UTIL.UTIL_TX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public Float getUtilTxNb() {
        return utilTxNb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_SIGNAL_UTIL.UTIL_TX_NB
     *
     * @param utilTxNb the value for HR_BSC_SIGNAL_UTIL.UTIL_TX_NB
     *
     * @ibatorgenerated Tue Jul 23 18:03:20 ICT 2013
     */
    public void setUtilTxNb(Float utilTxNb) {
        this.utilTxNb = utilTxNb;
    }
}