package vn.com.vhc.vmsc2.statistics.domain;

import java.util.Date;

public class HrBscCore {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.BSCID
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private String bscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.DAY
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.HOUR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Integer hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.CSSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float cssr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.PSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float psr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.DCRS
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float dcrs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.DCRT
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float dcrt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.TRAUCR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float traucr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_BSC_CORE.HSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    private Float hsr;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.BSCID
     *
     * @return the value of HR_BSC_CORE.BSCID
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public String getBscid() {
        return bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.BSCID
     *
     * @param bscid the value for HR_BSC_CORE.BSCID
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setBscid(String bscid) {
        this.bscid = bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.DAY
     *
     * @return the value of HR_BSC_CORE.DAY
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.DAY
     *
     * @param day the value for HR_BSC_CORE.DAY
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.HOUR
     *
     * @return the value of HR_BSC_CORE.HOUR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.HOUR
     *
     * @param hour the value for HR_BSC_CORE.HOUR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.CSSR
     *
     * @return the value of HR_BSC_CORE.CSSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getCssr() {
        return cssr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.CSSR
     *
     * @param cssr the value for HR_BSC_CORE.CSSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setCssr(Float cssr) {
        this.cssr = cssr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.PSR
     *
     * @return the value of HR_BSC_CORE.PSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getPsr() {
        return psr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.PSR
     *
     * @param psr the value for HR_BSC_CORE.PSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setPsr(Float psr) {
        this.psr = psr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.DCRS
     *
     * @return the value of HR_BSC_CORE.DCRS
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getDcrs() {
        return dcrs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.DCRS
     *
     * @param dcrs the value for HR_BSC_CORE.DCRS
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setDcrs(Float dcrs) {
        this.dcrs = dcrs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.DCRT
     *
     * @return the value of HR_BSC_CORE.DCRT
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getDcrt() {
        return dcrt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.DCRT
     *
     * @param dcrt the value for HR_BSC_CORE.DCRT
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setDcrt(Float dcrt) {
        this.dcrt = dcrt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.TRAUCR
     *
     * @return the value of HR_BSC_CORE.TRAUCR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getTraucr() {
        return traucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.TRAUCR
     *
     * @param traucr the value for HR_BSC_CORE.TRAUCR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setTraucr(Float traucr) {
        this.traucr = traucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_BSC_CORE.HSR
     *
     * @return the value of HR_BSC_CORE.HSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public Float getHsr() {
        return hsr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_BSC_CORE.HSR
     *
     * @param hsr the value for HR_BSC_CORE.HSR
     *
     * @ibatorgenerated Mon Oct 18 10:35:49 ICT 2010
     */
    public void setHsr(Float hsr) {
        this.hsr = hsr;
    }
}