package vn.com.vhc.vmsc2.statistics.domain;

import java.util.Date;

public class HrHlrMapQos {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.DAY
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.HLRID
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private String hlrid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.HOUR
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private Integer hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.F1
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private Integer f1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.F2
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private Integer f2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR_HLR_MAP_QOS.F3
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    private Float f3;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.DAY
     *
     * @return the value of HR_HLR_MAP_QOS.DAY
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.DAY
     *
     * @param day the value for HR_HLR_MAP_QOS.DAY
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.HLRID
     *
     * @return the value of HR_HLR_MAP_QOS.HLRID
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public String getHlrid() {
        return hlrid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.HLRID
     *
     * @param hlrid the value for HR_HLR_MAP_QOS.HLRID
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setHlrid(String hlrid) {
        this.hlrid = hlrid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.HOUR
     *
     * @return the value of HR_HLR_MAP_QOS.HOUR
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.HOUR
     *
     * @param hour the value for HR_HLR_MAP_QOS.HOUR
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.F1
     *
     * @return the value of HR_HLR_MAP_QOS.F1
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public Integer getF1() {
        return f1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.F1
     *
     * @param f1 the value for HR_HLR_MAP_QOS.F1
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setF1(Integer f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.F2
     *
     * @return the value of HR_HLR_MAP_QOS.F2
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public Integer getF2() {
        return f2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.F2
     *
     * @param f2 the value for HR_HLR_MAP_QOS.F2
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setF2(Integer f2) {
        this.f2 = f2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR_HLR_MAP_QOS.F3
     *
     * @return the value of HR_HLR_MAP_QOS.F3
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public Float getF3() {
        return f3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR_HLR_MAP_QOS.F3
     *
     * @param f3 the value for HR_HLR_MAP_QOS.F3
     *
     * @ibatorgenerated Thu Oct 14 15:22:10 ICT 2010
     */
    public void setF3(Float f3) {
        this.f3 = f3;
    }
}