package vn.com.vhc.vmsc2.statistics.domain;

import java.math.BigDecimal;
import java.util.Date;

public class VRpHrCellQosHo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.DAY
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.HOUR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private Integer hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.REGION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String region;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.PROVINCE
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.DISTRICT
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String district;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.LOCATION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String location;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.MSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String mscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.BSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String bscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.CELLID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String cellid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.VENDOR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private String vendor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.CSSR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal cssr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.T_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal tDrpr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.S_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal sDrpr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.T_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal tBlkr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.S_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal sBlkr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.T_UTIL
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal tUtil;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.IN_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal inHoSucr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_CELL_QOS_HO.OG_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    private BigDecimal ogHoSucr;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.DAY
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.DAY
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.DAY
     *
     * @param day the value for V_RP_HR_CELL_QOS_HO.DAY
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.HOUR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.HOUR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.HOUR
     *
     * @param hour the value for V_RP_HR_CELL_QOS_HO.HOUR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.REGION
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.REGION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.REGION
     *
     * @param region the value for V_RP_HR_CELL_QOS_HO.REGION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.PROVINCE
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.PROVINCE
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.PROVINCE
     *
     * @param province the value for V_RP_HR_CELL_QOS_HO.PROVINCE
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.DISTRICT
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.DISTRICT
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.DISTRICT
     *
     * @param district the value for V_RP_HR_CELL_QOS_HO.DISTRICT
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.LOCATION
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.LOCATION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.LOCATION
     *
     * @param location the value for V_RP_HR_CELL_QOS_HO.LOCATION
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.MSCID
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.MSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getMscid() {
        return mscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.MSCID
     *
     * @param mscid the value for V_RP_HR_CELL_QOS_HO.MSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setMscid(String mscid) {
        this.mscid = mscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.BSCID
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.BSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getBscid() {
        return bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.BSCID
     *
     * @param bscid the value for V_RP_HR_CELL_QOS_HO.BSCID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setBscid(String bscid) {
        this.bscid = bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.CELLID
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.CELLID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getCellid() {
        return cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.CELLID
     *
     * @param cellid the value for V_RP_HR_CELL_QOS_HO.CELLID
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setCellid(String cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.VENDOR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.VENDOR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.VENDOR
     *
     * @param vendor the value for V_RP_HR_CELL_QOS_HO.VENDOR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.CSSR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.CSSR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal getCssr() {
        return cssr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.CSSR
     *
     * @param cssr the value for V_RP_HR_CELL_QOS_HO.CSSR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setCssr(BigDecimal cssr) {
        this.cssr = cssr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.T_DRPR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.T_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal gettDrpr() {
        return tDrpr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.T_DRPR
     *
     * @param tDrpr the value for V_RP_HR_CELL_QOS_HO.T_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void settDrpr(BigDecimal tDrpr) {
        this.tDrpr = tDrpr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.S_DRPR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.S_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal getsDrpr() {
        return sDrpr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.S_DRPR
     *
     * @param sDrpr the value for V_RP_HR_CELL_QOS_HO.S_DRPR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setsDrpr(BigDecimal sDrpr) {
        this.sDrpr = sDrpr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.T_BLKR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.T_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal gettBlkr() {
        return tBlkr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.T_BLKR
     *
     * @param tBlkr the value for V_RP_HR_CELL_QOS_HO.T_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void settBlkr(BigDecimal tBlkr) {
        this.tBlkr = tBlkr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.S_BLKR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.S_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal getsBlkr() {
        return sBlkr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.S_BLKR
     *
     * @param sBlkr the value for V_RP_HR_CELL_QOS_HO.S_BLKR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setsBlkr(BigDecimal sBlkr) {
        this.sBlkr = sBlkr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.T_UTIL
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.T_UTIL
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal gettUtil() {
        return tUtil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.T_UTIL
     *
     * @param tUtil the value for V_RP_HR_CELL_QOS_HO.T_UTIL
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void settUtil(BigDecimal tUtil) {
        this.tUtil = tUtil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.IN_HO_SUCR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.IN_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal getInHoSucr() {
        return inHoSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.IN_HO_SUCR
     *
     * @param inHoSucr the value for V_RP_HR_CELL_QOS_HO.IN_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setInHoSucr(BigDecimal inHoSucr) {
        this.inHoSucr = inHoSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_CELL_QOS_HO.OG_HO_SUCR
     *
     * @return the value of V_RP_HR_CELL_QOS_HO.OG_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public BigDecimal getOgHoSucr() {
        return ogHoSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_CELL_QOS_HO.OG_HO_SUCR
     *
     * @param ogHoSucr the value for V_RP_HR_CELL_QOS_HO.OG_HO_SUCR
     *
     * @ibatorgenerated Tue Nov 23 09:30:54 ICT 2010
     */
    public void setOgHoSucr(BigDecimal ogHoSucr) {
        this.ogHoSucr = ogHoSucr;
    }
}