package vn.com.vhc.vmsc2.statistics.domain;

import java.util.Date;

public class VRpHrBscGprsQos {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.DAY
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Date day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.HOUR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Integer hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.REGION
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private String region;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.MSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private String mscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.BSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private String bscid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float dlTbfReq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float dlTbfSucr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float ulTbfReq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float ulTbfSucr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.GDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float gdlTraf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.GUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float gulTraf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.EDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float edlTraf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_HR_BSC_GPRS_QOS.EUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    private Float eulTraf;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.DAY
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.DAY
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.DAY
     *
     * @param day the value for V_RP_HR_BSC_GPRS_QOS.DAY
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.HOUR
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.HOUR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.HOUR
     *
     * @param hour the value for V_RP_HR_BSC_GPRS_QOS.HOUR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.REGION
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.REGION
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.REGION
     *
     * @param region the value for V_RP_HR_BSC_GPRS_QOS.REGION
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.MSCID
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.MSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public String getMscid() {
        return mscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.MSCID
     *
     * @param mscid the value for V_RP_HR_BSC_GPRS_QOS.MSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setMscid(String mscid) {
        this.mscid = mscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.BSCID
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.BSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public String getBscid() {
        return bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.BSCID
     *
     * @param bscid the value for V_RP_HR_BSC_GPRS_QOS.BSCID
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setBscid(String bscid) {
        this.bscid = bscid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_REQ
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.DL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getDlTbfReq() {
        return dlTbfReq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_REQ
     *
     * @param dlTbfReq the value for V_RP_HR_BSC_GPRS_QOS.DL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setDlTbfReq(Float dlTbfReq) {
        this.dlTbfReq = dlTbfReq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_SUCR
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.DL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getDlTbfSucr() {
        return dlTbfSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.DL_TBF_SUCR
     *
     * @param dlTbfSucr the value for V_RP_HR_BSC_GPRS_QOS.DL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setDlTbfSucr(Float dlTbfSucr) {
        this.dlTbfSucr = dlTbfSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_REQ
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.UL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getUlTbfReq() {
        return ulTbfReq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_REQ
     *
     * @param ulTbfReq the value for V_RP_HR_BSC_GPRS_QOS.UL_TBF_REQ
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setUlTbfReq(Float ulTbfReq) {
        this.ulTbfReq = ulTbfReq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_SUCR
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.UL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getUlTbfSucr() {
        return ulTbfSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.UL_TBF_SUCR
     *
     * @param ulTbfSucr the value for V_RP_HR_BSC_GPRS_QOS.UL_TBF_SUCR
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setUlTbfSucr(Float ulTbfSucr) {
        this.ulTbfSucr = ulTbfSucr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.GDL_TRAF
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.GDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getGdlTraf() {
        return gdlTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.GDL_TRAF
     *
     * @param gdlTraf the value for V_RP_HR_BSC_GPRS_QOS.GDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setGdlTraf(Float gdlTraf) {
        this.gdlTraf = gdlTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.GUL_TRAF
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.GUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getGulTraf() {
        return gulTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.GUL_TRAF
     *
     * @param gulTraf the value for V_RP_HR_BSC_GPRS_QOS.GUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setGulTraf(Float gulTraf) {
        this.gulTraf = gulTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.EDL_TRAF
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.EDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getEdlTraf() {
        return edlTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.EDL_TRAF
     *
     * @param edlTraf the value for V_RP_HR_BSC_GPRS_QOS.EDL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setEdlTraf(Float edlTraf) {
        this.edlTraf = edlTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_HR_BSC_GPRS_QOS.EUL_TRAF
     *
     * @return the value of V_RP_HR_BSC_GPRS_QOS.EUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public Float getEulTraf() {
        return eulTraf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_HR_BSC_GPRS_QOS.EUL_TRAF
     *
     * @param eulTraf the value for V_RP_HR_BSC_GPRS_QOS.EUL_TRAF
     *
     * @ibatorgenerated Wed Nov 17 14:38:52 ICT 2010
     */
    public void setEulTraf(Float eulTraf) {
        this.eulTraf = eulTraf;
    }
}