package vn.com.vhc.vmsc2.statistics.domain;

import java.math.BigDecimal;

public class VRpQrIrsrAlarmDistrict3g {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.YEAR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    private Integer year;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.QUARTER
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    private BigDecimal quarter;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.REGION
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    private String region;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.IRSR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    private Float irsr;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.YEAR
     *
     * @return the value of V_RP_QR_IRSR_ALARM_DISTRICT_3G.YEAR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.YEAR
     *
     * @param year the value for V_RP_QR_IRSR_ALARM_DISTRICT_3G.YEAR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.QUARTER
     *
     * @return the value of V_RP_QR_IRSR_ALARM_DISTRICT_3G.QUARTER
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public BigDecimal getQuarter() {
        return quarter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.QUARTER
     *
     * @param quarter the value for V_RP_QR_IRSR_ALARM_DISTRICT_3G.QUARTER
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public void setQuarter(BigDecimal quarter) {
        this.quarter = quarter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.REGION
     *
     * @return the value of V_RP_QR_IRSR_ALARM_DISTRICT_3G.REGION
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.REGION
     *
     * @param region the value for V_RP_QR_IRSR_ALARM_DISTRICT_3G.REGION
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.IRSR
     *
     * @return the value of V_RP_QR_IRSR_ALARM_DISTRICT_3G.IRSR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public Float getIrsr() {
        return irsr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column V_RP_QR_IRSR_ALARM_DISTRICT_3G.IRSR
     *
     * @param irsr the value for V_RP_QR_IRSR_ALARM_DISTRICT_3G.IRSR
     *
     * @ibatorgenerated Thu Sep 15 11:45:36 GMT+07:00 2011
     */
    public void setIrsr(Float irsr) {
        this.irsr = irsr;
    }
}